### ISSUE TITLE
Suggestion: Remove `laravel-` prefix on the config file

### ISSUE THREAD

**Issue by edsamonte** [auth0/laravel-auth0#101]
Just a suggestion: remove `laravel-` on the config filename. It feels redundant. Laravel config mostly named after the service only without the `laravel-` prefix. Besides `auth0.php` seems pretty unique already.

It does not have any benefits aside from the aesthetics but will have an impact on backward compatibility, that I'm aware. Just voicing out here.

Cheers!

**Comment by dmyers** [comment]
Great idea! I also thought that was a bit redundant and would prefer to see `config/auth0.php` in my Laravel app. This would better follow Laravel conventions as well.

**Comment by joshcanhelp** [comment]
Being discussed in the PR above ☝️ and in #105
