### ISSUE TITLE
How do you combine Auth0 Lock with Laravel Auth0?

### ISSUE THREAD

**Issue by edsamonte** [auth0/laravel-auth0#102]
Is there a way to combine Auth0 Lock with Laravel Auth0?

Auth0 Lock supports `responseType=code`, and I'm planning to use Laravel Auth0 to handle the callback. Unfortunately, Laravel Auth0 has a stateful approach but there's no exposed function to issue a state token to the blade template. 

Maybe changing the private properties and functions of `Auth0Service` is a good start so we could override and customize its behaviour?

I hope you could help. Thanks.

**Comment by joshcanhelp** [comment]
Hi @edsamonte,

This Laravel library is built on top of our [PHP SDK](https://github.com/auth0/auth0-PHP) and the callback handling is the same whether you use the hosted login page or Lock. You can stop the PHP SDK from handling state by [passing in a dummy state handler](https://github.com/auth0/auth0-PHP/blob/master/src/Auth0.php#L243) on initialization. Then you can generate and store a value, pass that to Lock, and check within the callback. 

That said, the options used to initialize the PHP SDK are [loaded from the config file](https://github.com/auth0/laravel-auth0/blob/master/src/Auth0/Login/Auth0Service.php#L30) so you could pass that same dummy state handler in by default and handle state validation yourself. I have not tried this specifically so if you get stuck, let me know and I'm happy to help!

**Comment by edsamonte** [comment]
@joshcanhelp unfortunately, SessionStore is hardcoded. See https://github.com/auth0/laravel-auth0/blob/master/src/Auth0/Login/Auth0Service.php#L26. It is not even using Laravel's Dependency Injection. So whatever the value of your store in the config file, it won't work.

**Comment by edsamonte** [comment]
Thanks for the suggestion, @joshcanhelp. 

Though, it is not a good idea to create instantiated object on the config file. Config values should be as primitive as possible.

As a workaround, I just create a `BootServiceProvider` which is at the very first of all the service providers which sets the `laravel-auth0.state_handler`:
```php
// BootServiceProvider
public function boot(){
    config([
        'laravel-auth0.state_handler' => new MyCustomStateHandler(new SessionStore())
    ]);
}
```

**Comment by joshcanhelp** [comment]
I should have mentioned, you can also just pass in `false` and the dummy one will be used.
