### ISSUE TITLE
Changing name of user identifier

### ISSUE THREAD

**Issue by glaesser** [auth0/laravel-auth0#115]
Is there an easy way to change the user identifier from "sub" to something more descriptive like "auth0id"? I haven't been able to figure it out.

**Comment by joshcanhelp** [comment]
@glaesser - That's the default identifier claim in an OIDC ID token, it's short for "subject." It's used for both Auth0-generated identifiers as well as IDs from other providers (Twitter, Facebook, etc). It might not seem intuitive at first but it conforms to identity standards.

[Reference](https://tools.ietf.org/html/rfc7519#section-4.1.2)
