### ISSUE TITLE
API routes broken in auth0-laravel-php-web-app (and in general)?

### ISSUE THREAD

**Issue by glaesser** [auth0/laravel-auth0#117]
While app authentication works great, in the webapp example navigating to the existing route /api/user throws various errors:

```
Invalid state
Auth0\SDK\Exception\CoreException 
…/vendor/auth0/auth0-php/src/Auth0.php line 512
```
and

```
Can't initialize a new session while there is one active session already
Auth0\SDK\Exception\CoreException 
…/vendor/auth0/auth0-php/src/Auth0.php line 516
```
I seem to be encountering a similar behavior (error claiming I am unauthorized when I'm in fact logged in) in my own app when viewing /api/test (protected only with "auth" or "auth:api" middleware). Would be great to get this working...

**Comment by joshcanhelp** [comment]
@glaesser - I don't think this is an issue with the package itself. Could I get you to start a thread on the Community site with the steps to reproduce and any code samples you can provide? Make sure to tag that `laravel` so it gets to the right place. 

For context ... "Invalid state" occurs when the state value in the URL does not match what's stored or is missing. "Can't initialize a new session while there is one active session already" means you're trying to start a new session when there is one in place already.
