### ISSUE TITLE
Redirect to previous page after login

### ISSUE THREAD

**Issue by kavvson** [auth0/laravel-auth0#122]
For a while now I am trying to figure out how can I implement redirect after login to previous page, since each time I login now it takes me back to the site root. 

Routes file
`
Route::get('/auth0/callback', 'IndexController@callback')->name('auth0-callback');
Route::get('/register', 'Auth\Auth0IndexController@login')->name('register');
Route::get('/login', ['as' => 'login', 'uses' => 'IndexController@login']);
Route::get('/logout', ['as' => 'logout', 'uses' => 'IndexController@logout']);
`

**IndexController**

>     protected $userRepository;
> 
>     public function __construct(Auth0UserRepository $userRepository)
>     {
>         $this->userRepository = $userRepository;
>     }
> 
>     public function callback()
>     {
>         $service = \App::make('auth0');
> 
>         // Try to get the user information
>         $profile = $service->getUser();
> 
>         // Get the user related to the profile
>         $auth0User = $this->userRepository->getUserByUserInfo($profile);
> 
>         if ($auth0User) {
>             if ($service->hasOnLogin()) {
>                 $user = $service->callOnLogin($auth0User);
>             } else {
>                 // If not, the user will be fine
>                 $user = $auth0User;
>             }
>             \Auth::login($user, $service->rememberUser());
>         }
> 
>         return \Redirect::intended('/');
>     }
> 
>  public function login()
>     {
>         return \App::make('auth0')->login(null, null, ['scope' => 'openid email email_verified user_metadata profile'], 'code');
>     }
> 
>     public function logout()
>     {
>         \Auth::logout();
>         Session::flush();
>         return \Redirect::intended(URL::previous());
>     }

**Comment by joshcanhelp** [comment]
@kavvson - Thanks for the report here. Are you looking to do some kind of custom logic to change where the user is redirected or do you just need them redirected somewhere else after logging in?

**Comment by kavvson** [comment]
> @kavvson - Thanks for the report here. Are you looking to do some kind of custom logic to change where the user is redirected or do you just need them redirected somewhere else after logging in?

I just want a simple redirect to the previous page, no role-based or anything.

**Comment by joshcanhelp** [comment]
If you need the previous page then that will take some logic during the process. You need to store the original URL somewhere (session, probably) and then use that URL in the callback. The typical way to do that is to store it in the `state` parameter (along with a random string) that's sent to Auth0 and verified on the way back. As this package is built, though, I'm not seeing a simple way to do that so you'll need to store before redirecting (maybe use `URL::previous()` in the login method) and then use that in a custom callback.

**Comment by kavvson** [comment]
> If you need the previous page then that will take some logic during the process. You need to store the original URL somewhere (session, probably) and then use that URL in the callback. The typical way to do that is to store it in the `state` parameter (along with a random string) that's sent to Auth0 and verified on the way back. As this package is built, though, I'm not seeing a simple way to do that so you'll need to store before redirecting (maybe use `URL::previous()` in the login method) and then use that in a custom callback.

Could you show me an example approach?

**Comment by joshcanhelp** [comment]
Not tested but ...

**Login**

```php
class Auth0IndexController extends Controller
{
    // ...
    public function login()
    {
        session(['auth_return_to_url' => URL::previous()]);
        return \App::make('auth0')->login(null, null, ['scope' => 'openid name email email_verified'], 'code');
    }
    // ...
}
```

**Callback**

```php
class Auth0Controller extends Controller
{
    // ...
    public function callback()
    {
        // ...
        $redirect_to = session('auth_return_to_url', '/');
        return \Redirect::intended($redirect_to);
    }
}
```

**Comment by samsebastian** [comment]
It would be great to make the redirect string a protected property to avoid having to clone out a copy of the callback function..

ie

```php
class Auth0Controller extends Controller
{
   protected $redirectTo;
   
    public function __construct(Auth0UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
        $this->setRedirect();
    }
   protected function setRedirect() {
      $this->redirectTo = empty($this->redirectTo) ? '/' : $this->redirectTo;
   }
}
```

That way it would be trivial for users to just extend `\Auth0\Login\Auth0Controller` and either set a static string for `protected $redirectTo` attribute or override the `setRedirect()` function if they are using a session variable that needs logic without having the mess around with the main `callback()` function that might be changed and break in the future...

I'm always nervous about overriding a complex function just to do something like rewrite the redirect path...

If there's any interest I'd be happy to do a PR

**Comment by omidMolaverdi** [comment]
Does anybody know how to skip register and login page in redirect to the previous page after a successful login in?
