### ISSUE TITLE
How can I get auth()->id() as integer

### ISSUE THREAD

**Issue by saqueib** [auth0/laravel-auth0#137]
### Description

When I run `auth()->id()` its giving me `auth0|*****cfc5f8c70ffeebc135` which is causing issue in laravel nova which uses `int` for action_events recoding.

### Prerequisites

- Version of the module used: 5.0
- Version of PHP used: 7.1
- Version of Laravel used: 5.8
- Apache/Nginx and MySQL versions, if related: Nginx
- Additional packages that might be affecting your instance: Laravel Nova

### Reproduction

I followed this https://auth0.com/docs/quickstart/webapp/laravel/01-login and everything worked great, but when you go to nova it showing error 

```
Incorrect integer value: 'auth0|*******5f8c70ffeebc135' for column 'user_id'
```

it's trying to insert string into `int` column, Is there any way I can get user id from my database table instead of string. I already setup https://auth0.com/docs/quickstart/webapp/laravel/01-login#optional-custom-user-handling

**Comment by saqueib** [comment]
### Update

I tired digging into code so I find out if change the `vendor/auth0/login/src/Auth0/Login/Auth0User.php:34` to return user id it works 

```php
public function getAuthIdentifier()
    {
      if (isset($this->userInfo['sub'])) {
        return $this->userInfo['id']; // changed it to return the id
      }
      return $this->userInfo['user_id'];
    }
```

**Comment by saqueib** [comment]
I just overwritten the `getAuthIdentifier()` method on the user and returned that instance from `CustomUserRepository`

```
use App\Auth0User;

class CustomUserRepository extends Auth0UserRepository
{

   ...

    /**
     * Get a User from the database using Auth0 profile information
     *
     * @param array $userinfo
     *
     * @return Auth0User
     */
    public function getUserByUserInfo( $userinfo ) {
        $user = $this->upsertUser( $userinfo['profile'] );
        return new Auth0User( $user->getAttributes(), $userinfo['accessToken'] );
    }

```

But I would love to have a config for this, like `config('laravel-auth0.auth_identifier')` which we can use to define the key we need for auth()->id().

**Comment by joshcanhelp** [comment]
@saqueib - Apologies for the delayed response but glad you got it figured out. We're looking into how to improve this library and will take your feedback here into account.
