### ISSUE TITLE
Feature request: Add Laravel 6 support

### ISSUE THREAD

**Issue by FreekVR** [auth0/laravel-auth0#138]
Hi!

Laravel 6 was released a few days ago, but since they switched to semver, laravel-auth0 isn't installable as it needs to indicate compatibility in the `composer.json`

I've done some testing yesterday on a fork where I only changed the composer.json, and all functionality seemed to be fine, a quick scan of the codebase also didn't turn up any things that should be changed according to the laravel ugprade guide.

I'll submit a PR to make this package compatible, but please let me know if there's anything I missed.

**Comment by joshcanhelp** [comment]
@FreekVR - Thank you for the report here! We have someone internally testing this as well and will merge your PR #139 when that's complete.

**Comment by joshcanhelp** [comment]
@carnevalle - I'll get this out first thing next week. First round of internal testing is complete, just want to make sure we cover as many use cases as we can 👍

**Comment by giannidhooge** [comment]
@joshcanhelp Any idea when `5.3.0` will be tagged?

**Comment by joshcanhelp** [comment]
@giannidhooge - Thanks for checking in. I'm just waiting to see if we can get #135 in without breaking changes and we'll get that release cut. Appreciate your patience!

**Comment by joshcanhelp** [comment]
`5.3.0` is released with Laravel 6 support and fixed sessions! 🎉 

https://github.com/auth0/laravel-auth0/releases/tag/5.3.0
https://packagist.org/packages/auth0/login#5.3.0
