### ISSUE TITLE
Username/Name not being picked up by $profile variable in custom user repository

### ISSUE THREAD

**Issue by krthush** [auth0/laravel-auth0#146]
Following on again from here: https://auth0.com/docs/quickstart/webapp/laravel/01-login, I'm using a very slightly modified version of the app/Repositories/CustomUserRepository.php as shown in the docs.

Authenication and everything else works fine, but unfortunatly when I set up usernames (as shown here: https://auth0.com/docs/connections/database/require-username), the username field comes up on my form when a user tries to signup, but unfortunatly does not get passed to the $profile variable and thus I'm unable to handle it with Laravel and store it in my local user profile database.

i.e. "$user->setAttribute( 'name', isset( $profile['name'] ) ? $profile['name'] : '' );" will not have any value...

Am I missing something?

**Comment by joshcanhelp** [comment]
@krthush - Apologies for the delay here!

The `name` property should actually be the real name (or whatever name should be displayed) for the user. For new users, the property that typically contains the DB username on signup is actually `nickname`. The thing to note here, though, is that `username` is actually it's own property for the user and it's not, by default, sent back to your application as part of the profile. 

If you click on the **Raw JSON** tab for one of your Users in the Auth0 dashboard, you'll see both `nickname` and `username`:

![Screenshot 2019-10-10 15 39 34](https://user-images.githubusercontent.com/855223/66611712-405bc300-eb74-11e9-9377-abbadbb3b274.png)

This means that the `nickname` portion of the profile can be updated at some point in the future and it will not match the `username` in Auth0, nor will it match what you have in your database. 

So, you have a few options:

- Skip storing the username in your database and instead rely on the email or the Auth0 user ID (`sub` property in the profile)
- Add the `username` field from the user as a custom claim using a Rule ([explained here](https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims#custom-claims)).

Hope that helps! I'll close this for now but let me know if you have any additional questions.

**Comment by joshcanhelp** [comment]
Happy to help! There's only so much documentation we can provide before it starts to get overwhelming :)

If you're just using the name to display and not to, say, match incoming users, that should work fine. In fact it's generally what that field is for.

**Comment by krthush** [comment]
Okay so I think I've managed to get it working (or at least what I need - which is storing the username the user enters on sign up). I did this through doing what you suggested using a custom claim rule.

But I'm a bit curious about exactly whats going on **(sorry for turning this Git Issue into a Q&A, only answer back when you have the time)**. So for starters, my main issue started with the $profile variable, which originates from the Auth0 source code here (auth0/login/src/controllers/Auth0Controller)... 

![image](https://user-images.githubusercontent.com/33790334/66667874-ed553f00-ec4b-11e9-85e7-c68b4963d8be.png)

For which the dump is...

![image](https://user-images.githubusercontent.com/33790334/66668987-72d9ee80-ec4e-11e9-88ef-2972b4d35e82.png)

This $profile variable is what bubbles down to then being used by the upsertUser() function in the CustomUserRepo. Now since I wanted to include more fields into this $profile variable, I looked into the custom rules as you suggested, and at first I tried this:

![image](https://user-images.githubusercontent.com/33790334/66669282-07dce780-ec4f-11e9-9410-b27a7d56937b.png)

This didn't really lead to anything, I was hoping to be able to access $profile['username'] or something like that... But then I tried following the docs more precisely and added in my site's namespace as such:

![image](https://user-images.githubusercontent.com/33790334/66669367-3b1f7680-ec4f-11e9-8ceb-40903eb20a2e.png)

Voila! This worked, resulting in a $profile as follows:

![image](https://user-images.githubusercontent.com/33790334/66669416-630eda00-ec4f-11e9-8def-07a28972cd5d.png)

My curiosity here being, why does adding the namespace allow for the $profile now to show additional fields? Because of this I've had to include that same namespace string in my laravel code to be able to access it from the $profile array. Am right in saying it has something to do with the OIDC specifications?

Side Note: Thanks to your suggestion with custom rules I discovered I can log the timezone as well which I need anyways - saved me time in the future 🤸‍♂ I'll edit the issue name so more people can find this easily 🔍 

Thanks again for all the help, you really are super awesomes!

**Comment by joshcanhelp** [comment]
> saved me time in the future 

That's like pretty much our favorite thing to do!

> My curiosity here being, why does adding the namespace allow for the $profile now to show additional fields?

You're on the right track with the OIDC comment. OIDC doesn't say you have to use that specific namespace (URL), but it does reserve certain claims that are used to check token validity, communicate profile data, etc. There is a bit more information on the "why" part of this here:

https://auth0.com/docs/tokens/jwt-claims#custom-claims

> Thanks again for all the help, you really are super awesomes!

Thank you for saying so, that totally made my Friday ❤️ We try to make this stuff as simple as possible but it's a tough topic ... makes for a truly challenging and fun job 😄
