### ISSUE TITLE
Following the "CustomUserRepository" I get: Field 'sub' doesn't have a default value 

### ISSUE THREAD

**Issue by rlewkowicz** [auth0/laravel-auth0#168]
### Description

Following the "CustomUserRepository" I get: Field 'sub' doesn't have a default value. Doing a dd it shows that the user does indeed exist in the object. 

```
array:7 [▼
  "sub" => "auth0|5e5ffb9d014e73163f5b1d44"
  "nickname" => "ryan.m.lewkowicz"
  "name" => "ryan.m.lewkowicz@gmail.com"
  "picture" => "https://s.gravatar.com/avatar/6988fd52c049a43ded4580b7fea754b7?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fry.png"
  "updated_at" => "2020-03-09T16:57:39.200Z"
  "email" => "ryan.m.lewkowicz@gmail.com"
  "email_verified" => false
]
```
This is the function from the article, I modified it, but its the same error

```
    protected function upsertUser( $profile ) {  
        $sub  = $profile['sub'];
        $email = $profile['email'];
        $name = $profile['name'];
        return User::firstOrCreate(compact("sub","email","name"));
    }
```

Something has to be dying in firstOrCreate. Like it's trying to pass a null then complains that sub doesn't have a default and is not nullable 

### Reproduction

Add CustomUserRepository to https://auth0.com/blog/build-a-laravel-6-app-with-authentication/

### Environment

> Please provide the following:
```
"name": "auth0/auth0-php"
"version": "5.7.0"

"name": "auth0/login"
"version": "5.3.1"
```
Laravel Framework 6.18.0

Yea so by the looks of it its just not passing the variable even though the docs say it should
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/17415445/76248507-d6754180-6217-11ea-92c1-7c416dfd5b5e.png">

**Comment by rlewkowicz** [comment]
God what a terrible adventure. Ok. So I'm following this auth0 demo app and in it they have a models folder. In that there is users. That is not what you want. App/model/users is not App/user. You have to make sub fillable on  on app user which extends Auth\User and not the model user. I'm leaving this open because I need to update the docs

**Comment by rlewkowicz** [comment]
@joshcanhelp 

https://github.com/auth0/docs/pull/8826 

Idk if you can approve this, but it should save someone some time down the road

**Comment by joshcanhelp** [comment]
@rlewkowicz - Sorry for the trouble here and delayed replies. Appreciate the PR on docs and will respond there 👍
