### ISSUE TITLE
Laravel 7.0 supported release.

### ISSUE THREAD

**Issue by wotta** [auth0/laravel-auth0#171]
### Release a Laravel 7.0 supported release.

> This would fix the need of requiring dev-master and possibly breaking the application.

### Describe the ideal solution

> Create a new release version that supports laravel 7.0

## Alternatives and current work-arounds

> Create a stable laravel 7.0 dev branch.

### Additional context

My composer error atm.
`auth0/login 5.3.0 requires illuminate/support 5.* | ^6.0`

**Comment by giannidhooge** [comment]
Composer issue is fixed in #167. Waiting on #166 to be tested and to tag a release.

**Comment by wotta** [comment]
Thanks for the information 🙂

**Comment by joshcanhelp** [comment]
🚀 Releasing now! Apologies for the delay.

**Comment by wotta** [comment]
@joshcanhelp no worries have been busy with a lot of other stuff.
