### ISSUE TITLE
Target class [App\Repositories\CustomUserRepository] does not exist.

### ISSUE THREAD

**Issue by craigpotter** [auth0/laravel-auth0#182]
### Description

I have tried to follow the latest guide located [here](https://auth0.com/docs/quickstart/webapp/laravel) on a fresh install of Laravel v7.6.1. 
It works until I try to implement the custom user handling. 

I just get `Target class [App\Repositories\CustomUserRepository] does not exist.`

I've tried doing `composer dump` and clearing Laravel cache. 

I found if I remove ` extends Auth0UserRepository` from the class definition, it appears to work and the class is autoloaded. 

I did some digging and it appears to be because the example code for the CustomUserRepository is no longer compatible with Auth0UserRepository. 

```
[2020-04-15 22:37:36] local.ERROR: Declaration of App\Repositories\CustomUserRepository::getUserByDecodedJWT($jwt) must be compatible with Auth0\Login\Repository\Auth0UserRepository::getUserByDecodedJWT(array $decodedJwt): 
```
This also help justify the trait being discussed on #165 

Fixing this to be compatible with `Auth0\Login\Repository\Auth0UserRepository` means you can no longer return the User eloquent model from the `getUserByUserInfo` method either. 

### Reproduction

Follow https://auth0.com/docs/quickstart/webapp/laravel

### Environment

> Please provide the following:

- **Version of this library used:6.0.0
- **Version of the platform or framework used, if applicable:Laravel 7.6.1

**Comment by espenlg** [comment]
I'm having the exact same problem. Did you happen to find a solution @craigpotter?

**Comment by miking7** [comment]
For anyone (ie: @espenlg) who is having the same problems, I've just raised an issue against the Laravel docs which provides a solution to this problem:
[https://github.com/auth0/docs/issues/9002](https://github.com/auth0/docs/issues/9002)

**Comment by joshcanhelp** [comment]
@miking7 - Thank you for the report and fix submitted on the docs site. I just put through a PR there with the new class:

https://github.com/auth0/docs/pull/9056
