### ISSUE TITLE
disabling registration of new users in laravel 7

### ISSUE THREAD

**Issue by mons-reys** [auth0/laravel-auth0#185]
hello, i'm using laravel but i can't disable registration

Auth::routes([
'register' => false, // Registration Routes...
'reset' => false, // Password Reset Routes...
'verify' => false, // Email Verification Routes...
]);

this line doesn't work with me, someone explain why ?
Ps: when i use the line nothing happening...the registration still shows itself ( like the  register still always true ).

**Comment by craigpotter** [comment]
have you tried doing 
`php artisan route:clear`  
?

**Comment by Tamrael** [comment]
[Auth::routes and route caching is not part of this repo, it's part of laravel](https://laravel.com/docs/7.x/authentication#included-routing)
