### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by affektde** [auth0/laravel-auth0#188]
### Describe the problem you'd like to have solved

Today Laravel 8 was released. It would be wonderful if we can continue to use our projects with the Auth0 plugin and the fresh new version of Laravel.

**Comment by EmielSchmeink** [comment]
I too, would like this.

**Comment by lbalmaceda** [comment]
Will be available in the next release

**Comment by bkilshaw** [comment]
An ETA on the next release?

**Comment by lbalmaceda** [comment]
@bkilshaw support for Laravel 8 should be already available in version 6.1.0 (PR linked above). What problem are you facing?

**Comment by evansims** [comment]
Hey Brad! 👋  6.1 works with Laravel 8, unless you're hitting a specific issue I'm not aware of. I recently updated [our Laravel quickstart to use both](https://github.com/auth0-samples/auth0-laravel-php-web-app/blob/master/01-Login/composer.json).

**Comment by bkilshaw** [comment]
Sorry, got issues mixed up on this one, don't need Laravel 8 support myself (yet).

**Comment by evansims** [comment]
No problem Brad, thanks for letting us know
