### ISSUE TITLE
authorized_issuers have no meaning anymore?

### ISSUE THREAD

**Issue by afreakk** [auth0/laravel-auth0#194]
### Description

Earlier version of this library, you could have a list of authorized issuers,
Now https://github.com/auth0/laravel-auth0/blob/master/src/config/config.php#L64 is not even used, so could be removed.

Were using custom domain for login, but the jwttoken often has https://**.eu.auth0.com/, depending on what url the frontend/app used for authentication.
So we really needed having 2 allowed authorizers, but i see there is no possibility for that anymore, and the config hints that its possible.

### Reproduction

Just search
https://github.com/auth0/laravel-auth0/search?q=authorized_issuers
its not being used anywhere.

**Comment by afreakk** [comment]
made it work for us by forking auth0-php & laravel-auth0 like this
https://github.com/dx-oss/auth0-PHP
https://github.com/dx-oss/laravel-auth0
but would be nice to not have to use forked versions

**Comment by afreakk** [comment]
Made it work for us by forking it like this:
https://github.com/dx-oss/laravel-auth0
https://github.com/dx-oss/auth0-PHP

**Comment by Tamrael** [comment]
@evansims [this commit](https://github.com/auth0/laravel-auth0/commit/420cd6ce945b4e93d3f935e03ae03170f23cafe3) removed the authorized issuers from the repo. it was part of the sdk update. look for the function "decodeJWT", the new version uses TokenVerifier [which doesn't suport multiple issuers](https://github.com/auth0/auth0-PHP/blob/ccead4f3eab36703b905eee49e9e61a282cb7694/src/Helpers/Tokens/TokenVerifier.php#L52) but the old [JWTVerifier did](https://github.com/auth0/auth0-PHP/blob/1bf6d8568fe729804922afa28dfb4107e9c20225/src/JWTVerifier.php#L86)

**Comment by la-roberto** [comment]
Hi there, just checking in on the status of this issue. I have a repository that has relies on two authorizers that is preventing me from upgrading my project.

**Comment by evansims** [comment]
Hey @la-roberto 👋 Sorry this has been a blocker on upgrading for you! I hate to hear that.

As reintroducing this functionality on the upstream SDK will result in breaking changes, I'm waiting for plans to solidify around the next major release to squeeze this in there. I'll update as a timetable around that begins to take shape.

**Comment by evansims** [comment]
Just an update on this, I've slotted this for reintroduction in the upstream SDK in its next major, so we'll return support for that in this library when that is released. As this work is really centered around the upstream SDK I'm going to close this one.
