### ISSUE TITLE
5.3 => 6.1 upgrade, "Can't initialize a new session while there is one active session already"

### ISSUE THREAD

**Issue by bkilshaw** [auth0/laravel-auth0#195]
### Description

I currently have an application running on version 5.3 of laravel-auth0. I'm trying to upgrade to the latest version (6.1) and after the upgrade any attempt to login results in "Can't initialize a new session while there is one active session already". I've flushed all sessions locally, deleted cookies, and manually hit the logout endpoint for good measure.

### Reproduction

Update composer.json:
Old: `"auth0/login": "^5.3"`
New: `auth0/login:"~6.0"`

```
composer update
composer dumpautoload
php artisan cache:clear
php artisan config:clear
rm ./storage/framework/sessions/*
```

For my code, I added the guards and providers into `auth.php` and updated my routes to use the `auth:auth0` middleware instead of just `auth`.

I'm using a custom user repository which is here: [https://gist.github.com/bkilshaw/828db131107d28265781af16468ad2db](https://gist.github.com/bkilshaw/828db131107d28265781af16468ad2db)

### Environment

- **Version of this library used:** 6.1
- **Version of the platform or framework used, if applicable:** Laravel 7.28.4

**Comment by evansims** [comment]
Hey @bkilshaw 👋 Sorry you hit some trouble with this. I've not been able to reproduce this on my end as of yet unfortunately. Usually just wiping out your cookies should address this error, but it sounds like you tried that already, and you covered all the other bases I can think of.

I know this ticket has been around for a bit (sorry about that!) — did you have any luck resolving this yet? If not, could you let me know what PHP version you're on so I can try diagnosing further? Thanks

**Comment by evansims** [comment]
Closing this issue for now, but if you have any additional updates on this or further info to help diagnose this please feel free to comment. Thanks
