### ISSUE TITLE
Type error: Argument 3 passed to Auth0\Login\Auth0Service::__construct() must be an instance of Psr\SimpleCache\CacheInterface or null, instance of Illuminate\Cache\Repository given, called in /var/www/laravel/vendor/auth0/login/src/Auth0/Login/LoginServiceProvider.php on line 68

### ISSUE THREAD

**Issue by rahul7yadav** [auth0/laravel-auth0#203]
I used 
```
"auth0/login": "^6.1"
"laravel/framework": "5.2.*"
Php version 7.1 
```
Can you Please let me know how to fixed this error.

**Comment by evansims** [comment]
Hi @rahul7yadav it appears you're using an incompatible SDK version for that Laravel release. As mentioned in [our README](https://github.com/auth0/laravel-auth0/blob/master/README.md) we no longer maintain support for Laravel 5.2 or PHP 7.1, but you could use the 3.X branch of this SDK if you do not have any upgrade paths.

**Comment by rahul7yadav** [comment]
Hi @evansims , Thanks for fast reply :+1: 
Now i used 
`"auth0/login": "3.2.1"`
and when i run composer install then why this is installed latest version of auth0/login .
```
 - Installing auth0/auth0-php (7.5.0): Downloading (100%)         
  - Installing auth0/login (6.1.0): Downloading (100%)  
```   
Thanks!!

**Comment by evansims** [comment]
I suspect you may need to run a `composer update` to update your lockfile

**Comment by rahul7yadav** [comment]
Now i got the new error 
`Declaration of App\Repositories\CustomUserRepository::getUserByDecodedJWT(array $decodedJwt): Illuminate\Contracts\Auth\Authenticatable must be compatible with Auth0\Login\Contract\Auth0UserRepository::getUserByDecodedJWT($jwt)`

Can you Please share the quickstart for `"auth0/login": "3.2.1"`

Thanks!!

**Comment by evansims** [comment]
As that version has not been supported for quite a long time now I'm afraid we don't have a quickstart available online for that release anymore. I am unsure if that version of the SDK is able to do what you're needing. Are you not able to upgrade to a newer version of Laravel and PHP?
