### ISSUE TITLE
Laravel Octane support

### ISSUE THREAD

**Issue by affektde** [auth0/laravel-auth0#212]
### Describe the problem you'd like to have solved
- Install Laravel Octane (https://github.com/laravel/octane)
- Configure with PHP swoole
- Running Laravel PHP server with `/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=swoole --host=0.0.0.0 --port=80`
- Try to login via Auth0
- Session and cookies not persisted
- Login not possible

### Describe the ideal solution
Laravel Auth0 package provides a solution to work with Laravel Octane.
Changes in `register` and `boot` of Auth?

## Alternatives and current work-arounds
N/A

### Additional information, if any
I think the `register` method in Auth0 ServiceProvider has to be changed in order to work with the boot process of Laravel Octane warmed up instances.

**Comment by evansims** [comment]
Hey, @affektde 👋 Thanks for the request! I've been following Octane's development and it's definitely an exciting project. It's on my radar to add support but it may be a bit before I'm able to dig into this. In the meantime, if anyone wants to get started tackling this, PRs are most welcome!

**Comment by evansims** [comment]
An initial PR addressing this has been merged into the dev branch for the next major. I'm unable to provide a timeline on when that will be getting shipped, but it likely won't be until Q4 this year. I'm going to close this for the meanwhile.

**Comment by ionut-tanasa** [comment]
@evansims any ETA on this? I would LOVE to use Octane and this is keeping us back 😄

**Comment by evansims** [comment]
Hey @ionut-tanasa a beta release of the new major should be available within the next couple weeks with support for Octane (It's live on `main` branch at the moment, though not quite code complete)

**Comment by ionut-tanasa** [comment]
@evansims hiya ! okay. will patiently wait then. thanks for the quick response

**Comment by trconyl** [comment]
i have problem with laravel octane - swoole when trying to login with Auth my nginx server returns 504 gateway time-out

**Comment by affektde** [comment]
> though not quite code complete

I updated to official release 7 right now and switched my Laravel Sail environment to Octane.

**Is there still missing some code to complete Octane support?**

Testing Octane with latest release leads to following error:

```
Auth0 \ SDK \ Exception \ StateException
PHP 8.1.3
Laravel 9.5.1
Missing code
```

It's caused by an emtpy `$code` in `vendor/auth0/auth0-php/src/Auth0.php:307`

```php
$code = $code ?? $this->getRequestParameter('code');
```

`getRequestParameter`-method seems to not work with Laravel Octane.

I see `$_GET` in there. Probably need something different for Octane.

**Comment by tyler-koch-sw** [comment]
> > though not quite code complete
> 
> I updated to official release 7 right now and switched my Laravel Sail environment to Octane.
> 
> **Is there still missing some code to complete Octane support?**
> 
> Testing Octane with latest release leads to following error:
> 
> ```
> Auth0 \ SDK \ Exception \ StateException
> PHP 8.1.3
> Laravel 9.5.1
> Missing code
> ```
> 
> It's caused by an emtpy `$code` in `vendor/auth0/auth0-php/src/Auth0.php:307`
> 
> ```
> $code = $code ?? $this->getRequestParameter('code');
> ```
> 
> `getRequestParameter`-method seems to not work with Laravel Octane.
> 
> I see `$_GET` in there. Probably need something different for Octane.

@evansims has there been any progress on this? Many people are waiting to use Octane alongside Auth0. This seems to be a blocker. `Auth0 \ SDK \ Exception \ StateException  "Missing code" PHP 8.1.8 Laravel 9.21.0`
