### ISSUE TITLE
api_identifier config is not passed to Auth0\SDK\Auth0 config as audience

### ISSUE THREAD

**Issue by iSerter** [auth0/laravel-auth0#213]
### Problem 

Auth0 Laravel package uses the `api_identifier` config key, which is the default JWT audience. 
See https://github.com/auth0/laravel-auth0/blob/master/src/Auth0/Login/Auth0Service.php#L204
However, Auth0 PHP SDK -which is a dependency of this package- is using the `audience` config key to create a login URL. 
So setting `api_identifier` in the config, does not add the audience param to the login URL. 

### Expected behavior?
I'd expect the login URL to include the audience I set in the config file. 

### Reproduction
Fresh install of the package and following the official docs will cause it. 

### Solution 
It's possible to pass the audience as an additional parameter, and it'll work. However, what's the point of the config then? 
I think something like this would make things much easier; 
https://github.com/iSerter/laravel-auth0/commit/011190a2b13e79700c7adeab79bc89545c139198

### Environment

PHP 8 
Laravel 8
auth0/login: 6.4

**Comment by evansims** [comment]
Hey @iSerter! Good catch, thank you! Your solution looks reasonable, I'll be sure to update this in the next major to reflect the same naming as the upstream SDK. If you'd like, would you want to create a PR with that suggestion I can merge your fix? I can do it if you'd rather

**Comment by iSerter** [comment]
Hi @evansims, 
Thank you for checking on the issue and responding. I have created a PR for the commit I had shared as an example in the issue description; 

https://github.com/auth0/laravel-auth0/pull/214

**Comment by evansims** [comment]
Thanks very much for catching this and creating a fix, @iSerter! Really appreciate it. I'll ship this as a new bugfix release this coming week.
