### ISSUE TITLE
upgrade "auth0/auth0-php" package to version "^8.0"

### ISSUE THREAD

**Issue by edambasuren** [auth0/laravel-auth0#229]
### What should be added?

upgrade "auth0/auth0-php" package to version "^8.0"

**Comment by evansims** [comment]
Hey @edambasuren! 👋 A new major of the Laravel plugin will be made available in the future based on Auth0 PHP SDK 8.0. This work has just begun and is slated for Q4 for this year. Watch our repo and keep an eye out for new releases, we'll have a beta release available in the near future.
