### ISSUE TITLE
Composer still installs 7.9.0 with consequent issues.

### ISSUE THREAD

**Issue by sfinktah** [auth0/laravel-auth0#231]
### SDK Version

Other (specify in 'additional context')

### PHP Version

PHP 7.4

### Composer Version

2.x

### What happened?

Gotcha, thanks for letting me know! I'll go over our docs this week and get them updated to ensure we're suggesting the right versions to install for getting started 👍

_Originally posted by @evansims in https://github.com/auth0/laravel-auth0/issues/221#issuecomment-908458758_

Brand new install, `composer update` fixed -- but you might want to check why it's happening in the first place. 

```
  - Upgrading auth0/auth0-php (7.9.0 => 7.9.2)
```

### How can we reproduce this issue?

.

### Additional context

.

**Comment by evansims** [comment]
Thanks, it's an odd one and I'm not quite sure why Composer is doing that for some users. As a workaround I'll just bump it to enforce auth0-php ^7.9.2 of the package next release, although that obviously shouldn't be necessary. I'm confident it will be resolved with the next major of this library slated for Q4, at any rate, as we'll be depending on auth0-php 8.0 at that point.
