### ISSUE TITLE
Fresh Laravel 8 Installation on PHP v8.0 cannot install auth0/login and laravel/passport simultaneously

### ISSUE THREAD

**Issue by la-roberto** [auth0/laravel-auth0#236]
### SDK Version

6.5

### PHP Version

PHP 8.0

### Composer Version

2.x

### What happened?

* When creating a new Laravel project from scratch using PHP v8.0, you currently cannot install both the latest Laravel Passport with auth0.

```
$ composer require auth0/login laravel/passport lcobucci/jwt
Using version ^6.5 for auth0/login
Using version ^10.2 for laravel/passport
Using version ^4.1 for lcobucci/jwt
./composer.json has been updated
Running composer update auth0/login laravel/passport lcobucci/jwt
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - auth0/login 6.5.0 conflicts with lcobucci/jwt 4.1.5.
    - auth0/login 6.5.0 conflicts with lcobucci/jwt 4.1.4.
    - auth0/login 6.5.0 conflicts with lcobucci/jwt 4.1.3.
    - auth0/login 6.5.0 conflicts with lcobucci/jwt 4.1.2.
    - auth0/login 6.5.0 conflicts with lcobucci/jwt 4.1.1.
    - auth0/login 6.5.0 conflicts with lcobucci/jwt 4.1.0.
    - auth0/login 6.5.0 conflicts with lcobucci/jwt 4.2.x-dev.
    - auth0/login 6.5.0 conflicts with lcobucci/jwt 4.1.x-dev.
    - Root composer.json requires auth0/login ^6.5 -> satisfiable by auth0/login[6.5.0].
    - Root composer.json requires lcobucci/jwt ^4.1 -> satisfiable by lcobucci/jwt[4.1.0, ..., 4.2.x-dev].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require auth0/login:*" to figure out if any version is installable, or "composer require auth0/login:^2.1" if you know which you need.
```

* I have tried several ways to installing these packages together, but I always end up getting similar conflicts with the `lcobucci/jwt` library.

* I've tried to install Laravel Passport first and then auth0/login and vice-versa, but no dice either.

* Any chance that these internal dependencies can be resolved? Thank you for your help and please let me know if any further clarification is needed.

### How can we reproduce this issue?

* Create a new Laravel Project, then attempt to add both Laravel Passport and auth0/login right after:
```bash
composer require laravel/passport
composer require auth0/login
```

**Comment by evansims** [comment]
Hey @la-roberto 👋 Thanks for your report. This is a known issue. `laravel/passport` relies on a different major release of the `lcobucci/jwt` dependency, and the two are incompatible at this time. We rely on a fork of the 3.x branch of that JWT dependency to enable PHP 8.0+ support, while Passport is using 4.x. We have a new major of this plugin in development that removes this dependency and will resolve the conflict, which should be seeing a beta release next month if all goes as planned. Apologies for the trouble in the meantime. I don't have a workaround available for this particular situation.

**Comment by la-roberto** [comment]
Thanks for the followup, Evan! Looking forward to that release. Thankful for your work.
