### ISSUE TITLE
Upgrade auth0-PHP SDK to v8

### ISSUE THREAD

**Issue by danielme85** [auth0/laravel-auth0#242]
### What should be added?

Hi, seems like the  auth0-PHP SDK version included in this package is out of date when it comes to supporting the management API. 

The newest SDK seems to automagically fetch the management token (nice), and has a $auth0->management() method. 
I assume there are breaking changes between SDK7->8 for this package.

Is there a quick and dirty workaround?
Thanks!

**Comment by evansims** [comment]
Hi @danielme85 👋  No quick workaround I'm afraid, too many changes from Auth0-PHP SDK v7 to v8 to make it an easy patch. However, a new major release of the Laravel plugin is in development that includes this upgrade. That should be available within a few weeks time. Hang tight a bit longer!

**Comment by danielme85** [comment]
Ok, thats good news, thanks!
