### ISSUE TITLE
Create a logout route

### ISSUE THREAD

**Issue by thijsvdanker** [auth0/laravel-auth0#25]
I need a way to logout my users from auth0 within my Laravel application.

Would it make sense to create a logout route in this package that flushes the session?

**Comment by glena** [comment]
I don't think so.

The session handling is not handled by the package, it just extends laravel's in order to work with auth0.

In this case, you just need to add a route that excecutes `Auth::logout();`

**Comment by thijsvdanker** [comment]
ok, agreed. thanks

**Comment by glena** [comment]
thanks

**Comment by hossam-maurice** [comment]
I am facing an issue with the `Auth::logout()` with Auth0 application created after 1st of September 2017, after logging out it redirects me to the login page which is the Auth0 lock, and before it displays the lock it logs me in again and redirect to the authenticated screen on my site. So I can't logout.

I tried all the solutions in the following link and it didn't work with me
[https://stackoverflow.com/questions/34479994/laravel-5-2-authlogout-is-not-working/34667356#34667356](https://stackoverflow.com/questions/34479994/laravel-5-2-authlogout-is-not-working/34667356#34667356)

I am using Laravel 5.6 and laravel-auth0 v5.1.0
My code is exactly like the following guide: https://auth0.com/docs/quickstart/webapp/laravel/01-login with the custom user handling, except the home page redirects to the Auth0 lock, it isn't a normal page with login button.

Any ideas?

**Comment by joshcanhelp** [comment]
@hossam-maurice - Sorry for the trouble there. 

I walked through the Quickstart (Laravel 5.7 but that shouldn't make any difference) and everything is working for me right out of the box. My tenant was created this year so same situation. A few questions on your comment here:

> after logging out it redirects me to the login page which is the Auth0 lock

The Quickstart uses the [Universal Login page](https://auth0.com/docs/guides/login/universal-vs-embedded), not Lock/embedded. Where are you seeing steps to integrate Lock? I would recommend using the hosted page with an application like this. 

> before it displays the lock it logs me in again and redirect to the authenticated screen on my site

Do you have any kind of `checkSession` on the Lock page? We do that in the WordPress plugin, check for an Auth0 session and, if there is one, log the user in automatically. Like so:

https://github.com/auth0/wp-auth0/blob/master/templates/auth0-sso-handler-lock10.php

**Comment by joshcanhelp** [comment]
@hossam-maurice - Happy to help! So this is resolved?
