### ISSUE TITLE
Multi config support

### ISSUE THREAD

**Issue by holoyan** [auth0/laravel-auth0#253]
### What should be added?

Hey guys, I have multiple client in my auth0 console and depending on condition I want to use one of this clients. 
It would be great if could pass some parameter to specify which config we want to use. for example

```php
// laravel-auth0.php


declare(strict_types=1);

return [
   'defult' => [
      'domain' => env( 'AUTH0_DOMAIN' ),
      'client_id' => env( 'AUTH0_CLIENT_ID' ),
   ],
 
   'admin' => [
      'domain' => env( 'AUTH0_DOMAIN2' ),
      'client_id' => env( 'AUTH0_CLIENT_ID2' ),
   ],

   //....
]

```

and then I could do something like this 

```php

\App::make('auth0', [ 'config'  => 'admin']) // this takes admin configs
\App::make('auth0', [ 'config'  => 'admin2']) // ...

```

Thanks in advance.

**Comment by evansims** [comment]
Hey @holoyan 👋 Thanks for your feature request! Interesting idea! I don't think it's something we'll be able to tackle in time for the next release, but I've created a backlog ticket to investigate adding it down the road
