### ISSUE TITLE
Impossible to configure custom User Repository in 7.0.0-BETA1

### ISSUE THREAD

**Issue by pkivits-litebit** [auth0/laravel-auth0#256]
### SDK Version

Other (specify in 'additional context')

### PHP Version

PHP 8.0

### Composer Version

2.x

### What happened?

Expected:

Custom user repository configured in config/auth.php to be used by Auth0\Laravel\Auth\User\Provider.

Actual:

```
Auth0\Laravel\Auth\User\Provider::__construct(): Argument #1 ($repository) must be of type Auth0\Laravel\Auth\User\Repository, SomeCustomUserRepository given, called in /var/www/html/vendor/auth0/login/src/ServiceProvider.php on line 48
```

### How can we reproduce this issue?

In the config/auth.php setup a custom user repository instead of the one provided by auth0/laravel-auth0.

```
// 👆 Continued from above, in config/auth.php
'providers' => [
    // 📝 Any additional providers you use should stay here, too.
    'auth0' => [
        'driver' => 'auth0',
        'repository' => SomeCustomUserRepository::class
    ],
],
```

### Additional context

Because the $repository parameter in Auth0\Laravel\Auth\User\Provider is expecting a Auth0\Laravel\Auth\User\Repository type, it is impossible to pass any other type then Auth0\Laravel\Auth\User\Repository to Auth0\Laravel\Auth\User\Provider.

Thus making it impossible to configure a custom User Repository.

**Comment by evansims** [comment]
Hi @pkivits-litebit 👋 Thanks for your report. Good catch, we should be expecting an `Auth0\Laravel\Contract\Auth\User` type there, so your custom provider can implement that interface. I'll prepare a PR to adjust that.

**Comment by evansims** [comment]
@pkivits-litebit Merged! If you want to update off `main` to give it a try right away; otherwise a new beta release should be cut next week.

**Comment by JanMisker** [comment]
I am attempting to use a custom repository as well, however even with the change to the contract interface I still run into problems.

The thing is that later on in the flow, for example in the `handleTokenExpiration` function, there are calls to `$user->getAccessTokenExpired()` https://github.com/auth0/laravel-auth0/blob/3edee55f02552a7dc4743752f802cb2b8f80f2ea/src/Auth/Guard.php#L246 
However, that method does not exist on the Illuminate `Authenticatable` contract, although it does exist on `Auth0\Laravel\Contract\Model\User`. So it seems the Repository contract should specify that interface instead?
https://github.com/auth0/laravel-auth0/blob/8b6ffb1ac36abb5c2a4474e393a3f52913856e03/src/Contract/Auth/User/Repository.php#L28

**Comment by evansims** [comment]
Hey @JanMisker 👋 Thanks for your thoughtful feedback! That could be worth considering, let me investigate and get back to you. (I'm on vacation for the next week or so, so apologies in advance if I am delayed in any responses.)

**Comment by evansims** [comment]
Hey there 👋 Revisiting this topic, I've iterated on the user provider API to ease use of custom user models. The PR implementing these changes is https://github.com/auth0/laravel-auth0/pull/264 and will be released as Beta 2 this week for feedback.

**Comment by affektde** [comment]
We are testing the latest Beta 2 release right now. Also with a custom user model.

We can successfully authenticate our users for now and `auth()->user()` is holding our Eloquent User.

Thank you for those new commits @sheggi @evansims <3

**Comment by evansims** [comment]
Delighted to hear it, @affektde 👍 If you see any room for improvement we can iterate on with this side of things before the full release, don't hesitate to let me know
