### ISSUE TITLE
502 Bad Gateway on callback

### ISSUE THREAD

**Issue by nsaumini** [auth0/laravel-auth0#259]
### SDK Version

7.0

### PHP Version

PHP 8.0

### Composer Version

2.x

### What happened?

I followed the instructions in [Laravel 9 Beta guide](https://auth0.com/docs/quickstart/webapp/laravel-beta/) and when I click the login button it redirects to the callback url & throws 502 Bad Gateway error.

I'm using Laravel Valet

![C9A84690-CECB-4722-B6D2-B67C9A561627_1_201_a](https://user-images.githubusercontent.com/12414016/154069285-0363ee17-609b-4cd6-ac21-b41de39cb5dd.jpeg)

### How can we reproduce this issue?

Follow the [Laravel 9 Beta guide](https://auth0.com/docs/quickstart/webapp/laravel-beta/) documentation

**Comment by evansims** [comment]
Hi @nsaumini 👋

- If you could, please run the tutorial code using `php artisan serve --port=3000`, I can't advise on troubleshooting the code running through an nginx proxy.
- Ensure [display_errors](https://www.php.net/manual/en/errorfunc.configuration.php#ini.display-errors) is enabling on your PHP configuration.
- Check your PHP log files for any reported errors.

**Comment by nsaumini** [comment]
@evansims Thanks for the guide. 

https://github.com/laravel/valet/issues/290#issuecomment-398686133 resolved my issue.
