### ISSUE TITLE
Class Auth0\Laravel\Facade\Auth0 located in ./vendor/auth0/login/src/facade/Auth0.php does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by AndyMillne** [auth0/laravel-auth0#262]
### SDK Version

Other (specify in 'additional context')

### PHP Version

PHP 8.1

### Composer Version

2.x

### What happened?

When running:

composer require auth0/login:dev-main

the following error is shown:

Class Auth0\Laravel\Facade\Auth0 located in ./vendor/auth0/login/src/facade/Auth0.php does not comply with psr-4 autoloading standard. Skipping.

### How can we reproduce this issue?

Follow the Readme getting started steps

**Comment by evansims** [comment]
Hi @AndyMillne 👋 Thanks for the heads-up, it appears git didn't update the folder name casing of `Facade` which would affect PSR-4. I've updated it. Can you try again?
