### ISSUE TITLE
all routes with code and state query params fail

### ISSUE THREAD

**Issue by jclyons52** [auth0/laravel-auth0#271]
### SDK Version

6.5

### PHP Version

PHP 8.0

### Composer Version

2.x

### What happened?

vendor/auth0/auth0-php/src/Auth0.php:550 will throw an error on any authenticated route with query parameters of code and state. These are used by other service providers such as stripe with the callback from stripe connect.

### How can we reproduce this issue?

add ?code=foo&state=bar to any authenticated route in a Laravel app using auth0

### Additional context

full stack trace:
vendor/auth0/auth0-php/src/Auth0.php
Auth0\SDK\Auth0
:550
46
Auth0\SDK\Auth0
:489
45
vendor/auth0/login/src/Auth0/Login/Auth0Service.php
Auth0\Login\Auth0Service
:204
44
vendor/auth0/login/src/Auth0/Login/Repository/Auth0UserRepository.php
Auth0\Login\Repository\Auth0UserRepository
:42
43
vendor/auth0/login/src/Auth0/Login/Auth0UserProvider.php
Auth0\Login\Auth0UserProvider
:44
42
vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php
Illuminate\Auth\SessionGuard
:148
41
Illuminate\Auth\SessionGuard
:219
40
vendor/laravel/framework/src/Illuminate/Session/DatabaseSessionHandler.php
Illuminate\Session\DatabaseSessionHandler
:225
39
Illuminate\Session\DatabaseSessionHandler
:212
38
Illuminate\Session\DatabaseSessionHandler
:198
37
vendor/laravel/framework/src/Illuminate/Support/helpers.php
:263
36
vendor/laravel/framework/src/Illuminate/Session/DatabaseSessionHandler.php
Illuminate\Session\DatabaseSessionHandler
:200
35
Illuminate\Session\DatabaseSessionHandler
:137
34
vendor/laravel/framework/src/Illuminate/Session/Store.php
Illuminate\Session\Store
:129
33
vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php
Illuminate\Session\Middleware\StartSession
:236
32
Illuminate\Session\Middleware\StartSession
:130
31
Illuminate\Session\Middleware\StartSession
:64
30
vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
Illuminate\Pipeline\Pipeline
:167
29
vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php
Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse
:37
28
vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
Illuminate\Pipeline\Pipeline
:167
27
vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php
Illuminate\Cookie\Middleware\EncryptCookies
:67
26
vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
Illuminate\Pipeline\Pipeline
:167
25
Illuminate\Pipeline\Pipeline
:103
24
vendor/laravel/framework/src/Illuminate/Routing/Router.php
Illuminate\Routing\Router
:697
23
Illuminate\Routing\Router
:672
22
Illuminate\Routing\Router
:636
21
Illuminate\Routing\Router
:625
20
vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
Illuminate\Foundation\Http\Kernel
:167
19
vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
Illuminate\Pipeline\Pipeline
:128
18
vendor/fruitcake/laravel-cors/src/HandleCors.php
Fruitcake\Cors\HandleCors
:38
17
vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
Illuminate\Pipeline\Pipeline
:167
16
vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php
Illuminate\Http\Middleware\TrustProxies
:39
15
vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
Illuminate\Pipeline\Pipeline
:167
14
vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php
Illuminate\Foundation\Http\Middleware\TransformsRequest
:21
13
vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php
Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull
:31
12
vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
Illuminate\Pipeline\Pipeline
:167
11
vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php
Illuminate\Foundation\Http\Middleware\TransformsRequest
:21
10
vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php
Illuminate\Foundation\Http\Middleware\TrimStrings
:40
9
vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
Illuminate\Pipeline\Pipeline
:167
8
vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php
Illuminate\Foundation\Http\Middleware\ValidatePostSize
:27
7
vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
Illuminate\Pipeline\Pipeline
:167
6
vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php
Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance
:86
5
vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php
Illuminate\Pipeline\Pipeline
:167
4
Illuminate\Pipeline\Pipeline
:103
3
vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php
Illuminate\Foundation\Http\Kernel
:142
2
Illuminate\Foundation\Http\Kernel
:111
1
public/index.php
:52

**Comment by evansims** [comment]
Hi @jclyons52 👋 This is by design for V6, although this behavior was changed in V7 to accommodate situations like you are describing. If code/state params are present in the request, V6 of the SDK will attempt to process them as an Auth0 callback for authentication. Upgrading to V7 enables you to opt-in to this behavior on specific callback routes.
