### ISSUE TITLE
How to use the laravel session storage in v7?

### ISSUE THREAD

**Issue by JanMisker** [auth0/laravel-auth0#273]
### What should be added?

By default the underlying auth0 php sdk will use the CookieStore to store session information. 

I did some digging but can’t figure out how to configure it to use the laravel built in session storage feature. Is this possible or was it stripped in the new v7 release?

**Comment by evansims** [comment]
Hi @JanMisker 👋 This is not currently supported out of the box; I'm looking to add support for that in 7.1.

**Comment by roberttolton** [comment]
@evansims Sorry to bother here too, but any update?

**Comment by evansims** [comment]
Hi @roberttolton, please don't post across multiple old/closed issues as it unnecessarily sends notifications to everyone who contributed to a thread in the past. In the future, please open a new issue. I have responded to your previous ping on the other issue.
