### ISSUE TITLE
Cookie size limit in Cloudflare

### ISSUE THREAD

**Issue by khamazaspyan** [auth0/laravel-auth0#274]
### SDK Version

7.0

### PHP Version

PHP 8.1

### Composer Version

2.x

### What happened?

We updated our application to Laravel 9. After updating auth0/auth0-laravel (7.0) and auth0/auth0-php (8.1.0) SDK is storing too large cookie. But we have cookie size limit in [Cloudflare](https://developers.cloudflare.com/workers/platform/limits/#request-limits) and it's not impossible to increase limit.
Also auth0/auth0-laravel 7.0 doesn't support [SessionStorage](https://github.com/auth0/auth0-PHP/issues/618#issuecomment-1102750552).
Do you have ETA for version 7.1? Or maybe do you know another workaround to solve this issue?
Thanks.

### How can we reproduce this issue?

Just need to run Laravel 9 with auth0-laravel 7.0 SDK with auth0/auth0-laravel (7.0) and auth0/auth0-php (8.1.0) in Cloudflare

**Comment by evansims** [comment]
Hi @khamazaspyan 👋 Thanks. I've answered this in the original thread for now: https://github.com/auth0/auth0-PHP/issues/618
