### ISSUE TITLE
id_token and access_token disappears after authentication

### ISSUE THREAD

**Issue by carnevalle** [auth0/laravel-auth0#28]
Hi!

I am trying to get Auth0 to function with Laravel. 

I have everything setup so I can initiate a login (username-password & facebook) with Lock. When it returns it authenticates and Auth::check() returns true.

If I try to access a route using the route middleware mentioned in the guide (https://auth0.com/docs/quickstart/webapp/laravel) I get "uauthorized user'.

I can see that if I dump the variables in the Auth0Controller on the callback it has both an access_token and an id_token. But after I redirect away from the callback the access_token and id_token are null.

I am a bit clueless on how I can get both user profile, access_token and id_token after the login. I can't seem to find anything in the docs.

I am running Laravel 5.2 on Laravel Homestead 3.0.1

**Comment by carnevalle** [comment]
Ok, by looking in the source code I can see that it is intended default behavior to not persist the id_token or the access_token. 

Perhaps these config options should be added and documented in the laravel-auth0.php config file.

So now I can access the tokens through the session, but the route middleware still reports "Unauthorized user".

It looks for the JWT in the request header. So the auth0.jwt middleware is primarily for API calls and not as stated in the guide for admin areas etc.?

**Comment by glena** [comment]
I assume this is related to the PR you sent right? (thx by the way)

Is there anything else?

**Comment by carnevalle** [comment]
In the documentation (https://auth0.com/docs/quickstart/webapp/laravel) it is not clear when to use route middleware 'auth0.jwt'. 

The use case demonstrated in the docs seems like a use case for the standard laravel middleware 'auth' and the use case for 'auth0.jwt' seems to be for authenticating requests to an API. 

Is my undstanding of this correct? The only way the JWT would be a part of the Request headers would be if I explicit add the to the headers, right?

**Comment by glena** [comment]
yes. for api authentication using JWT, you need to use the `auth0.jwt` middleware in the routes you need to secure. You can use this in routes groups, etc.

In this case, it will get the JWT from the header and you need to add it in all your requests. This is meant for APIs not regular webapp.

If you need to use sessions, you can use the laravel's authentication middleware with the auth0 driver and it will work with normal sessions and cookies (check this seed https://auth0.com/docs/quickstart/webapp/laravel/)
