### ISSUE TITLE
intended url not set

### ISSUE THREAD

**Issue by puggan** [auth0/laravel-auth0#283]
### SDK Version

7.0

### PHP Version

PHP 8.0

### Composer Version

2.x

### What happened?

When returning from the authentication, the user land on the wrong url.

https://github.com/auth0/laravel-auth0/blob/bd6ee079a30f10c1c8dbfb7e470c50f53251e45a/src/Http/Middleware/Stateful/Authenticate.php#L30

Think you supose to use the guest() method, when redirecting an unatuerized user, as that one sets the inteded url.
like: `return redirect()->guest(app()->make('config')->get('auth0.routes.login', 'login'));`

### How can we reproduce this issue?

- add `->middleware('auth0.authenticate')` to a none home route.
- visit that route, 
- login, 
- get anoyed when you end up on homepage.

### Additional context

There is closed issues on similar problems, but the problem is still active:
- #272
- #122

**Comment by puggan** [comment]
Another option is to throw an \Illuminate\Auth\AuthenticationException

**Comment by evansims** [comment]
Hi @puggan, I'm not quite sure if I'm following your request here. The SDK redirects to the login route for authentication and then returns the user to the index route. This is the intentional design. If you're looking to redirect the end user to a different route after authentication, that logic can be handled within your application code by listening for the [AuthenticationSucceeded event](https://github.com/auth0/laravel-auth0/blob/main/src/Event/Stateful/AuthenticationSucceeded.php).

**Comment by evansims** [comment]
👋 That would be a bit redundant and introduce an element of confusion to our API and documentation we'd prefer to avoid. Listening for and responding to the event offers more robust customization for responding to this situation than the suggested change would provide. Is there a reason why the event approach isn't viable in your situation?

**Comment by puggan** [comment]
The flow I'm used to:

1. User is not authenticated, throws a AuthenticationException:
https://github.com/laravel/framework/blob/e742118a851c5751b616ef51841a7b0bf6be8cd4/src/Illuminate/Auth/Middleware/Authenticate.php#L82

2. The Exception is catched, and converted to an redirect with the intended url stored:
* https://github.com/laravel/framework/blob/e742118a851c5751b616ef51841a7b0bf6be8cd4/src/Illuminate/Foundation/Exceptions/Handler.php#L362
* https://github.com/laravel/framework/blob/e742118a851c5751b616ef51841a7b0bf6be8cd4/src/Illuminate/Foundation/Exceptions/Handler.php#L458
* https://github.com/laravel/framework/blob/e742118a851c5751b616ef51841a7b0bf6be8cd4/src/Illuminate/Routing/Redirector.php#L92

3. After successfully logged in, user is redirected back to the intended url:
https://github.com/auth0/laravel-auth0/blob/bd6ee079a30f10c1c8dbfb7e470c50f53251e45a/src/Http/Controller/Stateful/Login.php#L18

----

By using the AuthenticationSucceeded event, I can modify part 3 above? the only part that works as expected today.
If I'm going to listen to an event, so is that the wrong event...

**Comment by evansims** [comment]
Without a better understanding of your application, it's a bit tough to say that this is the best methodology to take, but you shouldn't need to catch any exceptions. You can simply check with the Guard if the user is authenticated already or not (using a number of methods, such as the `user` method) and react accordingly, such as redirecting to a login route. The middleware provided by the SDK handles checking if a user is authenticated or not and redirects accordingly to start an authentication flow, but you can of course build something custom if you need more control.

I'm uncertain if I entirely follow your last statement correctly, but yes, if you listen for the AuthenticationSucceeded event you can control the behavior immediately following the user returning from the authentication flow, including redirecting them to a route of your choice.

I'll close this as it isn't a feature we're wanting to add right now, but feel free to keep the discussion going if you have further questions
