### ISSUE TITLE
Impossible to retrieve or output the custom deny reason (error_description)

### ISSUE THREAD

**Issue by piljac1** [auth0/laravel-auth0#287]
### SDK Version

7.0

### PHP Version

PHP 8.1

### Composer Version

2.x

### What happened?

In the `Callback` controller, there seems to be some undesired (or unexpected) behavior regarding the error description.

See the following code (line 43):

```php
$errorDescription = is_string($errorDescription) ? $error : '';
```

Since the `$error` content is assigned instead of the `$errorDescription`, it is impossible to retrieve a custom reason that was specified when denying access.

### How can we reproduce this issue?

1. Add a listener to the `AuthenticationFailed` event and `dd($event->getException()->getMessage());` within the `handle` method.
2. Deny access (with a custom reason) in an action and link the action to the login flow.
3. Try to login, the access denial is hit as expected, but the error description is not the one that is expected. Instead, `access_denied: access_denied` is output.

**Comment by evansims** [comment]
Hi @piljac1 👋 Thanks for the heads-up! I'm getting a fix drafted right now.
