### ISSUE TITLE
Testability

### ISSUE THREAD

**Issue by marijnvanderhorst** [auth0/laravel-auth0#295]
### SDK Version

7.0

### PHP Version

PHP 8.1

### Composer Version

2.x

### What happened?

Inside my application I'm calling `Auth0::getSdk()->authentication()->clientCredentials()` to retrieve a machine-to-machine token. This is working fine, but I'm running into A LOT of issues as soon as I want to write a single test case where the underlying SDK is used.

Namely, in my tests, I do not actually want to retrieve any valid machine-to-machine token from Auth0 **obviously**. I've spent hours upon hours trying to simply mock the `clientCredentials()` function call, such that it does not actually perform any HTTP requests and simply returns some string instead.

I would have thought that the following would achieve this. However, the response is only mocked after the actual request is already made. Why perform the HTTP request at all if its response is going to be mocked??? 
```PHP
Auth0::getSdk()->authentication()->getHttpClient()->mockResponse(
    new Response(200, [], '{"access_token": "mocked_token"}')
);
```

So then I resorted to just mocking the SDK methods using Mockery. However, you seem to have made this **impossible** by making all classes final. Final classes are perfectly fine IMO, but only if you then rely solely on the interface that the final class implements instead of the final class directly. Why does the return type of [this function](https://github.com/auth0/laravel-auth0/blob/main/src/Auth0.php#L30), for instance, depend directly on the final class instead of `Auth0\SDK\Contract\Auth0Interface`?? Right now it's impossible for me to replace the SDK by a mocked one during my tests.

Thus, the only thing I want is to be able to mock calls to our Auth0 instance when the application is running in test mode. Am I missing something here? Right now, I cannot test any parts of my code base where this Auth0 SDK is being used, which is simply not acceptable to me.

### How can we reproduce this issue?

1. Call the following function somewhere in any Laravel application. (For instance in a controller function invoked by a route).
```PHP
Auth0::getSdk()->authentication()->clientCredentials()
```

2. Write a test case where the above function call is indirectly executed, for instance by executing an HTTP request to the application under test.

3. Observe the SDK tries to perform an HTTP request to retrieve the machine-to-machine token. (completely expected)

4. Try to mock the request such that no calls are made to Auth0 when the application is in test mode.

### Additional context

Laravel's Facade system and its use of the service container with dependency injection is constructed in such a way with testability in mind. That's why all Facades include functions to mock them **by default**. However, the Auth0 facade just seems to ignore all of this and again makes it impossible to do any kind of mocking 😢 . 

For reference, this is how I'm trying to mock the `clientCredentials()` function:

```PHP
$authentication = Mockery::mock(Auth0::getSdk()->authentication())
    ->makePartial()
    ->shouldReceive('clientCredentials')
    ->andReturn(new Response(200, [], '{"access_token": "mocked_token"}'));

$sdk = Mockery::mock(Auth0::getSdk())
    ->makePartial()
    ->shouldReceive('authentication')
    ->andReturn($authentication);

Auth0::shouldReceive('getSdk')->andReturn($sdk);
```

**Comment by evansims** [comment]
Hi @marijnvanderhorst 👋 Thanks for filing your issue. Your request for the SDK to return interface types is of course reasonable and sound. I've created a PR to change this behavior. Would you mind giving it a look and see if this would resolve the issue to your satisfaction? https://github.com/auth0/laravel-auth0/pull/296

As an alternative to resorting to mocking, one can use a mock PSR-18 client library like [php-http/mock-client](https://github.com/php-http/mock-client) to avoid making real HTTP calls. This is in fact how we write the test suite for the underlying SDK itself.

**Comment by marijnvanderhorst** [comment]
> Hi @marijnvanderhorst 👋 Thanks for filing your issue. Your request for the SDK to return interface types is of course reasonable and sound. I've created a PR to change this behavior. Would you mind giving it a look and see if this would resolve the issue to your satisfaction? #296

Thanks for the quick response! I've tested your new branch in my application and now it does indeed allow mocking of the auth0-PHP SDK functions. Thanks. The following does the trick:

```PHP
$authentication = Mockery::mock(AuthenticationInterface::class)
    ->shouldReceive('clientCredentials')
    ->andReturn(new Response(200, [], '{"access_token": "mocked_token"}'));

$sdk = Mockery::mock(Auth0Interface::class)
    ->shouldReceive('authentication')
    ->andReturn($authentication->getMock());

Auth0::setSdk($sdk->getMock());
```

> As an alternative to resorting to mocking, one can use a mock PSR-18 client library like [php-http/mock-client](https://github.com/php-http/mock-client) to avoid making real HTTP calls. This is in fact how we write the test suite for the underlying SDK itself.

Jup, eventually I did indeed resort to mocking the HTTP client that is used by the auth0-PHP SDK using Guzzle's `MockHandler` (i.e. `Config::set('auth0.httpClient', new GuzzleHttp\Client($this->createTestingGuzzleOptions()));`). And while that's indeed a good addition to have in this Laravel SDK's tests, I don't think this should be the required method for testing applications that rely on this Laravel SDK. In my application's tests I would like to assume that the Auth0 SDK is correct and only mock the responses it gives (in this case only the machine-to-machine token), such that I only have to test that my application uses the SDK correctly. The changes in #296 make that possible 👍 .

**Comment by evansims** [comment]
Thanks for reviewing that PR and confirming the changes solved things for you @marijnvanderhorst, I've gone ahead merged that change. I appreciate your thoughtful and detailed feedback on this issue!

There is one other unrelated issue I want to review before cutting the next release, but given it's Friday, you can expect an update with these changes next week 👍
