### ISSUE TITLE
Using Laravel's session store for the PHP SDK's sessionStorage/transientStorage

### ISSUE THREAD

**Issue by nie7321** [auth0/laravel-auth0#299]
### What should be added?

I'm developing for Laravel Octane. One issue I ran into is that the default configuration for the package is to use cookies for the sessionStorage & transientStorage. The PHP SDK's `CookieStore` will call `setcookie()`, which won't work when running on Octane[^1].

[^1]: See [the Laravel Swoole notices](https://github.com/swooletw/laravel-swoole/wiki/Z1.-Notices), specifically point number 6.

I didn't see anything in the Laravel package to offer another driver, so I implemented a `StoreInterface` that uses the the framework's sessions.

However: It was a little difficult to configure this. It didn't look like I could just give the two storage parameters the classpath in `config/auth0.php`; it expected instances. That's a bit of a bummer since caching the config would fail[^2].

[^2]: Running `php artisan config:cache` is what fails if you pass `new MyCoolStorageDriver`. I think I could have made the classes serializable to make it work, but that seems very un-Laravel-y.

I have two suggestions for enhancements of the Laravel package:

1. When a parameter in `config/auth0.php` is expected to be an object, allow it to be specified as a classpath and have the service container resolve it.
2. Add a `StoreInterface` implementation that uses the framework's session driver.

**Comment by evansims** [comment]
Hey @nie7321! 👋 Thanks for raising this!

Adding support for Laravel's session store is definitely on my radar as a next feature addition. I was unaware of the Octane limitation on `setcookies()` and I didn't have any issues in my tests with Octane using it, but it's good to know and further underscores the need for that storage support feature. I'm on it!

**Comment by nie7321** [comment]
> (particularly since I didn't have any issues in my tests with Octane using it)

It was failing specifically because [this script](https://github.com/laravel/vapor-core/blob/2.0/stubs/octaneRuntime.php) does a couple log messages by writing output when it starts Octane up.

The easiest way I found to simulate that was adding an event listener to `WorkerStarting` in the `config/octane.php` that just echos something. It prints to the console, but it seems to count as output for the purposes of breaking `setcookie()`.

**Comment by roberttolton** [comment]
For anyone that's interested, I have a fork that uses Redis for the session storage:

https://github.com/roberttolton/laravel-auth0

You'll need to require `symfony/cache:^5.4` (for Laravel 9.x) and then set `'useRedisForSessionStorage' => true` in your `auth0.php` config file (and of course have a working Redis connection).
