### ISSUE TITLE
Tag 2.2.2 breaks on Laravel 5.1

### ISSUE THREAD

**Issue by thijsvdanker** [auth0/laravel-auth0#30]
The recently tagged 2.2.2 release is not based on the 2.x.x-dev branch but on master and breaks on Laravel 5.1 applications.

**Comment by glena** [comment]
deleted, I will republish it. Sorry

**Comment by glena** [comment]
You might want to flush the composer cache or force the tag to 2.2.1 for the time being. It is already updated on packagist tho (https://packagist.org/packages/auth0/login)
