### ISSUE TITLE
Session Error: Invalid text representation

### ISSUE THREAD

**Issue by bkilshaw** [auth0/laravel-auth0#301]
### SDK Version

7.0

### PHP Version

PHP 8.1

### Composer Version

2.x

### What happened?

Laravel's default session table sets the `user_id` column to INT4 but after following the Auth0 Laravel setup guide it attempts to set it to a string which throws the error.

```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "auth0|72398a0fa2a6f17f7a3" 
```

### How can we reproduce this issue?

Follow the https://auth0.com/docs/quickstart/webapp/laravel/ guide and set your session driver to database

```
SESSION_DRIVER=database
```

**Comment by evansims** [comment]
Hi, @bkilshaw 👋 Thanks for raising this issue.

Our Quickstart wasn't designed to demonstrate more complex configurations like this, and the SDK is designed to work well out-of-the-box with Laravel's default configurations, but there simply isn't a one-size-fits-all approach to these sorts of things. In your case, a custom user provider could easily be used to fit your needs here.

As Auth0's unique identifier is always a string, we'd need to figure out an alternative schema storage solution, or, more easily, create a CustomUserProvider for the SDK that adapts that identifier into an integer. One solution that might work is to create a CRC32 checksum of the ID, which would result an integer that should work for your that use.

```php
<?php

declare(strict_types=1);

namespace App\Auth;

class CustomUserRepository implements \Auth0\Laravel\Contract\Auth\User\Repository
{
    public function fromSession(
        array $user
    ): ?\Illuminate\Contracts\Auth\Authenticatable {
        return new \App\Models\User([
            'id' => crc32($user['sub'] ?? $user['user_id'] ?? 0),
            'name' => $user['name'],
            'email' => $user['email'],
        ]);
    }

    public function fromAccessToken(
        array $user
    ): ?\Illuminate\Contracts\Auth\Authenticatable {
        // Not relevant for stateful sessions
        return null;
    }
}
```

This is, of course, just a rough example off the top of my head, and you'd need to validate that this is the right approach for your application's needs. More information on custom user providers can be found here: https://github.com/auth0/laravel-auth0/pull/264
