### ISSUE TITLE
ERROR: Auth0\SDK\Utility\TransientStoreHandler

### ISSUE THREAD

**Issue by fabien-lopes** [auth0/laravel-auth0#325]
### SDK Version

7.2

### PHP Version

PHP 8.1

### Composer Version

2.x

### What happened?

When I call an API route under the 'middleware' => 'auth0.authorize', I get the following error on the new package 7.2.2 

`[2022-10-20 07:40:21] local.ERROR: Auth0\SDK\Utility\TransientStoreHandler::__construct(): Argument #1 ($store) must be of type Auth0\SDK\Contract\StoreInterface, null given, called in /Users/fabienlopes/code/onboarding-back/vendor/auth0/auth0-php/src/Auth0.php on line 607 {"exception":"[object] (TypeError(code: 0): Auth0\\SDK\\Utility\\TransientStoreHandler::__construct(): Argument #1 ($store) must be of type Auth0\\SDK\\Contract\\StoreInterface, null given, called in /Users/fabienlopes/code/onboarding-back/vendor/auth0/auth0-php/src/Auth0.php on line 607 at /Users/fabienlopes/code/onboarding-back/vendor/auth0/auth0-php/src/Utility/TransientStoreHandler.php:24)
[stacktrace]
#0 /Users/fabienlopes/code/onboarding-back/vendor/auth0/auth0-php/src/Auth0.php(607): Auth0\\SDK\\Utility\\TransientStoreHandler->__construct(NULL)
#1 /Users/fabienlopes/code/onboarding-back/vendor/auth0/auth0-php/src/Auth0.php(198): Auth0\\SDK\\Auth0->getTransientStore()
#2 /Users/fabienlopes/code/onboarding-back/vendor/auth0/login/src/Auth/Guard.php(175): Auth0\\SDK\\Auth0->decode('eyJhbGciOiJSUzI...', NULL, NULL, NULL, NULL, NULL, NULL, 2)
#3 /Users/fabienlopes/code/onboarding-back/vendor/auth0/login/src/Auth/Guard.php(72): Auth0\\Laravel\\Auth\\Guard->getUserFromToken()
#4 /Users/fabienlopes/code/onboarding-back/vendor/auth0/login/src/Http/Middleware/Stateless/Authorize.php(30): Auth0\\Laravel\\Auth\\Guard->user()
#5 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Auth0\\Laravel\\Http\\Middleware\\Stateless\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#6 /Users/fabienlopes/code/onboarding-back/vendor/tomlerendu/laravel-convert-case-middleware/src/ConvertRequestToSnakeCase.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#7 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): TomLerendu\\LaravelConvertCaseMiddleware\\ConvertRequestToSnakeCase->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#8 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(102): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest(Object(Illuminate\\Http\\Request), Object(Closure), Array)
#12 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(54): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter(Object(Illuminate\\Http\\Request), Object(Closure), 'api', Object(Closure))
#13 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#14 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#16 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#17 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#18 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#19 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#20 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/fabienlopes/code/onboarding-back/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/fabienlopes/code/onboarding-back/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Clockwork\\Support\\Laravel\\ClockworkMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#43 /Users/fabienlopes/code/onboarding-back/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#44 /Users/fabienlopes/code/onboarding-back/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#45 /Users/fabienlopes/.composer/vendor/laravel/valet/server.php(234): require('/Users/fabienlo...')
#46 {main}
"} 
`

### How can we reproduce this issue?

Call an API route under the 'middleware' => 'auth0.authorize'

**Comment by evansims** [comment]
Hi @fabien-lopes 👋 Thanks for your report!

Could you check and see if auth0/auth0-PHP 8.3.4 is installed in your project as a transient dependency? "composer show -i" should give you a listing with it

**Comment by evansims** [comment]
Thanks! Looks good. Next thing that comes to mind: could you share your app's config/auth0.php file's contents, redacting any sensitive content you may have added?

**Comment by fabien-lopes** [comment]
@evansims 

Please find below the content of the file.
It's the original one, I changed nothing

`<?php

declare(strict_types=1);

/**
 * Please review available configuration options here:
 * https://github.com/auth0/auth0-PHP#configuration-options.
 */

use Auth0\Laravel\Configuration;
use Auth0\SDK\Configuration\SdkConfiguration;

return [
    // Should be assigned either 'api', 'management', or 'webapp' to indicate your application's use case for the SDK.
    // Determines what configuration options will be required.
    'strategy' => env('AUTH0_STRATEGY', SdkConfiguration::STRATEGY_REGULAR),

    // Auth0 domain for your tenant, found in your Auth0 Application settings.
    'domain' => env('AUTH0_DOMAIN'),

    // If you have configured Auth0 to use a custom domain, configure it here.
    'customDomain' => env('AUTH0_CUSTOM_DOMAIN'),

    // Client ID, found in the Auth0 Application settings.
    'clientId' => env('AUTH0_CLIENT_ID'),

    // Authentication callback URI, as defined in your Auth0 Application settings.
    'redirectUri' => env('AUTH0_REDIRECT_URI', env('APP_URL') . '/callback'),

    // Client Secret, found in the Auth0 Application settings.
    'clientSecret' => env('AUTH0_CLIENT_SECRET'),

    // One or more API identifiers, found in your Auth0 API settings. The SDK uses the first value for building links. If provided, at least one of these values must match the 'aud' claim to validate an ID Token successfully.
    'audience' => Configuration::stringToArrayOrNull(env('AUTH0_AUDIENCE')),

    // One or more scopes to request for Tokens. See https://auth0.com/docs/scopes
    'scope' => Configuration::stringToArray(env('AUTH0_SCOPE')),

    // One or more Organization IDs, found in your Auth0 Organization settings. The SDK uses the first value for building links. If provided, at least one of these values must match the 'org_id' claim to validate an ID Token successfully.
    'organization' => Configuration::stringToArrayOrNull(env('AUTH0_ORGANIZATION')),

    // The secret used to derive an encryption key for the user identity in a session cookie and to sign the transient cookies used by the login callback.
    'cookieSecret' => env('AUTH0_COOKIE_SECRET', env('APP_KEY')),

    // How long, in seconds, before cookies expire. If set to 0 the cookie will expire at the end of the session (when the browser closes).
    'cookieExpires' => env('COOKIE_EXPIRES', 0),

    // Cookie domain, for example 'www.example.com', for use with PHP sessions and SDK cookies. Defaults to value of HTTP_HOST server environment information.
    // Note: To make cookies visible on all subdomains then the domain must be prefixed with a dot like '.example.com'.
    'cookieDomain' => env('AUTH0_COOKIE_DOMAIN'),

    // Specifies path on the domain where the cookies will work. Defaults to '/'. Use a single slash ('/') for all paths on the domain.
    'cookiePath' => env('AUTH0_COOKIE_PATH', '/'),

    // Defaults to false. Specifies whether cookies should ONLY be sent over secure connections.
    'cookieSecure' => Configuration::stringToBoolOrNull(env('AUTH0_COOKIE_SECURE'), false),

    // Named routes within your Laravel application that the SDK may call during stateful requests for redirections.
    'routes' => [
        'home'  => env('AUTH0_ROUTE_HOME', '/'),
        'login' => env('AUTH0_ROUTE_LOGIN', 'login'),
    ],
];
`

**Comment by evansims** [comment]
Hey again @fabien-lopes 👋 Found the issue! Going to require a bug fix release in the upstream `auth0-php` library this Laravel SDK is built on top of. I'll let you know once that's ready for you to update to and confirm it's fixed.

**Comment by lioneaglesolutions** [comment]
@evansims any updates on this being merged? Currently blocking a new install.

**Comment by evansims** [comment]
Hi @lioneaglesolutions 👋 The fix PR (linked above) is currently pending review by our team as part of our QA process, but it's after hours for most of us at the moment. I anticipate to be able to merge and cut a release early tomorrow, though. I'll update this thread once it's released. Thanks for your patience!

**Comment by evansims** [comment]
Hi @fabien-lopes and @lioneaglesolutions 👋 I've released 8.3.5 of the transient `auth0-php` dependency, which should resolve this. Can you run a `composer update` on your projects and see if this resolves things for you? 🤞

**Comment by fabien-lopes** [comment]
Hi @evansims! Thanks for your help! I no more the problem but I have another one :(
I'm creating another ticket to check if you can help me again on this issue.
Many thanks for your help
