### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by fabien-lopes** [auth0/laravel-auth0#326]
### SDK Version

7.2

### PHP Version

PHP 8.1

### Composer Version

2.x

### What happened?

Hello @evansims!

When I send an API protected call from our React App, I have an **"500 Internal Server Error"**.
It only happens when I use the "CustomUserRepository.php" file and I don't understand why.

Many thanks for your precious help again

### How can we reproduce this issue?

Please find bellow the code used : 

- routes/api.php
`/*
|--------------------------------------------------------------------------
| Front API Routes
|--------------------------------------------------------------------------
*/

Route::middleware(['api'])->group(function () {

    // User authenticated Routes
    Route::group(['middleware' => 'auth0.authorize'], function() {

        // Customers
        Route::post('/customers', [CustomerController::class, 'store']);
    });
});`

- app/Auth/CustomUserRepository.php
`class CustomUserRepository implements Repository
{
    public function fromSession(array $user): ?Authenticatable {
        return null;
    }

    public function fromAccessToken(array $user): ?Authenticatable {
        // Similar to above. Used for stateless application types.

        Log::debug('fromAccessToken');

        return new User([
            'id' => 'just_a_random_example|',
            'name' => 'name',
            'email' => 'email'
        ]);
    }
}`

**Comment by DispatchCode** [comment]
Hello Fabien,

probably we facing the same problem few days ago (and I have the same one today in another project). I suppose you updated the auth0 config file (publishing the new vendor file), so I move forward.

We solved the problem by adding this line in our backend:

 `\Illuminate\Session\Middleware\StartSession::class,` 

in the `protected $middleware` array (`app\Http\kernel.php` file).

I hope this can help. :)

Marco

**Comment by fabien-lopes** [comment]
Hello @DispatchCode,

Thanks for your message!
I tried your solution but without success :(

Many thanks for your help

**Comment by evansims** [comment]
Hi @fabien-lopes :wave:

- GitHub appears to have corrupted your formatting on those code snippets
- Can you include any `use` statements you have at the top of your `CustomUserRepository`, that would be helpful in troubleshooting things
- Do your Laravel logs include any hints? Usually at `storage/logs/laravel.log`

**Comment by evansims** [comment]
Closing for now as the thread has gone quiet, but let me know if this continues to be a problem for you.
