### ISSUE TITLE
Typo in vendor:publish (README)

### ISSUE THREAD

**Issue by joshelboy** [auth0/laravel-auth0#334]
### SDK Version

Other (specify in 'additional context')

### PHP Version

PHP 8.1

### Composer Version

2.x

### What happened?

I just created a new Laravel Project and followed the [guide ](https://auth0.com/blog/build-and-secure-laravel-api/#Secure-your-Laravel-API)on your website.
At some point the guide didnt work for me, so i tried to install auth0/login via

```php
composer require auth0/login
# and after that with
php artisan vendor:publish --tag auto0-config
```

The "php artisan vendor [...]"-Part is where my problem occured.
It returned the following line in my Terminal:
```bash
 INFO  No publishable resources for tag [auto0-config]
```

But when I tried the line from your [docs](https://auth0.com/docs/quickstart/backend/laravel/interactive), which fixed the typo && it has an extra "**=**" between tag and auth0-config, it worked for me!
```bash
php artisan vendor:publish --tag=auth0-config
INFO  Publishing [auth0-config] assets.
```

I thought some one should have a look at it.
I think fixing the typo (auto0-config => auth0-config) should be it. The "=" shouldn't be required.
...I am really new to php, laravel and auth0 lol.

### How can we reproduce this issue?

1.    create a fresh laravel project, install dependecies etc...
2.    Install auth0-laravel plugin
       ```bash
          composer require auth0/login
       ```
3.    This is the error install command:
       ```bash
          php artisan vendor:publish --tag auto0-config
       ```
4.    Try my suggestion with the fixed typo -> --tag=auth0-config

### Additional context

SDK 7.3, Win10 - 64 Bit + WSL, PHP8.1.2, Composer 2.2.1, Laravel 9

**Comment by evansims** [comment]
Thanks very much for the heads up on that, @joshelboy! I've got a fix prepared and will merge shortly 👍
