### ISSUE TITLE
Can no longer retrieve user data after updating from 7.1 to 7.4, session store not set error

### ISSUE THREAD

**Issue by Bastien-Bourgon** [auth0/laravel-auth0#342]
### SDK Version

7.2

### PHP Version

PHP 8.0

### Composer Version

2.x

### What happened?

Been using this laravel SDK for a web application for a bit, things were running fine, but yesterday i got around to update the SDK to 7.4 (previously was on 7.1), went ahead and re-generated the config file, and tried to log in, and now `$user = auth()->guard('auth0')->user();` or `Auth::user()` both return me a `Session store not set on request` error, is there a new configuration option to add or modify that i missed/skipped? Or do i need another method to gather user info now?

config/auth.php is set according to the quickstart guide, same for any environment variables, i double checked to make sure i hadn't missed any changes to the guide too. So i'm not sure what's causing this.

If this isn't an issue and just me being an idiot and forgetting something, my apologies.

### How can we reproduce this issue?

Install Laravel and the SDK at the latest version
Follow the quickstart guide
Attempt to use `Auth::user()` or `$user = auth()->guard('auth0')->user();` to get user data after login.

**Comment by evansims** [comment]
Hey @Bastien-Bourgon 👋 Sorry you're hitting challenges on this! Happy to help get things sorted. To kick off our troubleshooting, would you mind sharing:

1. Your `config/auth0.php` file contents?
2. Relevant parts of your `config/auth.php` file?
3. Your dependency manifest by running `composer show`?

Thanks!

**Comment by Bastien-Bourgon** [comment]
i found a workaround from reading another issue of adding `\Illuminate\Session\Middleware\StartSession::class` to the middleware array inside app/Http/Kernel.php, no idea if this is the "intended" fix, but at least it solved the problem. If this doesn't seem like how to fix it then i'm fine with providing the requested contents.
