### ISSUE TITLE
Issue running unit tests after upgrade to 7.4 - "RuntimeException: Session store not set on request."

### ISSUE THREAD

**Issue by DimeZilla** [auth0/laravel-auth0#344]
### SDK Version

7.2

### PHP Version

PHP 8.2

### Composer Version

2.x

### What happened?

Hi all! We are upgrading to from auth0/laravel-auth0 from 6.5 to 7.4 so that we can upgrade laravel from 8 to 9 before laravel 8 reaches end of life. Since 7.4 kinda forces us into using the auth0 provided login guard and the auht0 provided LaravelSession, we discovered an issue when running our unit tests:

Basically, anywhere in our application where we run `\Illuminate\Support\Facades\Auth::check()` to check if there is a logged in user, we get errors that look like the following:

```
1) Tests\Unit\App\Plugins\ActivityMonitor\MonitorTest::testLoggingActivty
RuntimeException: Session store not set on request.

/var/www/vendor/laravel/framework/src/Illuminate/Http/Request.php:515
/var/www/vendor/auth0/login/src/Store/LaravelSession.php:118
/var/www/vendor/auth0/login/src/Store/LaravelSession.php:98
/var/www/vendor/auth0/login/src/Store/LaravelSession.php:53
/var/www/vendor/auth0/auth0-php/src/Auth0.php:671
/var/www/vendor/auth0/auth0-php/src/Auth0.php:413
/var/www/vendor/auth0/login/src/Auth/Guard.php:228
/var/www/vendor/auth0/login/src/Auth/Guard.php:80
/var/www/vendor/auth0/login/src/Auth/Guard.php:52
/var/www/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:340
/var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/var/www/app/Plugins/Module/Module.php:23
/var/www/tests/Unit/App/Plugins/Module/ModuleTest.php:54
/var/www/tests/Unit/App/Plugins/Module/ModuleTest.php:23
/var/www/vendor/phpunit/phpunit/phpunit:98
```

The line `/var/www/app/Plugins/Module/Module.php:23` is just a call to `Auth::check()`:
```
        if (Auth::check()) {
            $this->user = Auth::user();
        }
```

When tracing this all the way down, I see the following method in `vendor/auth0/login/src/Store/LaravelSession.php`:

```
    private function getStore(): \Illuminate\Session\Store
    {
        $request = request();

        // @phpstan-ignore-next-line
        if ($request instanceof \Illuminate\Http\Request) {
            return $request->session();
        }

        // @phpstan-ignore-next-line
        throw new Exception('A cache must be configured.');
    }
```

Here it's clear that the LaravelSession is trying to piggy back off of the session from the request object. However, at the composer runtime (or any other cli runtime like tinker), there won't necessarily be a request object with the session defined.

Our workaround is to add `request()->hasSession()` before anywhere we might check `Auth::check()`. For Example:
```
if (request()->hasSession() && Auth::check()) {
    // now do the thing
}
```

I woudl recommend getting the session from `app('session.store')` instead of rom `request()->session()` in `Auth0\Laravel\Store/LaravelSession.php::getStore()`

### How can we reproduce this issue?

1. Create a unit test in laravel.
2. In the test run `\Illuminate\Support\Facade\Auth::check()`
3. Run the test and see it fail

### Additional context

none

**Comment by evansims** [comment]
Hey @DimeZilla 👋 Thanks for raising this! Let me look into this a little and I'll get back to you. (Will likely won't have bandwidth until next week, my sincere apologies - will get to you ASAP.)

**Comment by DimeZilla** [comment]
@evansims - Hi, I just wanted to check in so see if you've been able to look into this at all. It's kind of a disruptive workaround for us to check the request object before running Auth::check() so before we over commit to coding that into everywhere we run Auth::check)( throughout our application, I just wanted to see if a fix is close to getting implemented. Thank you so much for your time on this!

**Comment by uandco** [comment]
I'm also impacted by this bug after upgrading a project to PHP 8.1, Laravel 9 and the latest auth0 SDK.

I'm using Sentry and my exception handler is using `auth()->user()` to enrich the scope if a session is active.
Even when removing this, it fails later as this is a Laravel Nova app, and NovaServiceProvider calls this:

```
    public static function provideToScript(array $variables)

    {

        if (empty(static::$jsonVariables)) {

            static::$jsonVariables = [

                'debounce' => static::$debounce * 1000,

                'base' => static::path(),

                'userId' => Auth::id() ?? null,

            ];

        }
        [...]
```

**Comment by DimeZilla** [comment]
For others watching this file, as a work around, we're looking into implementing our own `Auth0\Laravel\Store\LaravelSession` class. The only method we are overwriting is `getStore` since that's the method causing issues.

in `config\auth0.php` we added the following:
```
   'sessionStorage' => new \App\Plugins\Auth0\Store\LaravelSession(),
```

and here is the relevant parts of our class
```
<?php

namespace App\Plugins\Auth0\Store;

use Auth0\SDK\Contract\StoreInterface;
use Illuminate\Support\Facades\Session;
use Exception;

/**
 * Class LaravelSession
 * Bridges the Auth0-PHP SDK StoreInterface with the Laravel Session Store API.
 */
final class LaravelSession implements StoreInterface
{
    ...
    /**
     *  {@inheritdoc}
     */
    private function getStore(): \Illuminate\Session\Store
    {
        return Session::driver();
    }
    ...
}
```

* the code truncated by `...` in the code block above is exactly the same as the original LaravelSession class.

**Comment by diamondobama** [comment]
> 

Still getting `Session store not set on request.` after adding a custom session store that returns Laravel session driver in the `getStore()` method, as you suggested.

I downgraded to v7.0 for now, and will wait for a fix or a potential workaround that works.

**Comment by diamondobama** [comment]
> 

Still getting `Session store not set on request.` after adding a custom session store that returns Laravel session driver in the `getStore()` method, as you suggested.

I downgraded to v7.0 for now, and will wait for a fix or a potential workaround that works.

**Comment by evansims** [comment]
👋 Just to update you all, I'm currently digging into this, it's turned out to be a bit of a tricky one. I think I have a solution in mind. Will update you when I have something to try out.

**Comment by ArcadeCityMayor** [comment]
I am receiving this error in my Pest tests when trying to access `auth()->id()` inside Livewire components. 

I'm using `$this->actingAsAuth0User();` which successfully gives auth()->id() in e.g. the following test:

```
it('can access auth()->user() while acting as auth0 user', function () {
    $this->actingAsAuth0User();
    $authuser = auth()->id();

    expect($authuser)->not()->toBeNull();
    expect($authuser)->toEqual('some-auth0-user-id');
});
```

...but that same setup throws the "Session store not set on request" when I try to access auth()->id() inside a method called via Livewire::test().

**Comment by DimeZilla** [comment]
Just circling back to say that we rolled out the [suggestion above](https://github.com/auth0/laravel-auth0/issues/344#issuecomment-1397916484) to our production environment and everything is working smoothly. I would highly recommend it for anyone watching.

**Comment by diamondobama** [comment]
> Just circling back to say that we rolled out the [suggestion above](https://github.com/auth0/laravel-auth0/issues/344#issuecomment-1397916484) to our production environment and everything is working smoothly. I would highly recommend it for anyone watching.

That's good to know. Do you mind sharing your full code changes that make this work in a gist?

**Comment by evansims** [comment]
Hi everyone 👋 Just a heads up, we're wrapping up 7.5 for release next week which addresses this bug, as well as a few other fixes and additions. Thanks for your patience while we looked into it.
