### ISSUE TITLE
Auth0 and Spatie/laravel-permissions conflict

### ISSUE THREAD

**Issue by williamarmilleiCW** [auth0/laravel-auth0#350]
### SDK Version

7.2

### PHP Version

PHP 8.2

### Composer Version

2.x

### What happened?

Hi,

I have been trying to integrate the latest version of Auth0 with spatie/laravel-permission ‘and Spatie\Activitylog’ in my Laravel 9 application; it was working fine with Laravel 8, but the latest Auth0 version changes drastically auth.php file, changing the guards used by Spatie plugins. I believe this is causing quite a few conflicts. I might be wrong with my diagnoses, probably the reasons could be different, but the following is the error which appears when trying to login into my application:

On “Spatie/permissions”:
Spatie\Permission\PermissionRegistrar::Spatie\Permission{closure}(): Argument #1 ($user) must be of type Illuminate\Contracts\Auth\Access\Authorizable, Auth0\Laravel\Model\Stateful\User given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php on line 553

On “Spatie\Activitylog”:
Spatie\Activitylog\CauserResolver::getDefaultCauser(): Return value must be of type ?Illuminate\Database\Eloquent\Model, Auth0\Laravel\Model\Stateful\User returned

As you see above in each instance Spatie expects a type of Model or Function instead an Model\Stateful\User is returned by Auth0, so, triggering the error.

Could you please help me to understand how to solve the issue?
Thanks,
William

### How can we reproduce this issue?

Basically installing Spatie/laravel-persmissions
[https://spatie.be/docs/laravel-permission/v5/installation-laravel](https://spatie.be/docs/laravel-permission/v5/installation-laravel)
and Auth0 latest version. Create a permission/role and assign it to your user, then include it in the code in the following way.
Create a code to authorize access to a certain area like the below:
    @if(auth()->user()->can('manage-organisations'))
        @include('partials.nav-item', ['route' => route('organisations', [], false), 'title' => __('Organisations')])
    @elseif(auth()->user()->can('access-organisations'))
        @include('partials.nav-item', ['route' => route('organisations.show', ['id' => auth()->user()->organisation_id], false), 'title' => __('Organisations')])
    @endif

and an error suppose to be triggered.
Thanks

### Additional context

I thing that should be enough

**Comment by evansims** [comment]
Hi @williamarmilleiCW 👋 Thanks for your question.

I'm not familiar with either of those packages, so I can't answer this without looking into their code further. Based on the error messaging you provided, it appears that these packages have very specific class types they're expecting for the user models provided to them.

This might be something that can be solved with a CustomUserProvider and custom user model, which we show here: https://github.com/auth0/laravel-auth0/blob/ You might start there and see if that provides a solution for you.

I'll mark this as a feature request for the moment, until I'm able to look into this deeper.

**Comment by evansims** [comment]
Thanks for spotting that, @fredsal! I had entirely forgotten about that issue coming up in the past. A reminder to take my own medicine when I suggest searching past issues first, haha.

@williamarmilleiCW please let me know if the links @fredsal provided help you out.

**Comment by williamarmilleiCW** [comment]
Thanks all, I had noticed #187 one, but it didn't work as there were some steps missing. At the end I have worked out a similar solution, which includes the most of the development of the two posts shared by @fredsal (187 and 264).

Basically when  you login with Auth0 the object returned is totally different from User Model also I need to retrieve all User information from the database and I can do that only retrieving the User Model. In order to do that I have done the following in CostumerUserRepository.php

![image](https://user-images.githubusercontent.com/121885095/223068933-3b23e4c7-268c-40c9-9d75-1971d1c5d24b.png)

Basically I have used the only thing in common between the two Objects (Model and Auth0) which is the email to retrieve the User Model, and I have returned it. 

But if you inspect the Model User returned it is slightly different from the one returned because processed by permission laravel plugin, the attribute permissionClass is missing. In order to populate that attribute I have added the following:

![image](https://user-images.githubusercontent.com/121885095/223069930-c6def857-c04a-41c7-8f0a-a10c7afad932.png)

I hope this might help those who wants to have latest Auth0 and Spatie permissions in their Laravel application. But definitely it is better if Auth0 and Spatie permission may solve this conflict. I have alerted them.

**Comment by fredsal** [comment]
If you already add `hasRole`, why do you add `hasPermsissions`?
[Traits/HasRoles.php#L13-L15](https://github.com/spatie/laravel-permission/blob/490fa00b0c8286659a534d822f7e74c684c86d27/src/Traits/HasRoles.php#L13-L15)

**Comment by williamarmilleiCW** [comment]
If you dd($user) when you have Spatie installed you may notice that it has permissionClass attribute with a list of permissions, unfortunately they disappear when you add the above development in order to have Auth0.  I just wanted to do it as identical as the original $user object with Spatie integration, that's it.

**Comment by elopez1987** [comment]
Good morning everyone, I am following these steps in version 10 of Laravel but I cannot overcome the error, has anyone already tried in the new version to see if there are any changes, thanks to everyone.
<img width="1101" alt="image" src="https://github.com/user-attachments/assets/3397553f-8e73-4745-9df4-606658dc3804">
