### ISSUE TITLE
Web & Mobile Logins Simultaneously 

### ISSUE THREAD

**Issue by seivad** [auth0/laravel-auth0#351]
### SDK Version

7.2

### PHP Version

PHP 8.1

### Composer Version

2.x

### What happened?

I cannot for the life of me figure out how to allow users / endpoints to support both Web authentication using the Custom User Repository I have setup as well as an endpoint for mobile app to receive an api token. 

I've gone through every doc page you have at Auth0 and you never describe away using the Laravel package to support both web and api at the same time from what I can see. I have to change the ```AUTH0_STRATEGY``` from webapp to api.

### How can we reproduce this issue?

Instructions are unclear on supporting both web and api at the same time.

### Additional context

Ideally my web users still use a /login endpoint and get redirected the universal login, then callback occurs which sets the users details into my laravel users table & also marks their login in a user_logins table. 

Then from the mobile app, they login using the React Native view, it still hits the same callback in Laravel but sends over the access token (bearer) to hit /api/v1 endpoints. I'm really lost as to how this can work, if at all and any help would be greatly appreciated! Is there something I am missing that the ``` public function fromAccessToken()``` function in the custom repository should do or a way to get the bearer token and respond back with a json payload?

**Comment by evansims** [comment]
Hi @seivad 👋 At present we do not support using the SDK simultaneously in both stateful and stateless operations. We do plan on supporting this in our roadmap, but it requires some significant changes in the upstream PHP SDK to do. I'm afraid I don't have an ETA I can offer on those changes at the moment.

I am hopeful we can have this implemented in the upstream SDK by the next minor or two, but we still need to do more research toward an implementation approach that doesn't result in breaking changes.

There have been some ideas on [workarounds](https://github.com/auth0/laravel-auth0/issues/336) shared in the past, namely around hooking into the events thrown by the HTTP controllers and manipulating the SdkConfiguration state dynamically to adjust, but I know that isn't the most elegant solution.
