### ISSUE TITLE
Legacy behavior uses `$token` instead of `$session` for `login` method

### ISSUE THREAD

**Issue by LucWollants** [auth0/laravel-auth0#363]
### Laravel Version

Laravel 10.x

### SDK Version

SDK 7.5

### PHP Version

PHP 8.3

### What happened?

I expect that `$session` would be used [here](https://github.com/auth0/laravel-auth0/blob/main/src/Auth/Guard.php#L584) instead of `$token`

### How can we reproduce this issue?

Create a stateful application and try to retrieve the user, this will return `null`

**Comment by evansims** [comment]
Hi @LucWollants 👋 Good catch, thanks! I'll get a fix cut right away.
