### ISSUE TITLE
Feature Request: Ability To Specify Connection During Login

### ISSUE THREAD

**Issue by elliottlawson** [auth0/laravel-auth0#373]
### What should be added?

We use multiple enterprise connections per application and would apprecitate the ability to dynamically specify which connection should be used. Since upgrading to v7.x there doesn’t seem to be a way to natively do this via the stateful login controller. If possible, we would prefer to avoid duplicating and maintaining the logic within the controller just to add in this support.

As the underlying SDK does support a connection parameter, an easy way to enable this would be via a query string parameter.

```@php
// Auth0\Laravel\Http\Controller\Stateful LN:37

$url = $this->getSdk()->login(
    params: array_filter([
        ‘connection’ => $request->query(‘connection’),
    ]),
);
```

Then for routing to a specific connection

```@php
Route::get(‘/some-connection-login’, to_route(‘login’, [‘connection’ => ‘some-connection’]));
```

**Comment by evansims** [comment]
Hi, @elliottlawson 👋 Thanks for raising this. Let me think about this improvement request for a bit, and I'll get back to you.

Off the cuff, I'm a little hesitant to introduce something like this through query parameters for a few reasons. However, this feels like a good opportunity for leveraging Events. Your application could hook into an event raised by the SDK right before the `login()` method is called, to customize those parameters. I'll think on this a bit.

**Comment by evansims** [comment]
Hi @elliottlawson 👋 Thanks for your patience. I've created a PR that implements a new event supporting this. Take a look at #382 when you have a moment, and let me know what you think. Thanks!

**Comment by elliottlawson** [comment]
Hey @evansims!  Looks good. Your implementation of passing parameters via an event is quite eloquent! This will get us what we need. Thanks for taking the time to consider and implement. ⭐️
