### ISSUE TITLE
Multiple strategies on the same Laravel project?

### ISSUE THREAD

**Issue by gogl92** [auth0/laravel-auth0#374]
### What should be added?

As a developer I'd like to have a back office portal and in the same project the API of my system to avoid to create two different projects.

Is it possible to have multiple strategies on the same auth0 configuration?

**Comment by evansims** [comment]
Hi @gogl92, I'm afraid the SDK does not support multiple strategies simultaneously in the same application instance at this time. This feature is expected for the next major release: https://github.com/auth0/laravel-auth0/discussions/370
