### ISSUE TITLE
Add configuration to enable/disable cache

### ISSUE THREAD

**Issue by jeovajr** [auth0/laravel-auth0#380]
### What should be added?

Currently, the cache usage is subject to Laravel general settings for caching.

On Auth0, there's no setting to manually disable the cache for tokens.

On src/Auth0.php
```php
<?php
// ...
if (! isset($config['tokenCache']) || ! isset($config['managementTokenCache'])) {
    $cache = new LaravelCachePool();

    if (! isset($config['tokenCache'])) {
        $config['tokenCache'] = $cache;
    }

    if (! isset($config['managementTokenCache'])) {
        $config['managementTokenCache'] = $cache;
    }
}
// ...
```

That means I only have two options, set the entry `tokenCache` with my own cache adapter instance so I can use my own implementation, or keep it not set, so I can use Auth0's implementation.

I'd expect that, if the `tokenCache` is not set, then no cache would be used instead of defaulting to Auth0's implementation.

If `tokenCache` is defined, I'd expect it to be a class name, like `LaravelCachePool::class`, and then for it to be instantiated inside the if `if (! isset($config['tokenCache']) || ! isset($config['managementTokenCache'])) {` instead of expecting an already instantiated object. 

That's important because adding a object to a config value would make it impossible to use `php artisan config:cache` or `php artisan optimize`.

In order to use Auth0's implementation, I'd expect to set the `tokenCache` configuration to `true` or even to have another configuration entry to explicitly enable/disable cache.

Something in this line:

on config/auth0.php
```php
<?php
return [
   // ...
   'tokenCache' => LaravelCachePool::class,
   'enableTokenCache' => true,
   // ...
];
```

on src/Auth0.php
```php
<?php
return [
   // ...
  if (isset($config['tokenCache']) && isset(class_implements($config['tokenCache'])['Psr\Cache\CacheItemPoolInterface'])) {
    $config['tokenCache'] = new $config['tokenCache']();
  } else if($config['enableTokenCache']) {
    $config['tokenCache'] = new LaravelCachePool();
  }
  
  if (isset($config['managementTokenCache']) && isset(class_implements($config['managementTokenCache'])['Psr\Cache\CacheItemPoolInterface'])) {
    $config['managementTokenCache'] = new $config['managementTokenCache']();
  } else if($config['enableTokenCache']) {
    $config['managementTokenCache'] = new LaravelCachePool();
  }
   // ...
];
```

**Comment by evansims** [comment]
Hey @jeovajr 👋 Although I'd strongly recommend against disabling these changes, you make a good point, and I can understand the value in supporting that.

I'll create a PR that:
- Allows assigning `false` to disable these
- Allows `string` values for class names (like `Some\Cache::class`) or class aliases (like `cache.psr6`) to have the SDK instantiate these at runtime
