### ISSUE TITLE
New guard logic in v7.5/v7.6 breaks $guard->check()

### ISSUE THREAD

**Issue by miking7** [auth0/laravel-auth0#384]
### Laravel Version

Laravel 10.x

### SDK Version

SDK 7.6

### PHP Version

PHP 8.1

### What happened?

While upgrading from v7.4 to v7.6, we found that authentication checks (using Laravel's Authenticate middleware) are broken... and results in an infinite redirect loop - ie:
* /myroute --> /login --> /myroute --> /login --> ...

Sequence:
* Whenever `middleware('auth:web')` is applied to a route...
* The `authenticate()` function in Laravel's Authenticate.php -> `$this->auth->guard($guard)->check()`...
* ...but the new "Credential-based" `check()` -> `hasUser()` -> `$this->getCredential()` code introduced in v7.5 onwards no longer attempts to load the user from the session, but returns a null Credential... and a false hasUser().

I notice in a few places (ie: stateful logins / `Stateful/Login.php`) that the new codebase replaces simpler code that relied on `check()` with more complex code that relied on a combination of `check()` + `find()` - ie:
```php
# v7.4 LOGIC
$guard->check()

# v7.6 LOGIC
$guard->check() ? true : $guard->find(Guard::SOURCE_SESSION) instanceof Credential;   //
```

This obviously works well internally, but it breaks Laravel's 'auth' (Authenticate.php) middleware.

I can start trying to create a PR, but I'm still struggling to understand the reasons for the new 'Credential' layer... and I can already see there will be a lot of side-effects.

Note: this same bug is present in Laravel 9 as well as Laravel 10.

### How can we reproduce this issue?

Apply any session-based Laravel 'auth' guard (to a route/Controller/etc):
```php
middleware('auth:web')
```

### Additional context

Note 1: our simplified `config/auth.php` file looks roughly like this:
```php
    'defaults' => [
        'guard' => 'web',
    ],

    'guards' => [
        'web' => [
            'driver' => 'auth0.guard',
            'provider' => 'ffm_auth0_provider',
        ],
    ],

   'providers' => [
        'ffm_auth0_provider' => [
            'driver' => 'auth0.provider',
            'repository' => FaithFM\Auth0Pattern\Auth0PatternUserRepository::class,
        ],
    ],
```

Note 2: the reason why I'm keen to use Laravel's default 'auth' middleware is because although our web routes use only auth0 for authentication, our api routes need to allow either auth0-based OR URL-token-based authentication using `middleware('auth:api,web')`.

**Comment by evansims** [comment]
Hi @miking7 👋 Thanks for your question.

You can restore the previous before by using the `legacyGuardUserMethod` flag. Usage instructions are mentioned in [the CHANGELOG](https://github.com/auth0/laravel-auth0/blob/main/CHANGELOG.md#changes-to-user-behavior).

This change was intentional, and not a bug. Usage with `auth` is not reliable at present, but will be possible in a future version once we're able to fully separate the guards into independent stateful and stateless instances ([see roadmap](https://github.com/auth0/laravel-auth0/discussions/370)), but I do not have an ETA I can share for that yet.

Current guidance is to ensure requests are being routed through the configured SDK guard ([guidance on that here](https://github.com/auth0/laravel-auth0#guard-assignment)). Critically, you must use one of the provided middleware (`auth0.authenticate`, `auth0.authenticate.optional`, `auth0.authorize`, or `auth0.authorize.optional`) for routes, as these are responsible for setting up the user state.

**Comment by miking7** [comment]
Thanks @evansims.  We were already using the `legacyGuardUserMethod`, and we can change most of our codebase to use the provided `auth0.authenticate` (et-al) middleware... but this won't help for our api routes that need to allow authentication from **either** Auth0 **OR** our own URL-token-based authentication guard.  

I wiil eagerly await your updated code that unbreaks compatibility with Laravel's `auth` middleware... but in the meantime I'll probably write my own middleware to do the x-OR-y authentication checking manually.

Incidentally, your 'guard:XXX' middleware (`Auth0\Laravel\Http\Middleware\Guard.php`) implementation could readily be extended to allow for multiple alternative guards... just like Laravel's 'auth:XXX,YYY' middleware does with the `foreach ($guards as $guard)` loop in `Illuminate/Auth/Middleware/Authenticate.php`.

**Comment by miking7** [comment]
If anyone else is struggling with this, here's a temporary replacement middleware you can use (instead of Laravel's 'auth' middleware or auth0/login's 'guard' middleware).

Create this new middleware file `app/Http/Middleware/PatchedAuthenticationMiddleware.php`:
```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Auth\Middleware\Authenticate as LaravelAuthenticateMiddleware;
use Auth0\Laravel\Auth\Guard as Auth0Guard;
use Auth0\Laravel\Contract\Entities\Credential as Auth0Credential;

/**
 * Class PatchedAuthenticationMiddleware
 *
 * Registered as the 'auth.patched' middleware in app/Http/Kernel.php
 *
 * Usage:  (similiar to Laravel's 'auth:XXX,YYY' middleware)
 *    middleware('auth.patched)               // Check authentication using the default guard
 *    middleware('auth.patched:XXX')          // Check authentication using the 'XXX'' guard
 *    middleware('auth.patched:XXX,YYY')      // Check authentication using the 'XXX' OR the 'YYY' guard
 *
 * This class is a temporary workaround for Auth0's broken support for Laravel's 'auth' middleware (as-at v7.6 / Apr 2023).
 * See: https://github.com/auth0/laravel-auth0/issues/384
 *
 * We are extending Laravel's 'auth' middleware (Illuminate/Auth/Middleware/Authenticate.php) which allows multiple (OR-ed) guards to be specified.
 * We have added additional logic to load Auth0 Credentials from the Session - since auth0/login's check() method does not do this.
 *
 * @package App\Http\Middleware
 */
class PatchedAuthenticationMiddleware extends LaravelAuthenticateMiddleware
{
    /**
     * Determine if the user is logged in to any of the given guards.
     * NOTE: Overriding Laravel's default one XXXXXXXX
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  array  $guards
     * @return void
     *
     * @throws \Illuminate\Auth\AuthenticationException
     */
    protected function authenticate($request, array $guards)
    {
        if (empty($guards)) {
            $guards = [null];
        }

        foreach ($guards as $guardName) {
            $guard = $this->auth->guard($guardName);

            if ($guard->getName() === 'web_guard') {
                // Hack to compensate for auth0/login v7.6's broken support for Laravel's 'auth' middleware. (See: https://github.com/auth0/laravel-auth0/issues/384)
                // Concept taken from logic found in auth0/login / Http/Controller/Stateful/Login.php
                $loggedIn = $guard->check() ? true : $guard->find(Auth0Guard::SOURCE_SESSION) instanceof Auth0Credential;
            } else {
                $loggedIn = $guard->check();
            }

            if ($loggedIn) {
                return $this->auth->shouldUse($guardName);
            }
        }

        $this->unauthenticated($request, $guards);
    }

}
```

Register it in `app/Http/Kernel.php`:
```php
    protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'auth.patched' => \App\Http\Middleware\PatchedAuthenticationMiddleware::class,
        ...
```

Use it like this...
```php
middleware('auth.patched:api,web')
```
...instead of this:
```php
middleware('auth:api,web')
```

**Comment by LeadingreIT** [comment]
The behavior described by @miking7 is exactly what we are encountering, brand new Laravel 10.9.0 project and install of composer require auth0/login:^7.0 --with-all-dependencies.  cannot get this updated version to work, continuously loops as described above: /myroute --> /login --> /myroute --> /login --> ...
