### ISSUE TITLE
Laravel Auth0 Guard Returning Empty Array on Production Server

### ISSUE THREAD

**Issue by xerk** [auth0/laravel-auth0#389]
### Laravel Version

Other (specify in 'additional context')
8.12

### SDK Version

SDK 7.1

### PHP Version

Other (specify in 'additional context')
local: 7.4.16
prod: 7.4.33

### What happened?

Hey there!

I have an issue with the "auth0/laravel-auth0" repository on GitHub. I installed auth0 on my local machine, and everything worked fine with version 7.1 and Laravel 8.12. However, when I deployed my application to production and changed the redirect URI to the production domain name, I faced an issue.

Whenever I try to log in using auth0, it redirects me back to the login page. To debug the issue, I checked the callback and found that my auth0 guard is returning an empty array.

I think this might be related to the version I am using and the fact that I am using Docker on my production server but not on my local machine. Can anyone help me with this issue? Thanks!

### How can we reproduce this issue?

1. Install the "auth0/laravel-auth0" package in a Laravel 8.12 application on your local machine.
2. Configure the package according to the instructions provided in the package documentation.
3. Create a login page and a callback route to handle the auth0 authentication.
4. Test the application to make sure that everything works as expected on your local machine.
5. Deploy the application to a production server, making sure to change the redirect URI to the production domain name.
6. Try to log in using auth0 on the production server.
7. Verify that the application redirects you back to the login page instead of successfully authenticating you.

This issue seems to be reproducible consistently, as the error occurs every time the user tries to log in using auth0 on the production server.

### Additional context

Laravel 8.12
PHP version: 7.4

**Comment by evansims** [comment]
Hi, Xerk 👋 The versions of Laravel and PHP you mentioned are unsupported, as both have reached EOL. If you upgrade to support versions, and the latest version of the SDK, and continue to see issues, please feel free to open a bug report here. If you are for some reason unable to upgrade, you might [try asking on the Auth0 Community](https://community.auth0.com/).

Given that this is working on your local machine and suddenly doesn't in production, this doesn't sound like an SDK issue — you should check your Auth0, Laravel, and PHP logs to determine the cause.

**Comment by xerk** [comment]
@evansims, thanks for the help I found the solution it was related to the 502 error code from the callback, 
https://github.com/auth0/laravel-auth0/issues/259#issuecomment-1040499188
