### ISSUE TITLE
Optionally signing user in from JWT

### ISSUE THREAD

**Issue by Andy0708** [auth0/laravel-auth0#39]
Hello,

I am using this library in conjunction with JWT. By using the currently available middleware, I can limit access to routes to users who have a valid JWT, and this works great. The middleware decodes the JWT based on the `Authorization` header and logs the user into Laravel if everything is OK.

However, I have some routes for which it is optional whether or not the user is logged in, hence why I cannot make use of the provided middleware. Basically I want the user to be logged in if a valid JWT is provided, and otherwise proceed, even if no JWT is present. Sometimes you just want to access the logged in user if available, without _requiring_ the user to be logged in. I _could_ roll my own logic to parse the `Authorization` header similar to how the middleware does it, but I kind of want to keep this stuff in the middleware.

As far as I can tell, there is currently nothing in the library that enables this, because access to the user relies on the middleware. Therefore, I am thinking of adding a new middleware that checks if a JWT is provided and logs the user in if it is valid and does nothing otherwise. This would be very similar to how the current middleware works.

I can quite easily go ahead and implement my own middleware and be done with it, but I was thinking that perhaps this could be a nice addition to this library. I was thinking of something like the below.

1. Implement a middleware that logs the user in if a valid JWT is provided. Otherwise it does nothing
2. Refactor the current middleware to return a 401 response if the user is not signed in (remove JWT decoding etc.)

The idea is to refactor the current middleware to have a single responsibility instead of doing more than one thing (decoding JWT + authorization check + logging in). So to have users with a valid JWT signed in, one middleware would be used (probably enabled for most of the application), and to restrict certain routes to signed in users, another one would be used. This does require two middlewares to accomplish the same thing as today, but it seems cleaner to do it this way. Perhaps using a middleware group would mean that the configuration is not more complex than today?

Anyways, the above would kind of break backwards compatibility, so it should probably be done in smaller steps. The "optional" middleware could easily be added without any problems, and when there is an opportunity to break backwards compatibility, the last refactor could be done.

I will have to implement this either way, and I am open to opening a pull request if there is an interest for it. What do you think?

**Comment by glena** [comment]
Sounds good, but since I want to avoid BC breaks, I would go ahead by adding a new one and keep the current as it is, what do you think?

**Comment by glena** [comment]
What do you think of something like this? 

https://github.com/auth0/laravel-auth0/pull/40


so using the `auth0.optional-jwt` middleware should do the trick.

```
...

protected $routeMiddleware = [
	...
	'auth0.jwt' => 'Auth0\Login\Middleware\Auth0JWTMiddleware',
	'auth0.optional-jwt' => 'Auth0\Login\Middleware\Auth0OptionalJWTMiddleware',
];

...
```

**Comment by Andy0708** [comment]
Yeah, something like that should work (except the undefined variable on line 22 ;-)). It is not really as pretty as I had hoped for, because it is kind of a workaround to not break backwards compatibility, but I totally understand that.

I am thinking if it would be an idea to go all the way by introducing two new middlewares as I proposed in my first comment. As long as the existing middleware keeps its functionality as is, this would not be an issue (other than providing an additional middleware, of course). The reason I mention this is because this would make it possible to use the optional middleware for all routes and then restricting certain routes - without decoding the JWT twice.

It's not a big deal, and your approach would work fine and be a little less intrusive, although slightly less flexible. Let me know if you would like to see a pull request on this, but otherwise you have my thumbs up on your approach. 👍

**Comment by glena** [comment]
well, in this scenario, you can really build your own middleware to do the check. 

As simple as:

```
<?php namespace App\Middleware;

class Auth0JWTMiddleware {

    public function handle($request, \Closure $next)
    {
        if ( ! \Auth::check()) {
            return \Response::make("Unauthorized user", 401);
        }

        return $next($request);
    }

}
```

register the middleware and you should be done

**Comment by Andy0708** [comment]
Yeah true, in combination with the optional middleware, that would work. You are right, it's totally fine to implement my own middleware for that. So yeah, including the optional middleware would be awesome! :-)

**Comment by glena** [comment]
nevermind, I added this middleware too (ForceAuthMiddleware).

Do you mind to give it a try?

I can cut off a new release after that

**Comment by Andy0708** [comment]
Sounds great. I will give it a spin ASAP and get back to you. Thanks!

**Comment by glena** [comment]
@Andy0708 check `3.2.0` :)

**Comment by medinagabriel** [comment]
Thanks for this, saved my day.
