### ISSUE TITLE
Sanctum 401 1st party API access errors after upgrade to 7.7

### ISSUE THREAD

**Issue by seivad** [auth0/laravel-auth0#391]
### Laravel Version

Laravel 10.x

### SDK Version

SDK 7.7

### PHP Version

PHP 8.1

### What happened?

Hey guys, I was using 7.4 with Laravel 9.x but needed to upgrade to 10.x so I was forced to upgrade to 7.7. I updated the auth.php config with the new changes including:

**Snippets (not complete code):**
```
'guards' => [
        'auth0' => [
            'driver' => 'auth0.guard',
            'provider' => 'auth0',
        ],
 ```
 
 and
 
 ```
 'providers' => [
        'auth0' => [
            'driver' => 'auth0.provider',
            'repository' => App\Auth\CustomUserRepository::class,
        ],
```

and previously my local API routes which utilise auth:sanctum as middleware now get 401 errors. I am using Inertia (vue) and there are a number of endpoints for table data that hit the API locally. 

I also had to change the way the user was retrieved in the HandleInertiaRequests class, previously I had:

```
$profile = auth()->user();
```

Which I could pass into the array_merge() to pass the user into each inertia vue template but the only way I could get the user now since upgrading to 7.7 is:

```
        $guard = auth()->guard();
        $credential = $guard->find(Guard::SOURCE_SESSION);
        $profile = $credential?->getUser();
        ```

I don't quite understand the ->guard() change, but it really broke a ton of my code.

My gut feeling now is that auth:sanctum middleware can't access the logged in user that Auth0 provider should be setting in the session and now the cookie token is wrong, causing a 401 error when hitting the api routes from the inertia vue templates via Axios. 
       
As a litmus test, my API endpoints still all work 100% when testing via Postman where I pass in a personal access token (bearer token) so I know sanctum is actually fine, I just don't think Auth0 is passing the logged in user correctly now in the views / controllers / session. I'm at a loss.       

### How can we reproduce this issue?

Maybe the best reproduction would be to setup Auth0 in a fresh laravel 10.x app and also follow the Laravel Sanctum documentation to setup for 1st party api access and see if you can get it to work via an axios call within a vue template.

### Additional context

All help is appreciated to help resolve this 401 unauthenticated errors after upgrading. I've got this on a new branch so it's not breaking production but I can't upgrade to Laravel 10.x but 7.4 requires packages that only Laravel 9.x has when running the composer update.

**Comment by evansims** [comment]
Hi @seivad 👋 Thanks for your question, and sorry to hear you're hitting a challenge there.

Unfortunately, Laravel's `auth` middleware is incompatible with 7.7. It is designed to use the bundled, specialized authentication middleware [outlined in the README](https://github.com/auth0/laravel-auth0#routing-middleware) (such as `auth0.authenticate`.)

SDK 7.8 will be released within the next few days, restoring compatibility with `auth`.

**Comment by seivad** [comment]
Hey thanks for writing back, do you mind updating this ticket once it has been released and i'll try it out on my other branch which has upgraded everything to Laravel 10.x and confirm if Sanctum works again. That will probably help a fair few people out there utilising Livewire or Inertia who will hit this issue.

**Comment by evansims** [comment]
👋 [7.8 is now available.](https://github.com/auth0/laravel-auth0/releases/tag/7.8.0) Please be sure to read the README, as integration guidance has changed with the introduction of the new Guard APIs.

**Comment by seivad** [comment]
@evansims Thanks mate, I will switch over to my other branch and give it a spin tomorrow - see what happens. It looks like you guys have implemented a more simple approach, i'll know pretty quick if I can run with it - if sanctum works, happy days!

**Comment by evansims** [comment]
Closing for now since it's been a bit, and I'm 99% sure this should be resolved now, but feel free to update the thread with your experience when you have time. Much appreciated!

**Comment by axsann** [comment]
When I use "->middleware('auth')" in api.php,
{"message": "Unauthenticated."} is returned even if it is a valid token.

Laravel version is 10.12.0 and auth0/login version is 7.8.1.

The auth()->check() seems to work fine.

Could you please check?

**Comment by axsann** [comment]
Thanks @evansims.
However there still seems to be a problem.

When I use "->middleware('auth')" in api.php,
{"message": "Unauthenticated."} is returned even if it is a valid token.

Laravel version is 10.12.0 and auth0/login version is 7.8.1.

The auth()->check() seems to work fine.

Could you please check?

PS: I used ->middleware('auth0.authorize') instead and it worked.

**Comment by evansims** [comment]
@axsann Happy to take a look, but that would not have anything to do with this issue — let's follow up in a new issue on this, if you don't mind. Thanks!
