### ISSUE TITLE
Does this only work if laravel's session driver is set to 'file'?

### ISSUE THREAD

**Issue by annakopp** [auth0/laravel-auth0#392]
### What should be added?

I haven't seen this documented anywhere but from reading various other issues it seems like that's the case, but I might be missing something.  Is it at all possible to use the 'cookie' session driver? We are behind a load balancer and so can't use 'file'.

**Comment by evansims** [comment]
Hi @annakopp 👋 Thanks for your question.

The SDK applies the standard Laravel Sessions API. There's nothing non-standard/custom that would interfere with normal behavior, or require any particular driver use.

**Comment by annakopp** [comment]
@evansims When I try to run the example project and set the `SESSION_DRIVER` to `cookie` it doesn't ever log the user in, and in some cases results in a redirect loop, but it works fine when it's set to `file`. I was also reading some comments on auth0 community forum and it seemed like people had similar issues (but not 100% sure).

**Comment by evansims** [comment]
Hey @annakopp 👋 I'm not able to find any Community threads with similar reports offhand, unfortunately, but please let me know if you find any that I may have missed. (Other questions about `SESSION_DRIVER`, particularly with older Laravel/SDK versions, though! Probably what you came across.)

As the SDK simply reads and writes data from the Laravel Session APIs, there's not really anything I can suggest doing differently about this from the SDK's perspective. The SDK doesn't interact directly with any session driver and is completely agnostic as to how it's configured. 😞

**Comment by annakopp** [comment]
@evansims hmm maybe my issue is unrelated to the other issues I found, but when I'm running the example project (https://github.com/auth0-samples/laravel, updated to php 8.1 & version 7.7 of this lib) if I all I do is change session driver from file to cookie, login no longer works. I made this video to quickly demonstrate but let me know if there's anything else I should share:

https://github.com/auth0/laravel-auth0/assets/3953261/141c8340-bcdf-425b-96dc-c38dfc3e8a49

**Comment by evansims** [comment]
I suspect you're probably hitting the cookie size limit imposed by the browser. I'm surprised Laravel doesn't implement a reliable cookie chunking strategy to avoid it, but that is my best guess. Unfortunately, we simply do not have any control over how Laravel does session handling in its drivers. I suggest using Redis or another database driver to circumvent the issue for production.
