### ISSUE TITLE
Current version (7.8) fails to parse .env comments

### ISSUE THREAD

**Issue by bluehaoran** [auth0/laravel-auth0#394]
### Laravel Version

Laravel 10.x

### SDK Version

SDK 7.7

### PHP Version

PHP 8.1

### What happened?

My .env files has comments, e.g.:
```
#Laravel configuration
APP_NAME=Laravel
APP_ENV=local
#etc
```

When I run `composer install`, the package scripts run and fall over at `vendor/auth0/login/src/Configuration.php:327`.

This is because the new version of Configuration.php fails to correctly ignore comments, per the [.env file specs](https://github.com/vlucas/phpdotenv#comments).

### How can we reproduce this issue?

Add a comment to your .env file, e.g. a line such as `#This is a comment`.

**Comment by bluehaoran** [comment]
Actually, to be more precise, it will also fail any non-empty line without an `=`.

**Comment by evansims** [comment]
Thanks for the heads up! I'll cut a fix for that first thing tomorrow morning
