### ISSUE TITLE
.env and json file location option

### ISSUE THREAD

**Issue by cwp-michaell** [auth0/laravel-auth0#397]
### What should be added?

Would it be possible to add the ability to locate the json and/or .env files used for configuration is a sub directory rather than root directory.

The reason for the request is based around containerisation.

Kubernetes allows for mounting of storage locations to containers, but this feature can't be used for storage of the auth0 configuration files( even though it is ideally suited for it) because they are expected in the root directory. If we could specify or if a specific directory was added to the getEnvironment and getJson functions this would allow this feature to be used.

**Comment by evansims** [comment]
Hey, @cwp-michaell! 👋 Thanks for your feature suggestion.

Sure thing, that should be a pretty simple change to make. We can expose a new optional key in the configuration to assign the configuration search path. I'll work on that next week when I return from vacation. Thanks!
