### ISSUE TITLE
Getting `Auth guard [auth0-session] is not defined` when upgrading from 7.7 to 7.8.1

### ISSUE THREAD

**Issue by uandco** [auth0/laravel-auth0#398]
### Laravel Version

Laravel 9.x

### SDK Version

SDK 7.8

### PHP Version

PHP 8.1

### What happened?

When upgrading from a working setup using 7.7 to 7.8.1, I get this error as soon as I try to load the homepage of the app, which is not even guarded.

`Auth guard [auth0-session] is not defined. {"exception":"[object] (InvalidArgumentException(code: 0): Auth guard [auth0-session] is not defined. at /app/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:86)`

### How can we reproduce this issue?

Use these auth and auth0 configs from a working SDK 7.7 setup:

`config/auth0.php`:

```
<?php

declare(strict_types=1);

return [
    'strategy' => env('AUTH0_STRATEGY', 'webapp'),
    'domain' => env('AUTH0_DOMAIN'),
    'customDomain' => env('AUTH0_CUSTOM_DOMAIN'),
    'clientId' => env('AUTH0_CLIENT_ID'),
    'redirectUri' => env('AUTH0_REDIRECT_URI', env('APP_URL') . '/auth0/callback'),
    'clientSecret' => env('AUTH0_CLIENT_SECRET'),
    'audience' => \Auth0\Laravel\Configuration::stringToArrayOrNull(env('AUTH0_AUDIENCE')),
    'scope' => \Auth0\Laravel\Configuration::stringToArrayOrNull(env('AUTH0_SCOPE')),
    'organization' => \Auth0\Laravel\Configuration::stringToArrayOrNull(env('AUTH0_ORGANIZATION')),
    'cookieSecret' => env('AUTH0_COOKIE_SECRET', env('APP_KEY')),
    'cookieExpires' => env('COOKIE_EXPIRES', 0),
    'cookieDomain' => env('AUTH0_COOKIE_DOMAIN'),
    'cookiePath' => env('AUTH0_COOKIE_PATH', '/'),
    'cookieSecure' => \Auth0\Laravel\Configuration::stringToBoolOrNull(env('AUTH0_COOKIE_SECURE'), false),
    'routes' => [
        'home' => env('AUTH0_ROUTE_HOME', '/'),
        'login' => env('AUTH0_ROUTE_LOGIN', 'login')
    ]
];
```

With these ENV vars declared:
AUTH0_DOMAIN
AUTH0_CUSTOM_DOMAIN
AUTH0_CLIENT_ID
AUTH0_CLIENT_SECRET
AUTH0_SCOPE="openid email profile groups"

`config/auth.php`:

```
<?php

return [
    'defaults' => [
        'guard' => 'auth0',
        'passwords' => 'users',
    ],
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'auth0' => [
            'driver' => 'auth0.guard',
            'provider' => 'auth0',
        ],
    ],
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],

        'auth0' => [
            'driver' => 'auth0.provider',
            'repository' => \Auth0\Laravel\Auth\User\Repository::class
        ],
    ],
    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
            'throttle' => 60,
        ],
    ],
    'password_timeout' => 10800,
];
```
Upgrade to SDK 7.8+

### Additional context

According to the CHANGELOG, "Developers using the previous syntax will have their existing configurations applied to all guards uniformly", but that doesn't seem to be the case?

There doesn't seem to be any breaking change, unless I missed something?

I also tried to use the default `web` guard in `config/auth.php` to no avail.

**Comment by evansims** [comment]
Hi, @uandco! 👋 Thanks for bringing this issue to us, and apologies for the challenge. I'm a bit perplexed about why that would happen to you. The only case in which I can think that `auth0-session` would be expressly required is when `registerMiddleware` is true. When this is true, the middleware is injected into the `web` middleware group, ensuring the `auth0-session` guard is applied. And while this is the default, that is only the case under the new configuration value.

It sounds as though `registerMiddleware` is bring invoked even when not using the new configuration for you, and I'm not quite sure why that would be the case offhand.

Can you try changing the name of your Guard from `auth0` to `auth0-session` and see if that at least resolves the error for you?

I'm on vacation until next week but I can look deeper into this when I get back.

**Comment by uandco** [comment]
Hi @evansims thanks for your reply. Using the `auth0-session` guard instead of `auth0` indeed works for non authenticated routes.

But once I get redirected to `/login`, I get `Auth guard [auth0] is not defined.`
This is because I still have the login route manually declared with the `guard:auth0` middleware.
Changing this to `guard:auth0-session` or removing the route declaration altogether as this is not auto-declared then triggers another error:

`Method Auth0->login() requires a stateful `strategy` with sessions configured.`

**Comment by evansims** [comment]
Can you post what your `config/auth0.php` file looks like, redacting any sensitive details?

**Comment by uandco** [comment]
@evansims I posted it in the original report, along with the env vars that are populated. Let me know if you need anything else.

**Comment by evansims** [comment]
@uandco Gotcha, thanks. I'm at a loss as to why this would occur for you without the new configuration format being used. It definitely shouldn't be the case. I won't be able to dig deeper until I return from vacation next week, but my recommendation for the moment is to migrate to the new configuration/integration guidance for 7.8+. It provides a better integration experience, anyway. Instructions are available in the README. But I'll follow up with you next week if I can track down what might be causing this, regardless. Thanks!

**Comment by uandco** [comment]
@uandco no worries, I froze the component version for now as I have very little bandwidth to look at using the new config format, but fixing the way the old format is used, or documenting 7.8.1 has breaking changes if the old config can't be used after all, would be great.

**Comment by evansims** [comment]
Hi @uandco 👋 Unfortunately, I've not been able to replicate the issue you're hitting here. The old configuration format is definitely supported, but I'm uncertain why it isn't working in your circumstance. I'll continue researching, but I'll close for now as I don't have any additional suggestions beyond migrating. Sorry about that!

**Comment by uandco** [comment]
Hi @evansims, thanks for looking into this. I actually tried to upgrade again yesterday, using the environment variables only, and I still got the same error, so it’s not related to the old config. Just confirming you tried to replicate in Laravel 9 and not 10? I will create a minimal project I can share.

**Comment by uandco** [comment]
@evansims I invited you to the https://github.com/uandco/laravel-auth0-78-issue repo, which is the minimal setup to reproduce this

**Comment by nickescobedo** [comment]
Also have the same issue as @uandco. Migrating from 7.4 -> 7.91. I get the same error `Auth guard [auth0-session] is not defined`. Then I changed the guard to be `auth0-session` and receive the same `Method Auth0->login() requires a stateful `strategy` with sessions configured.`.

Looking for ideas.
