### ISSUE TITLE
Update to 7.8 changed environment file parsing

### ISSUE THREAD

**Issue by tricki** [auth0/laravel-auth0#399]
### Laravel Version

Laravel 9.x

### SDK Version

SDK 7.8

### PHP Version

PHP 8.1

### What happened?

After upgrading from 7.4 to 7.8 and updating to the new configuration I got a "Service not found" error.

After some debugging (which included not understanding why I can't find a "service" configuration) I found that quotes in the environment file appear to be interpreted differently. I had this in my .env file:

```
AUTH0_AUDIENCE="https://sub.example.com/api"
```

This used to work but stopped working after the update. Once I removed the quotes it worked fine.

Ideally quotes should be interpreted equally, otherwise perhaps the docs should mention it. Especially since this isn't immediately obvious from the error message `Service not found: "https://sub.example.com/api"` 

### How can we reproduce this issue?

Set a valid audience value in quotes.

**Comment by devjack** [comment]
Can confirm this happens to other .env vars as well. In attempting to get 7.8 upgrade done I found `AUTH0_REDIRECT_URI` similarly included the quotes from .env in the value being passed in the call.

**Comment by evansims** [comment]
Hi @tricki 👋 Thanks for letting us know! I'm on vacation until next week, but I'll address this when I return. In the meantime, as you mentioned, removing the quotation marks around your strings serves as a workaround. 👍
