### ISSUE TITLE
v7.8 does not support opaque tokens for /userinfo

### ISSUE THREAD

**Issue by devjack** [auth0/laravel-auth0#401]
### Laravel Version

Laravel 10.x

### SDK Version

SDK 7.8

### PHP Version

PHP 8.1

### What happened?

When configuring an application with no AUTH0_AUDIENCE, the SDK will (successfully) complete an authentication request and receive an ID token & an opaque access token.

The AuthentigationGuard.php:303 assumes an access token is a JWT and attempts to parse it. However access tokens aren't always JWT's (see Auth0 docs: https://auth0.com/docs/secure/tokens/access-tokens#opaque-access-tokens).

Will open a suggested PR to silently catch and ignore the `\Auth0\SDK\Exception\InvalidTokenException` that is thrown in this case.

### How can we reproduce this issue?

Composer dependencies:
```
➜ vendor/bin/sail composer show
auth0/auth0-php                                8.6.0    PHP SDK for Auth0 Authentication and Management APIs.
auth0/login                                    7.8.1    Auth0 Laravel SDK. Straight-forward and tested methods for i...
```

Configure a 'webapp' (authorization_code flow) application with no audience value and complete an authentication request to Auth0.

**Comment by evansims** [comment]
Hi @devjack 👋 Thanks for your suggestion. I see the merit in your suggestion; however, this is not something we're looking at integrating support for at this time — it presents significantly more work than just ignoring the parser exception to implement reliably. We'll backport this feature request for future consideration.

In the meantime, I suggest creating a custom route that simply makes the call to the API manually using a provided opaque token.
