### ISSUE TITLE
7.8 route namespace and redirect url

### ISSUE THREAD

**Issue by Tamrael** [auth0/laravel-auth0#403]
### Checklist

- [ ] This can be reproduced using [the quickstart sample application](https://github.com/auth0-samples/laravel).
- [X] I have looked at [the README](https://github.com/auth0/laravel-auth0/#readme) and have not found a solution.
- [X] I have looked at [the `docs` directory](https://github.com/auth0/laravel-auth0/blob/main/docs) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/laravel-auth0/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/laravel) and have not found a solution.
- [X] I agree to uphold [the Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Laravel Version

9

### SDK Version

7.8

### PHP Version

PHP 8.2

### Description

The new code doesn't allow for any moving of the routes to another namespace e.g. "auth/login", "auth/logout" and "auth/callback" because the redirects are hard-coded to "/login".

### How can we reproduce this issue?
put this code into "routes/web.php" and try to login while
`Route::get('login', [ImportantMainController::class, 'main'])->middleware('auth0.authenticate');`
`Route::group(['prefix' => 'auth', 'namespace' => '\\', 'middleware' => ['web']], function () {Auth0::routes();});`

**Comment by evansims** [comment]
Hi @Tamrael 👋 This is still possible, you need to register the routes manually. Guidance on that is available here: https://github.com/auth0/laravel-auth0/blob/main/docs/Configuration.md#authentication-routes

**Comment by Tamrael** [comment]
@evansims do you see a future where you use named routes for redirects instead of hard-coded redirects?
See above comment. This effectively blocks us from moving from 7.6 to 7.8
