### ISSUE TITLE
Link directly to signup page

### ISSUE THREAD

**Issue by annakopp** [auth0/laravel-auth0#404]
### Checklist

- [X] I agree to uphold [the Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We need to direct users to a sign up page (instead of login). I think the auth0-php lib allows for that (https://github.com/auth0/auth0-PHP/blob/main/docs/API/Auth0.md#signup) but it doesn't look like that's possible in this library.

**Comment by evansims** [comment]
Hi @annakopp 👋 Thanks for your question.

The Laravel SDK is built on top of the PHP SDK, so it inherits all the same functionality. If an alias for an underlying method is not provided by the Laravel SDK directly, you can access the underlying PHP SDK instance by calling `getSdk()` from the SDK's Facade.

For example, here's a route controller that calls the method you're looking to use:

```php
<?php

declare(strict_types=1);

namespace App\Controllers;

use Auth0\Laravel\Facade\Auth0;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class SignupController
{
    public function __invoke(
        Request $request,
    ): Response {
		$url = Auth0::getSdk()->signup();
		return redirect()->away($url);
	}
}
```

**Comment by georgeharito** [comment]
Hi @evansims 

I've tried your code above (`Auth0::getSdk()->signup()`) after adding `use Auth0\Laravel\Facade\Auth0` at the top of my file, but when I call the `signup()` function, a Laravel exception is raised: 

> Method Auth0->signup() requires a stateful `strategy` with sessions configured.

I already have Auth0 set up in my Laravel project, with the /login, /logout and /callback routes set to the defaults within my routes/web.php file (using `Auth0::routes()`) but I am wanting to add a Sign Up button on the welcome page of my project. 

Is there another way to get the URL string from signup() working, or am I doing something wrong?

Many thanks.
