### ISSUE TITLE
When invalid JWT is provided, error 500 is returned

### ISSUE THREAD

**Issue by seanmangar** [auth0/laravel-auth0#41]
I noticed that if I change the Authorisation Bearer Token to some garbage value, it throws a 500 (internal server error), instead of returning a 401 Unauthorized error, indicating that "The request has not been applied because it lacks valid authentication credentials for the target resource."

Reference: https://httpstatuses.com/401

**Comment by glena** [comment]
can you elaborate a little more? it is answering with a 401 if:

- There is no token
- There is an issue decoding the token
- No use matches with the token

(check https://github.com/auth0/laravel-auth0/blob/master/src/Auth0/Login/Middleware/Auth0JWTMiddleware.php#L32)

Do you have any error message?
Do you see any unhandled exception in your logs?

**Comment by seanmangar** [comment]
Hi glena,

Thanks for response and apologies for the delayed response.

- There is a token, but it is purposefully malformed, so I am guessing this is an issue decoding the token (This is what I tested with: fefe.eyJpc3MiOiJodHRwczovL21ha2VyaHViLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1NzhmZDIyMTZjYTZhNWY3MzJiNmM4M2UiLCJhdWQiOiJHSjZiOVBEZk5DR0dNR3NOQTRVVzNoMFVZTllER0RoOSIsImV4cCI6MTQ2OTY0NjM2MywiaWF0IjoxNDY5NjEwMzYzfQ.ZglIdpK8Vtk1mYRh4ck)
- An exception is thrown. See below:
```
[2016-07-27 09:07:18] local.ERROR: ErrorException: Trying to get property of non-object in /home/vagrant/makerhub-laravel/vendor/auth0/auth0-php/src/Auth0JWT.php:43
Stack trace:
#0 /home/vagrant/makerhub-laravel/vendor/auth0/auth0-php/src/Auth0JWT.php(43): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/home/vagrant/m...', 43, Array)
#1 /home/vagrant/makerhub-laravel/vendor/auth0/login/src/Auth0/Login/Auth0Service.php(101): Auth0\SDK\Auth0JWT::decode('fefe.eyJpc3MiOi...', Array, 'dYLPStjgEJGUImq...', Array)
#2 /home/vagrant/makerhub-laravel/vendor/auth0/login/src/Auth0/Login/Middleware/Auth0JWTMiddleware.php(37): Auth0\Login\Auth0Service->decodeJWT('fefe.eyJpc3MiOi...')
#3 [internal function]: Auth0\Login\Middleware\Auth0JWTMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#4 /home/vagrant/makerhub-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#5 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#6 /home/vagrant/makerhub-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#7 /home/vagrant/makerhub-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
```

**Comment by glena** [comment]
mmm ok, the header is not valid.

That is weird, this exception should be handled here https://github.com/auth0/laravel-auth0/blob/master/src/Auth0/Login/Middleware/Auth0JWTMiddleware.php#L36-L41

which version of the sdk are you using?

**Comment by seanmangar** [comment]
I'm using version 3.1 of the sdk. Looking at the [node implementation](https://github.com/auth0/node-jsonwebtoken). 

It isn't being caught because in the Auth0 file, there is no check on whether the alg property exists on $head. Can I submit a pull request with these changes?
```
$head = json_decode(JWT::urlsafeB64Decode($headb64));

        if ($head->alg === 'RS256') {
            $body = json_decode(JWT::urlsafeB64Decode($body64));
            if ( !in_array($body->iss, $authorized_iss) ) {
                throw new CoreException("We can't trust on a token issued by: `{$body->iss}`.");
            }
            $secret = self::fetch_public_key($body->iss);
        } elseif ($head->alg === 'HS256') {
            $secret = JWT::urlsafeB64Decode($client_secret);
        } else {
            throw new CoreException("Invalid signature algorithm");
        }
```

**Comment by glena** [comment]
right, saw that exception and didnt realise it was the framework error handler.

i guess that adding will be enough

```
if ( !($head instanceof stdClass) || ! isset($head->alg))
{
    throw new CoreException("Invalid token");
}
```

**Comment by seanmangar** [comment]
Yes I think that will work. Maybe we should add a custom exception. CoreException is not descriptive enough. Could be something like InvalidTokenException.

**Comment by glena** [comment]
@seanmangar sorry for the delay, upgrade auth0-php to `3.4.2` :)

https://github.com/auth0/auth0-PHP/commit/38ad6237de9af07fa39b7e1c0abdeb5b0106e794

**Comment by glena** [comment]
upgrade to `3.4.3` because of https://github.com/auth0/auth0-PHP/pull/97
