### ISSUE TITLE
Error on custom repository and model 

### ISSUE THREAD

**Issue by squpshift** [auth0/laravel-auth0#413]
### Checklist

- [X] This can be reproduced using [the quickstart sample application](https://github.com/auth0-samples/laravel).
- [X] I have looked at [the README](https://github.com/auth0/laravel-auth0/#readme) and have not found a solution.
- [X] I have looked at [the `docs` directory](https://github.com/auth0/laravel-auth0/blob/main/docs) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/laravel-auth0/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/laravel) and have not found a solution.
- [X] I agree to uphold [the Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Laravel Version

10

### SDK Version

7.8

### PHP Version

PHP 8.2

### Description

Re-opening [issue](https://github.com/auth0/laravel-auth0/issues/385)

> I'm attempting to implement a custom repository that utilizes Eloquent ORM (from this link - https://github.com/auth0/laravel-auth0/blob/main/docs/User%20Models%20and%20Repositories.md), but I've encountered an error: Call to undefined method App\Models\User::where(). I believe the issue stems from the fact that the Auth0\Laravel\Model\User class does not extend the Laravel model, resulting in the absence of a ::where() method.
> 
> Could you please tell me what went wrong with the integration process based on the above documentation?

@evansims your initial response was: 

> Whoops, you're totally correct, I forgot to include the Eloquent user model! That's an embarrassing oversight. 🤦 I'll get that fixed yet today, thanks for the heads up!

The issue was then closed on the grounds that it was "becoming a catch-all for feedback" without ever addressing the core problem which you described as an "embarassing oversight".

Are we doing something wrong here? Is the documentation missing something or mis-guiding us? I have now spent multiple days trying to get this integration working and we just won't be able to use Auth0 for our project if we can't resolve this soon. 

Additionally, I have tried starting a brand new bare-bones laravel project with the most basic auth0 auth using the sample code here https://github.com/auth0-samples/laravel. I've followed the documentation exactly and am not able to get it working - I'm encountering this issue https://github.com/auth0-samples/laravel/issues/146 and am unable to resolve it using the suggestion in the discussion as the author did https://github.com/auth0-samples/laravel/issues/146#issuecomment-1500929473. I'll create a separate issue for that.

Really appreciate any guidance. 

### How can we reproduce this issue?

currently don't seem to be able to due to https://github.com/auth0-samples/laravel/issues/146

**Comment by evansims** [comment]
@squpshift

Reopening closed issues is not necessary. [The solution was provided](https://github.com/auth0/laravel-auth0/issues/385#issuecomment-1589969438) in the thread you linked: extend the abstract class. Have you tried that guidance?

In regards to having issues with a sample quickstart application, please open an issue in the appropriate repository so we can troubleshoot it more efficiently.
