### ISSUE TITLE
Getting 'unauthorized'

### ISSUE THREAD

**Issue by vladimir-yuldashev** [auth0/laravel-auth0#42]
ErrorException in Auth0.php line 244:
Illegal string offset 'error'

HandleExceptions->handleError('2', 'Illegal string offset 'error'', 'vendor/auth0/auth0-php/src/Auth0.php', '244', array('code' => '*******', 'auth_url' => 'https://*****.auth0.com/oauth/token/', 'response' => array('result' => 'Unauthorized', 'code' => '401', 'content_type' => false), 'auth0_response' => 'Unauthorized')) 

on /auth0/callback

**Comment by glena** [comment]
hi @vladimir-yuldashev 

can you replace this line (check under `vendor/php/auth0-php/src/Auth0.php`) https://github.com/auth0/auth0-PHP/blob/master/src/Auth0.php#L243

by `var_dump($response);var_dump($auth0_response);exit;`

I want to see what is it getting there.

**Comment by vladimir-yuldashev** [comment]
Auth0.php:243:
array (size=3)
  'result' => string 'Unauthorized' (length=12)
  'code' => int 401
  'content_type' => boolean false

string 'Unauthorized' (length=12)

**Comment by glena** [comment]
check if you have the correct client secret

**Comment by vladimir-yuldashev** [comment]
Double checked, it's correct.

**Comment by glena** [comment]
The only reason of this error is if either client id or secret are wrong.

If the redirect_url is not the same you used for the callback or the authorization code is not the correct one (or was previously used) it will return the proper error.

**Comment by vladimir-yuldashev** [comment]
redirect_url is the same

Downgrading from 3.2 to 3.0 now gives:

```
ApiException in Auth0.php line 248:
Invalid access_token - Retry login.
```

**Comment by glena** [comment]
can you create a ticket on support.auth0.com and send a zip with a snippet reproducing your issue (even your credentials, you can use a temporal application so you can later delete it and invalidate the client_id)?

**Comment by vladimir-yuldashev** [comment]
Okay

**Comment by vladimir-yuldashev** [comment]
No good feedback from them either.

I tried to get token by Postman. But 401 either. 
P.S. tokens are dev-only

![screen shot 2016-07-27 at 16 53 55](https://cloud.githubusercontent.com/assets/1809081/17177871/ec8308bc-541b-11e6-9afe-0ab55635f967.png)

**Comment by glena** [comment]
this redirect uri is wrong. It should be an URI, `http://domain.com/path`.

The rest looks good

**Comment by vladimir-yuldashev** [comment]
Same.

![screen shot 2016-07-27 at 17 17 27](https://cloud.githubusercontent.com/assets/1809081/17178388/03d42e4a-541e-11e6-90eb-db2401bd7ed7.png)

**Comment by glena** [comment]
but this redirect_uri is the same you used when you authenticate the user?
also, can you generate a new code and try again? make sure this code is not used

**Comment by vladimir-yuldashev** [comment]
@glena Yes, it's the same. Tried with new code. No result.

**Comment by glena** [comment]
what is the ticket number of the one you sent the code?

**Comment by vladimir-yuldashev** [comment]
12417

**Comment by glena** [comment]
can you send a zipfile with the code you are testing to that ticket?
do not throw it in the email body, it is imposible to follow.

**Comment by vladimir-yuldashev** [comment]
I can't do that because its part of the project. It does not even work for Postman.

**Comment by glena** [comment]
wait, in the ticket says your account is `http://misterio.eu.auth0.com` and in this screenshot it shows `http://misterio.auth0.com` you are setting the wrong domain

**Comment by vladimir-yuldashev** [comment]
@glena omg. So sooory I am so inattentive. Thank you!
