### ISSUE TITLE
v7.10.0 breaks permissions guards

### ISSUE THREAD

**Issue by vandarin** [auth0/laravel-auth0#424]
### Checklist

- [X] This can be reproduced using [the quickstart sample application](https://github.com/auth0-samples/laravel).
- [X] I have looked at [the README](https://github.com/auth0/laravel-auth0/#readme) and have not found a solution.
- [X] I have looked at [the `docs` directory](https://github.com/auth0/laravel-auth0/blob/main/docs) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/laravel-auth0/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/laravel) and have not found a solution.
- [X] I agree to uphold [the Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Laravel Version

10

### SDK Version

7.8

### PHP Version

PHP 8.2

### Description

After upgrading to 7.10.0, route guards using `->can()` and the `@can()` blade directive always return false.

I've narrowed it down to the additional call to clearSession in [CallbackControllerAbstract.php:133](https://github.com/auth0/laravel-auth0/blob/dca454830dd6edd7f211ae17878ddc8c4b3d3f9b/src/Controllers/CallbackControllerAbstract.php#L133).

The guards work properly after removing the call to clearSession or modifying it to clear all storage `$this->clearSession($guard, true, true, true)`. Clearing only transient & persistent storage (default) results in the session forgetting the list of permissions.

### How can we reproduce this issue?

Install the quickstart app as described in README, add `read:messages` permission to user. Visit http://localhost:8000/scope. It should report "You have `read:messages` permission, and can therefore access this resource.", instead I receive a "403 This action is unauthorized".

**Comment by evansims** [comment]
Hi @vandarin, thanks for reporting this! I'll look into this today

**Comment by evansims** [comment]
Hi @vandarin 👋 Thanks for reporting this. A fix has been merged to the development branch and a new release will be published this week containing it.
