### ISSUE TITLE
Name and Email values not set after call to management API, after adding User Repository

### ISSUE THREAD

**Issue by AndyMillerRadical** [auth0/laravel-auth0#425]
### Checklist

- [X] This can be reproduced using [the quickstart sample application](https://github.com/auth0-samples/laravel).
- [X] I have looked at [the README](https://github.com/auth0/laravel-auth0/#readme) and have not found a solution.
- [X] I have looked at [the `docs` directory](https://github.com/auth0/laravel-auth0/blob/main/docs) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/laravel-auth0/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/laravel) and have not found a solution.
- [X] I agree to uphold [the Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Laravel Version

10

### SDK Version

7.8

### PHP Version

PHP 8.2

### Description

PHP: 8.2.7 / Laravel 10.16.1 / Ubuntu 20.04.6 LTS

SDK installed with
```
composer require auth0/login:^7.8 --update-with-all-dependencies
php artisan vendor:publish --tag auth0
```
Context

I posted this in the Auth0 community and have been asked to post as an issue here. I'm not certain if it is an SDK issue or user error, as this is my first project with Auth0.

I have a FE React SPA App served by a PHP/Laravel Back End **API**. The same Back End also serves a simple Admin web App using Orchid Platform admin panels for Laravel as a regular Laravel **Web App**. This issue relates to the Back End.

The app is already in production with existing user base and I am working on a change to switch to Auth0 for IAM.

The new flow is: The SPA logs in via Auth0, receives an Access Token and includes the Token in API requests to the BE.

BE successfully validates the Token with Auth0 and I get the Auth0 ID "sub" and then allow access to protected routes defined in Routes/api.php

Next task is to associate Auth0 ID with existing user models (Eloquent ORM), as per sample Repository but with an extra check to match with existing DB email field if auth0_id hasn't been set in the DB yet.

The initial intended flow at this time will be:
1. check auth0 id "sub" matches a new auth0_id field added to users table in the DB.
2. if not, check if email matches existing user, and if found, update the auth_id field with the "sub" value. - This associates existing users with their new Auth0 Identity and gives them access to their existing data.
3. if not, add new user with available ID data from Auth0 management API. This will be the main flow for new users going forward.

I'm currently using the Auth0 React/Typescript sample SPA app as surrogate for the FE while working on getting the basic authentication for Back End access working..

Step 1  was to retrieve user data from the Auth0 management API as described at  [Backend Api Laravel API](https://auth0.com/docs/quickstart/backend/laravel) for which I added a route based on what the sample SPA app is calling:

```
Route::get('/messages/protected', function () {
    $user = auth()->id();
    $profile = cache()->get($user);
  
    if (null === $profile) {
      $endpoint = Auth0::management()->users();
      $profile = $endpoint->get($user);
      $profile = Auth0::json($profile);
  
      cache()->put($user, $profile, 120);
    }
  
    $name = $profile['name'] ?? 'Unknown';
    $email = $profile['email'] ?? 'Unknown';
  
    return response()->json([
      'name' => $name,
      'email' => $email,
      'user' => (array) auth()->user(),
    ]);
  })->middleware('auth');
```

This worked, returning both name and email correctly and the Auth0 version of a user, so I moved on to trying to add Auth0 to the Admin (Laravel Regular Web App) part of the BE following the instructions at [Regular Web App Laravel](https://auth0.com/docs/quickstart/webapp/laravel/interactive)

Next I wanted to integrate the [User Repository following the instructions here](https://github.com/auth0/laravel-auth0/blob/main/docs/Users.md) 

Nothing has gone well since then.

My repository is the same one from the docs:

```
<?php

declare(strict_types=1);

namespace App\Repositories;

use App\Models\User;
use Auth0\Laravel\{UserRepositoryAbstract, UserRepositoryContract};
use Illuminate\Contracts\Auth\Authenticatable;

final class UserRepository extends UserRepositoryAbstract implements UserRepositoryContract
{
    public function fromAccessToken(array $user): ?Authenticatable
    {
        $user = User::firstOrCreate([
            'auth0_id' => $user['sub'],
        ], [
            'name' => 'name',//$user['name'],
            'email' => 'email',//$user['email'],
            'email_verified' => 'email_verified',//$user['email_verified'],
        ]);

        return $user;
    }

    public function fromSession(array $user): ?Authenticatable
    {
        return User::where('auth0_id', $user['sub'])->first();
    }
}
```
The first thing that looked odd is my IDE (VS Code) does not recognise  UserRepositoryAbstract and UserRepositoryContract - Undefined types, but assuming that to be an IDE glitch I pressed on.

Initially, processing any request gave the error "The configured Repository App\Repositories\UserRepository could not be loaded "

I stopped and started the app with php artisan serve many times, and occasional php artisan config:clear

But could not get past this error.

But on returning to the project the following morning, (still loaded in the IDE) without any code changes (or forgotten saves), I no longer get this error. Now the UserRepository is loading (fromAccessToken) but failing with:

Error Undefined array key "name"

which relates to the line:

```
            'name' => 'name',//$user['name'],

``` 

above.

Also returning to the SPA app / API flow and the test route, name and email both now contain "Unknown" which seems to relate to the code in the '/messages/protected' route:

```
    $name = $profile['name'] ?? 'Unknown';
    $email = $profile['email'] ?? 'Unknown';

```

Both errors appear related to name and email now not being retrieved. Both from within the UserRepository (fromAccessToken) by whatever means the SDK uses to extract and pass that data to it, and now with in the API route, from the management API call.

Note, in the repository, after adding an auth0_id field to the database (the sample UserRepository assumes this field to exists although  nothing in steps I followed related to creating it, so I added my own migration to add it) and adding my Auth0 id ("sub") to my user record, and supplying dummy values for name, email and email_verified, it does successfully retrieve and return my User details from the database as a User object, which is good.

But without the expected user data (email, name) either being passed to the repository by the SDK, or accessible via a call to the management API, I am unable to associate the existing system users to their new Auth0 identities (by matching the email addresses), nor create new users in the database with sensible values for name, email, etc.

It seems that something in either the 'Regular web app Laravel' set up, or by adding UserRepository, has interfered with the name and email values being accessible in the either in repository (fromAccessToken) or from the management API. And I'm feeling a bit stumped for where to look for clues.  

Sorry for long message, but it all seems relevant.

composer.json
-------------

```
{
    "name": "myapp/be",
    "type": "project",
    "description": "MyApp Backend",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^8.2",
        "auth0/login": "^7.8",
        "aws/aws-sdk-php": "^3.273",
        "barryvdh/laravel-snappy": "^1.0",
        "doctrine/dbal": "^3.0",
        "guzzlehttp/guzzle": "^7.7",
        "h4cc/wkhtmltoimage-amd64": "0.12.4",
        "h4cc/wkhtmltopdf-amd64": "0.12.4",
        "laravel/framework": "^10.0",
        "laravel/sanctum": "^3.2",
        "laravel/socialite": "^5.6",
        "laravel/tinker": "^2.8",
        "laravel/ui": "^4.2",
        "markrogoyski/math-php": "^2.8",
        "orchid/icons": "^2.2",
        "orchid/platform": "^14.3",
        "socialiteproviders/google": "^4.1",
        "socialiteproviders/microsoft": "^4.2",
        "socialiteproviders/microsoft-graph": "^4.1",
        "spatie/laravel-server-side-rendering": "^1.4",
        "thomasjohnkane/snooze": "^2.3",
        "valorin/pwned-validator": "^1.3"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.13",
        "laravel/telescope": "^4.14",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9",
        "spatie/laravel-ignition": "^2.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "php-http/discovery": true
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
                "laravel/telescope"
            ]
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "@php artisan ide-helper:generate",
            "@php artisan ide-helper:meta"
        ]
    }
}
```

### How can we reproduce this issue?

The code is not publicly accessible but in brief the steps were

1) Follow guide for Laravel Backend API including using management API.

At this point, Authentication working, call to management API returns Auth0 user data.

2) Follow guide for Laravel Regular Web App
3) Follow guide for adding ORM based UserRepository

At this point, Authentication working. Call to UserRepository (fromAccessToken) does not include name, email, email_verified details, call to management API does not return name / email details.

**Comment by evansims** [comment]
Hi @AndyMillerRadical, thanks for your question!

> The first thing that looked odd is my IDE (VS Code) does not recognise UserRepositoryAbstract and UserRepositoryContract - Undefined types, but assuming that to be an IDE glitch I pressed on.

Your IDE's code intelligence probably doesn't support parsing PHP's grouped importing. I'd expect if you seperated the `use Auth0\Laravel\{UserRepositoryAbstract, UserRepositoryContract};` line into two distinct `use` lines your IDE would understand it. We use grouped imports extensively though, so you might want to consider using something like [Intelephense](https://intelephense.com), which does support it.

> I stopped and started the app with php artisan serve many times, and occasional php artisan config:clear

This wouldn't be an issue relating to the SDK.

For whatever reason, you class wasn't able to be loaded by Laravel, and Laravel happened to cache the error state. It worked when you came back to it the next morning because your application's cache expired. In the future, you can use Laravel's `php artisan optimize:clear` to fully clear all of your application's caches for a clean slate.

> Error Undefined array key "name"

The code you provided was:

```php
public function fromAccessToken(array $user): ?Authenticatable
{
    $user = User::firstOrCreate([
        'auth0_id' => $user['sub'],
    ], [
        'name' => 'name',//$user['name'],
        'email' => 'email',//$user['email'],
        'email_verified' => 'email_verified',//$user['email_verified'],
    ]);

    return $user;
}
```

Presumably you got this error when it was written as `'name' => $user['name'],` instead? That being the case, you're replacing `$user` as it was provided to the method (`fromAccessToken(array $user)`) with the return value of `User::firstOrCreate()`. You're manipulating an array as you're trying to read from it.

Otherwise, I'm not sure why it would give that particular error in that case, as there is no `name` being read here from any array.

> Also returning to the SPA app / API flow and the test route, name and email both now contain "Unknown" which seems to relate to the code in the '/messages/protected' route:

The code you provided was:

```php
Route::get('/messages/protected', function () {
  $user = auth()->id();
  $profile = cache()->get($user);

  if (null === $profile) {
    $endpoint = Auth0::management()->users();
    $profile = $endpoint->get($user);
    $profile = Auth0::json($profile);

    cache()->put($user, $profile, 120);
  }

  $name = $profile['name'] ?? 'Unknown';
  $email = $profile['email'] ?? 'Unknown';

  return response()->json([
    'name' => $name,
    'email' => $email,
    'user' => (array) auth()->user(),
  ]);
})->middleware('auth');
```

I would evaluate what is being stored in your cache. Call `dd($user, $profile)` before your `cache()->put()` call and see if the data structure is lining up with your expectations for reading it later.

This is a lot to try to grok at once, so apologies if I overlooked a question, but feel free to repeat it if so.

**Comment by AndyMillerRadical** [comment]
@evansims - Many thanks for reading and responding and the tips.

I appreciate it was a lot to grok. It's my first experience with Auth0 so I'm trying to take thing step by step to see how all the pieces fit together. I thought the sequence of configuring the App 

a) API server ('api')
b) Admin App ('web')
c) UserRepository

may have been material so wanted to provide the context, but perhaps too much!

The key issue for now is the UserRepository example:

```
<?php

declare(strict_types=1);

namespace App\Repositories;

use App\Models\User;
use Auth0\Laravel\{UserRepositoryAbstract, UserRepositoryContract};
use Illuminate\Contracts\Auth\Authenticatable;

final class UserRepository extends UserRepositoryAbstract implements UserRepositoryContract
{
    public function fromAccessToken(array $user): ?Authenticatable
    {
        $user = User::firstOrCreate([
            'auth0_id' => $user['sub'],
        ], [
            'name' => 'name',//$user['name'],
            'email' => 'email',//$user['email'],
            'email_verified' => 'email_verified',//$user['email_verified'],
        ]);

        return $user;
    }

    public function fromSession(array $user): ?Authenticatable
    {
        return User::where('auth0_id', $user['sub'])->first();
    }
}

```

Is failing with: Error Undefined array key "name", and I replaced $user['name'] with a dummy string for now.

My understanding of the UserRepository sample is that the passed in array should include the name and email, and I need these (email at least) for identifying existing users who have just logged in via Auth0 for the first time.

These existing users will already be in the database but with a null auth0_id value as this new field has just been added to the existing users table. The plan is to locate the user via the email, and then update the auth0_id field with the ['sub'] value (assuming the 'sub' value was not found).

I assume something I did while following the guide broke whatever is supplying the (array $user) to the repository public function fromAccessToken. There is no user code calling fromAccessToken so I assume it is being called automatically by the  Auth0 SDK, but without the name and email for some reason.

**Comment by AndyMillerRadical** [comment]
> Hey @AndyMillerRadical 👋 I provided a suggestion in my previous post regarding the undefined array question; did you give that a go?

Hey @evansims , thanks again. I'm not sure I'm following you point about the array.

The call to the Management API code in the '/messages/protected' api route was just an initial test taken from the [Retrieve User Information section of the Laravel API Quickstart](https://auth0.com/docs/quickstart/backend/laravel#retrieve-user-information).

Originally it was working, and auth()->id() returned a value of type 'auth0|xxxxxxxxxxxxxxxxxxx'. Since adding the UserRepository the ID is now the User record ID, eg 68. So I've put that to one side until I'm confident in what's happening the repository.

I don't think what I'm doing in that test route should impact what is being passed as '(array) $user' to the fromAccessToken() of the repository.

The UserRepository is taken from [this guide] (https://github.com/auth0/laravel-auth0/blob/main/docs/Users.md#creating-a-user-repository)

> Creating a User Repository
>
> Creating a repository is simple: it must implement the Auth0\Laravel\UserRepositoryContract interface, and include two methods:
>
> fromSession() to construct a model for an authenticated user.
> fromAccessToken to construct a model representing an access token request.
> 
> The following example repository uses Laravel's [Eloquent ORM](https://laravel.com/docs/eloquent) to store and retrieve users in a users table:

```
declare(strict_types=1);

namespace App\Repositories;

use App\Models\User;
use Auth0\Laravel\{UserRepositoryAbstract, UserRepositoryContract};
use Illuminate\Contracts\Auth\Authenticatable;

final class UserRepository extends UserRepositoryAbstract implements UserRepositoryContract
{
    public function fromAccessToken(array $user): ?Authenticatable
    {
        $user = User::firstOrCreate([
            'auth0_id' => $user['sub'],
        ], [
            'name' => $user['name'],
            'email' => $user['email'],
            'email_verified' => $user['email_verified'],
        ]);

        return $user;
    }

    public function fromSession(array $user): ?Authenticatable
    {
        return User::where('auth0_id', $user['sub'])->first();
    }
}
```

My assumption, based on the method names, is that this is called by the SDK to retrieve the authenticated user, and is supplying values '(array) $user' base on on the authenticated access token, and using those values to retrieve or create user based on the supplied values.

Are you suggesting there is a link between what is happing in the route '/messages/protected' and the '(array) $user' being passed to the repository?

Within the UserRepository, the code is as per the guide, but seems valid, $user will only be  replaced when the call to User::firstOrCreate returns, the 'name' => $user['name'] in the second parameter of that call will be using the $user as supplied to the fromAccessToken method.

The issue as it see it is that, based on the sample code the '(array) $user' should be getting supplied as something like:
{
"sub":"auth0|xxxxxxxxxxxxxxxxxxxxxxxx",
"name":"somename",
"email":"some email"
.....
}

but is coming in as:

{
"iss":"https:\/\/sometest-test.uk.auth0.com\/",
"sub":"auth0|xxxxxxxxxxxxxxxxxxxxxxxx",
"aud":["https:\/\/github.com\/auth0\/laravel-auth0",
"https:\/\/sometest-test.uk.auth0.com\/userinfo"],
"iat":1690965313,
"exp":1691051713,
"azp":"xxxxxxxxxxxxxxxxxxxxxxxxxx",
"scope":"openid profile email"
}

But are you saying, that what gets passes can be overridden by user code somewhere? 

One again, many thanks for helping.

**Comment by evansims** [comment]
Hi @AndyMillerRadical 👋

```
My assumption, based on the method names, is that this is called by the SDK to retrieve the authenticated user, and is supplying values '(array) $user' base on on the authenticated access token, and using those values to retrieve or create user based on the supplied values.
```

That's correct, this provides an interface for your application to create and retrieve matching users from a local database. By default the SDK does not persist user data to any local storage.

```
Are you suggesting there is a link between what is happing in the route '/messages/protected' and the '(array) $user' being passed to the repository?
```

No, I haven't suggested that

```
The issue as it see it is that, based on the sample code the '(array) $user' should be getting supplied as something like:
{
"sub":"auth0|xxxxxxxxxxxxxxxxxxxxxxxx",
"name":"somename",
"email":"some email"
.....
}

but is coming in as:

{
"iss":"https://sometest-test.uk.auth0.com/",
"sub":"auth0|xxxxxxxxxxxxxxxxxxxxxxxx",
"aud":["https://github.com/auth0/laravel-auth0",
"https://sometest-test.uk.auth0.com/userinfo"],
"iat":1690965313,
"exp":1691051713,
"azp":"xxxxxxxxxxxxxxxxxxxxxxxxxx",
"scope":"openid profile email"
}
```

The `fromAccessToken()` and `fromSession` methods both receive the complete payload of the ID or Access Token (respectively) that is returned by Auth0 during authentication, or as it is provided by the client for endpoint authorization.

The payload you're seeing is normal and expected. It is up to your application to adapt what is provided by the SDK to appropriately query (or create) the user records in your database based on this information. The `sub` should be enough to uniquely identify the user and look up a user from your table.

ID Tokens contain identify information, and include profile data like a name and email. Access Tokens are used exclusively for authorization, and do not include profile data. A "name" and "email" would never be contained within an access token under normal circumstances, unless you are using custom Actions/Rules to inject them. You can review the different between these token types and their purposes here: https://auth0.com/blog/id-token-access-token-what-is-the-difference/
