### ISSUE TITLE
Upgrading to 7.10 from 7.1 causing -  PHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 65536 bytes)

### ISSUE THREAD

**Issue by SukhrobNuraliev** [auth0/laravel-auth0#426]
### Checklist

- [X] This can be reproduced using [the quickstart sample application](https://github.com/auth0-samples/laravel).
- [X] I have looked at [the README](https://github.com/auth0/laravel-auth0/#readme) and have not found a solution.
- [X] I have looked at [the `docs` directory](https://github.com/auth0/laravel-auth0/blob/main/docs) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/laravel-auth0/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/laravel) and have not found a solution.
- [X] I agree to uphold [the Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Laravel Version

10

### SDK Version

7.8

### PHP Version

PHP 8.1

### Description

I'm having this error after upgrating to version 7.10 . in version 7.1 everything was working fine but it did not have multiple strategy use (web, api).

 WARN  PHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 65536 bytes) .... (some composer file)

I have telescope and nova installed. I think it is related to telescope issue.

### How can we reproduce this issue?

upgrade from 7.1 to latest (7.10)

**Comment by evansims** [comment]
Hi @SukhrobNuraliev 👋 I can't attest to Nova support at the moment; I have not tested this personally. Telescope does have compatibility issues, though I can't say if this is related to that or not.

The transition from 7.1 to 7.10 has seen significant internal changes, so I'm afraid I don't have a silver bullet for you. However, you can try:

- Try disabling Telescope and/or following [the guidance here](https://github.com/auth0/laravel-auth0/issues/412) as a workaround.
- Check your PHP and Laravel logs to see if anything is being reported.
- Try using XDebug or [Ray](https://myray.app) and see if any errors are captured
- You could try iteratively upgrading from 7.1 to 7.2, then 7.3, then 7.4.
- Be sure to read [the release notes](https://github.com/auth0/laravel-auth0/releases) to identify any potential integration changes you might need to address.
- Check if [the quickstart runs for you](https://github.com/auth0-samples/laravel); if so, recreate the integration provided there in your application.
