### ISSUE TITLE
7.7+ integration questions

### ISSUE THREAD

**Issue by watercayman** [auth0/laravel-auth0#427]
### Checklist

- [X] This can be reproduced using [the quickstart sample application](https://github.com/auth0-samples/laravel).
- [X] I have looked at [the README](https://github.com/auth0/laravel-auth0/#readme) and have not found a solution.
- [X] I have looked at [the `docs` directory](https://github.com/auth0/laravel-auth0/blob/main/docs) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/laravel-auth0/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/laravel) and have not found a solution.
- [X] I agree to uphold [the Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Laravel Version

10

### SDK Version

7.8

### PHP Version

PHP 8.2

### Description

I upgraded from 7.7 to 7.10 and can no longer use the application.

- I had been extending middleware \Auth0\Laravel\Http\Middleware\MiddlewareAbstract, but this file has been deleted.  
-  Based on the comment note left in the Auth0 file, i changed this to \Auth0\Laravel\Guards\AuthenticationGuard::class
- My custom user repository implemented \Auth0\Laravel\Contract\Auth\User\Repository but this file is now gone.
- Based on the issue reported by another user and the changes to the quick start I changed this to: class CustomUserRepository extends UserRepositoryAbstract implements UserRepositoryContract

Now I'm faced with a new error that prevents the app from running:

- Declaration of Illuminate\Database\Eloquent\Model::__get($key) must be compatible with Auth0\Laravel\Users\UserContract::__get(string $key): mixed

I appreciate that there may be more information out there, but I am having a hard time justifying the time and cost involved in coming back to research breaking changes on even minor versions of this library.  

I'm incredibly appreciative of the work done on this, as well as @evansims quick responses.  But I don't understand why I keep needing to refactor for this library so many times, even in the middle of a major version.  

If I'm doing something very wrong, please let me know, so I can correct it.  

Please let me know how to fix the above errors following this upgrade.

### How can we reproduce this issue?

Upgrade from 7.7 to 7.10 with a custom user repository based on the previous quick start guide.

**Comment by evansims** [comment]
Hey @watercayman 👋 Thanks for your question.

> I had been extending middleware \Auth0\Laravel\Http\Middleware\MiddlewareAbstract, but this file has been deleted.

This [has not been deleted](https://github.com/auth0/laravel-auth0/blob/main/src/Middleware/MiddlewareAbstract.php). Its namespace was updated to accommodate other changes. It now exists under `Auth0\Laravel\Middleware\MiddlewareAbstract`. This is an internal API and not intended to be extended by applications.

> Based on the comment note left in the Auth0 file, i changed this to \Auth0\Laravel\Guards\AuthenticationGuard::class

This was not a requirement, simply a deprecation notice. `Auth0\Laravel\Auth\Guard` still exists and remains functional.

> My custom user repository implemented \Auth0\Laravel\Contract\Auth\User\Repository but this file is now gone.

This [has not been deleted](https://github.com/auth0/laravel-auth0/blob/main/deprecated/Contract/Auth/User/Repository.php).

> Based on the issue reported by another user and the changes to the quick start I changed this to: class CustomUserRepository extends UserRepositoryAbstract implements UserRepositoryContract

There have been no issues relating directly to `Auth0\Laravel\Contract\Auth\User\Repository`. As `Auth0\Laravel\Contract\Auth\User\Repository` extends the newer `UserRepositoryContract` directly, you're free to use either implementation.

> Declaration of Illuminate\Database\Eloquent\Model::__get($key) must be compatible with Auth0\Laravel\Users\UserContract::__get(string $key): mixed

The `UserContract` interface included with the SDK isn't presently designed to work with Eloquent out of the box. This has never changed. User models must inherit the `Illuminate\Contracts\Auth\Authenticatable` interface, which is a requirement of the framework.

> I appreciate that there may be more information out there, but I am having a hard time justifying the time and cost involved in coming back to research breaking changes on even minor versions of this library.

I do sincerely apologize for any integration challenges you've faced; as I've noted above, there has not been anything that would be considered a breaking change.

**Comment by watercayman** [comment]
Thank you for the quick response, @evansims.

I see that the User Repo class was not removed - my IDE was showing depreciated, my mistake - my apologies.

I have attempted to implement the changes to the user model and am not having success.  I think this may be beyond my skillset for now, and may have to remain on v7.7, which was working fine.

Changing to the recommended User class declaration using the quick start guide seems to now conflict with several expected methods from the Laravel User model now.  For example, using the spatie media library, I am getting an error:
  `Cannot access "parent" when current class scope has no parent` inside a sleep function.  

If I remove the entire spatie library, I get another, similar error from a different library.  Removing that library, i then get 
  `Auth guard [auth0-session] is not defined.`

I had previously used 
  ```
use Illuminate\Foundation\Auth\User as Authenticatable;
  use Auth0\Laravel\Contract\Model\Stateful\User as StatefulUser;
```

And this worked fine with v7.7 on all aspects.  

I'm not sure where to go from here if changing the above is going to cause new issues.  My apologies, this is a bit beyond my understanding of what's under the hood for these classes.  I've relearned with each update, but I'm not sure I'm going to be able to bring this back to life, looking at the cascade of issues that seem to be coming with the changes I'm trying to implement.

**Comment by BryanMorgan** [comment]
I have the same issue when trying to create an Eloquent User Model. When extending `Illuminate\Foundation\Auth\User ` I get:

```
Declaration of Illuminate\Database\Eloquent\Model::__get($key) must be compatible with 
Auth0\Laravel\Users\UserContract::__get(string $key): mixed
```

The solution is already solved in the [https://github.com/auth0/laravel-auth0/pull/416](https://github.com/auth0/laravel-auth0/pull/416) pull request. Is that something that's planned soon?

**Comment by evansims** [comment]
Hi @watercayman 👋 

> I have attempted to implement the changes to the user model and am not having success. I think this may be beyond my skillset for now, and may have to remain on v7.7, which was working fine.

Aside from some minor and entirely optional namespace changes (previous namespaces still work, but are marked as deprecated) there were no changes to how user models work between 7.1 and 7.7.

> Changing to the recommended User class declaration using the quick start guide seems to now conflict with several expected methods from the Laravel User model now. For example, using the spatie media library, I am getting an error:
Cannot access "parent" when current class scope has no parent inside a sleep function.

I'm afraid we can't provide support for third party libraries; the SDK does not do anything unique or special that should introduce compatibility issues, however.

> If I remove the entire spatie library, I get another, similar error from a different library. Removing that library, i then get
Auth guard [auth0-session] is not defined.

If you're receiving that error, it doesn't sound like the SDK's Guard(s) are/is being loaded at all within your application. You may need to review the [README](https://github.com/auth0/laravel-auth0/blob/main/README.md) and follow the steps to ensure you have fully integrated the SDK appropriately.

> I had previously used
> use Illuminate\Foundation\Auth\User as Authenticatable;
> use Auth0\Laravel\Contract\Model\Stateful\User as StatefulUser;

Guidance is to implement the `Illuminate\Contracts\Auth\Authenticatable` interface directly, not `Illuminate\Foundation\Auth\User as Authenticatable`. This could have unforeseeable side effects.

> I'm not sure where to go from here if changing the above is going to cause new issues. My apologies, this is a bit beyond my understanding of what's under the hood for these classes. I've relearned with each update, but I'm not sure I'm going to be able to bring this back to life, looking at the cascade of issues that seem to be coming with the changes I'm trying to implement.

Again I do apologize for any challenges you're facing but as I said no breaking changes were introduced between the versions you mentioned, however I have pointed out a number of integration issues that are contrary to our guidance. If you simply address these I fully expect you'll be up and running and working just fine through future updates.
