### ISSUE TITLE
Auth0Service class should have properties at the top

### ISSUE THREAD

**Issue by seanmangar** [auth0/laravel-auth0#43]
I'm not sure if there is a convention/coding style for this project, but generally it would be a good idea to move all properties to the top. This is a convention, albeit not explicitly a PSR-2 (http://www.php-fig.org/psr/psr-2/) one. I can see they are interspersed throughout the Auth0Service file.

I can fix these and submit a pull request.

**Comment by seanmangar** [comment]
@glena Any feedback on this?

**Comment by glena** [comment]
I tracked this, but it is low prio right now. PR are always welcome :)

**Comment by cocojoe** [comment]
I am going to close, lack of activity and see no associated PR.  Sean if this is still an issue and you would like to submit a PR for 5.x this would be most welcome.
