### ISSUE TITLE
Restore 7.6 feature of configurable login route

### ISSUE THREAD

**Issue by Tamrael** [auth0/laravel-auth0#432]
### Checklist

- [X] This can be reproduced using [the quickstart sample application](https://github.com/auth0-samples/laravel).
- [X] I have looked at [the README](https://github.com/auth0/laravel-auth0/#readme) and have not found a solution.
- [X] I have looked at [the `docs` directory](https://github.com/auth0/laravel-auth0/blob/main/docs) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/laravel-auth0/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/laravel) and have not found a solution.
- [X] I agree to uphold [the Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Laravel Version

10

### SDK Version

7.8

### PHP Version

PHP 8.2

### Description

On 7.6 we could configure our own route for login: https://github.com/auth0/laravel-auth0/blob/e299f3eedb66b8c593d15f3bf9871a8b55ec625b/src/Http/Middleware/Stateful/Authenticate.php#L52

With 7.8 that config option was removed: https://github.com/auth0/laravel-auth0/blob/ce5994fce4f0ea0e058d031fbfe06187a13598e3/src/Middleware/AuthenticateMiddlewareAbstract.php#L51

as our target system is using "/auth/login" instead of "/login" we NEED this configuration variable.
We could duplicate the whole middleware but we would really like to just use the base auth0 file.
Can we have the configuration back please?

### How can we reproduce this issue?

try to use any other path for the login routes other then default "/login"

**Comment by evansims** [comment]
Hi @Tamrael 👋 Thanks for your suggestion. This was removed as it introduced confusion being included in the default configuration alongside the default auto-registered routes feature — but, I completely sympathize with your desire on this, and I agree it would be a waste to duplicate the middleware just for that purpose. I'll think on this for a few and get back to you.

**Comment by Tamrael** [comment]
@evansims thank you for considering it <3
Let me know if I can help you with anything.
Looking forward to your decision.

**Comment by Tamrael** [comment]
thank you <3 I'll try to update to this implementation asap
