### ISSUE TITLE
error with login

### ISSUE THREAD

**Issue by Amialc** [auth0/laravel-auth0#44]
As you can see at [screencast](https://webmshare.com/play/mxzoJ), after login with Twitter, it simply does nothing. I've reproduced bug with sample project and with project build using [auth0 tutorial](https://auth0.com/docs/quickstart/webapp/laravel).

**Comment by glena** [comment]
Are you using your own twitter application or is it the default auth0 uses when you are developing?

can you upload a har file? https://auth0.com/docs/har

And which is your account name? can you share your auth0 domain?

**Comment by Amialc** [comment]
I'm using my own twitter app.
I've logged in through twitter app then logout and logged in through facebook and got nothing still. [Here is HAR file for this](https://drive.google.com/file/d/0B233eIkPqGXJaVV5aVhZamQwa1E/view?usp=sharing).

**Comment by glena** [comment]
So the issue is not with twitter, but the second time you try to login?

**Comment by Amialc** [comment]
Yes, seems like that is the problem. 
Tried to login google, logout and login through facebook, same issue. But in logs all ok.
![image](https://cloud.githubusercontent.com/assets/1114365/17594905/8e3ecd66-5ff3-11e6-9de2-460a5fdbc1af.png)

**Comment by glena** [comment]
yeah, and the har file shows that it worked fine, but for some reason laravel is messing up the session...

if you can share the code for me to debug would be really helpful

**Comment by Amialc** [comment]
I have just downloaded [seed project](https://auth0.com/docs/quickstart/webapp/laravel) and tested it. Seed project is affected too.

**Comment by glena** [comment]
ok will use that then. thx

**Comment by glena** [comment]
I just tried and worked fine... it is really odd.

Check this capture, the first user is logged in using facebook (it will show an auth0 id because it is linked to a database user). The second one is using twitter.

![demo](https://cloud.githubusercontent.com/assets/5647310/17632376/6200bc04-609e-11e6-8693-86ca8ddca4d6.gif)

**Comment by Amialc** [comment]
We have tested different seed projects because of [this commit](https://github.com/auth0/docs/commit/8f7422d59d6d87060b742348e8ecd5b84c823d56#diff-673cc728ed00f2ec63f9bc141eafb2e9). Both projects redirects you to `http://localhost:8000/#_=_` after second login, but in new seed project you need to click on button `dump` and than you see. I can confirm that bug is not reproducible in new seed project.

**Comment by cocojoe** [comment]
This should be working, I've tested in latest sample started seed project https://github.com/auth0-samples/auth0-laravel-php-web-app/tree/master/00-Starter-Seed
Please re-open a new issue if this is still an issue Thx
