### ISSUE TITLE
Trigger a password reset email

### ISSUE THREAD

**Issue by nicosalvadore** [auth0/laravel-auth0#449]
### Checklist

- [X] I agree to uphold [the Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello,

I'd like to trigger a password reset email as described in this doc : https://auth0.com/docs/authenticate/database-connections/password-change#authentication-api

As far as I know, this endpoint is not exposed through this `laravel-auth0` SDK.
Is this correct ?

Thanks in advance :)

**Comment by evansims** [comment]
Hi @nicosalvadore

For that, you'd need to interact with the underlying [Auth0 PHP SDK](https://github.com/auth0/auth0-PHP), which is the foundation of the Auth0 Laravel SDK.

You can retrieve an instance of the Auth0 PHP SDK from the Auth0 Laravel SDK like this:

```php
use Auth0\Laravel\Facade\Auth0;

$sdk = Auth0::getSdk();
```

You could then access the Authentication API class, and use the `dbConnectionsChangePassword()` method:

```php
$sdk->authentication()->dbConnectionsChangePassword(
    email: [string],
    connection: [string],
    body: [array],
    headers: [array],
);
```

By the way, for general integration questions, your best route is the Auth0 Community: https://community.auth0.com

**Comment by nicosalvadore** [comment]
Thank @evansims for your answer.
Your solution is working perfectly :)
