### ISSUE TITLE
InvalidTokenException "The JWT string must contain two dots" when decoding token for regular (non-API) applications (with AUTH0_AUDIENCE=[blank])

### ISSUE THREAD

**Issue by miking7** [auth0/laravel-auth0#454]
### Checklist

- [X] I agree to uphold [the Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Please note: the bug-report template is currently broken, so I had to submit this issue via the only available "Suggest a Feature" issue template.

### The Issue:

While updating our Laravel (v10) applications from v7.6 to v7.12 of the SDK, we discovered a potential problem with the SDK (+ hack) that we wanted to flag for other users.  (This issue appears to have been introduced during the major changes in v7.8)

In terms of authentication, our applications are traditional web applications (not backend APIs), and we were surprised that the new [QuickStart](https://auth0.com/docs/quickstart/webapp/laravel) says *"You should also create a new API"*.  However we tested both approaches (**with** and **without** API credentials) and found the following:

* **With** API credentials, our applications work with the new SDK, **but** the Auth0 login flow includes an additional step where users have to authorise the API (once).  This additional step feels quite strange for a regular web application (as though users are trying to authenticate a mobile app), and we don't really want to go down this path.
* **Without** API credentials, the login completes normally, **but** the new SDK throws an exception **InvalidTokenException - *"The JWT string must contain two dots"*** on return to the _/callback_ route.

### Digging Deeper:

From debugging the SDK and reading documention and forums we learned:

* **Without** API credentials (ie the *audience* parameter is blank), Auth0 defaults to using your *userinfo* endpoint... and issues an *opaque token*.  (See [this article](https://community.auth0.com/t/what-is-the-audience/71414) for a helpful explanation)
* To the best of our understanding, the problem seems to be that the SDK is not capable of properly handling an *opaque* token. 
* The exception is thrown in `Token\Parser.php` -> `parse()` when a token is exploded that is meant to be a 3-part JWT.  Opaque tokens result in an invalid 5-part 'token' being passed to this function instead in some situations.
* Further debugging narrowed the issue down to `Guards\AuthenticationGuard.php` -> `pullState()`.  When using the SDK **without** API credentials, the credentials returned by `$credentials = $sdk->getCredentials();` are in two different formats.  Both contain a JWT, but in some cases (ie apparently when dealing with an opaque token) the valid JWT is not available in `$credentials->accessToken` but instead in the `$credentials->idToken`.

### Temporary Solution / Hack:

To be honest we don't completely understand what's going on in the SDK codebase, but the following **hack** to the `pullState()` function is working for us.  (We've implemented this as a temporarily patch in our projects):

```diff
if (null !== $credentials->accessToken) {
+   // Use the access token if it is a JWT, otherwise use the ID token
+   $accessTokenIsJwt = (3 == count(explode('.', $credentials->accessToken)));
+   $jwt = $accessTokenIsJwt ? $credentials->accessToken : $credentials->idToken;
+   $decoded = (new Parser(new SdkConfiguration(strategy: SdkConfiguration::STRATEGY_NONE), $jwt))->export();
-   $decoded = (new Parser(new SdkConfiguration(strategy: SdkConfiguration::STRATEGY_NONE), $credentials->accessToken))->export();
}
```

I'm hopeful that a better solution may be available, or that we've missed something simple, but having spent a couple of days trying to get to the bottom of this we wanted to document our issues for the benefit of others searching for solutions for the same symptoms.

### Additional Notes:

* During initial testing we initially followed the Auth0-preferred [configuration method](https://github.com/auth0/laravel-auth0/blob/main/docs/Configuration.md#sdk-configuration) using JSON files exported from the Auth0 CLI, but the results were the same when we switched back to an `.env` file-based configuration that we prefer.  

* When using JSON config files, an `auth0.app.json` file is present for both scenarios, and an `auth0.api.json` is added when testing scenarios "**with** API credentials".

* When using `.env` to configure the SDK we commented/uncommented the `AUTH0_AUDIENCE=` line to enable/disable the API credential - ie:

    ```bash
    AUTH0_DOMAIN=XXXX.au.auth0.com
    AUTH0_CLIENT_ID=XXXX
    AUTH0_CLIENT_SECRET=XXXX
    # AUTH0_AUDIENCE=https://XXXX.com
    ```

**Comment by evansims** [comment]
Hi @miking7, thanks for your suggestion. You are exactly correct; the audience is required for the Laravel SDK — even those configured to use the `web` (authentication) guard — to avoid receiving [opaque access tokens](https://auth0.com/docs/secure/tokens/access-tokens), which are not supported for authorization requests. Your workaround is indeed a solution, but it is not something we can adopt at this time, as this approach will most definitely have unintended side effects.

However, it's worth noting, you're able to override that authorization prompt you get authentication by simply turning on "allow skipping user consent" in your API configuration under Access Settings.

<img width="559" alt="image" src="https://github.com/auth0/laravel-auth0/assets/3093/104e6eb5-2ee1-4094-8a7f-c4445cd67bcc">

**Comment by miking7** [comment]
Thanks for explaining this @evansims - I will test the "allow skipping user consent" API option as a workaround for our applications.  (I agree, our solution is definitely a "hack" and I appreciate it will have unintended side effects although thankfully we haven't hit them yet. 🙂)

Can you help me understand one thing though - is the current lack of capability for the Laravel Auth0 SDK to work correctly unless an API is registered related to the complexity that would have been required to implement this in a library that is also trying to provide built-in support for authorization?  

(Our applications use Auth0 for authentication (AuthN) but not authorization (AuthZ), and I'm just trying to understand if this was a practical implementation constraint for the Laravel SDK based on limited resources, VS a broader strategic direction-shift we should be adopting to when using Auth0 for AuthN outside of the Laravel Auth0 SDK?)

**Comment by evansims** [comment]
👋 Just strictly an implementation constraint right now due to some legacy requirements of the underlying PHP SDK. Aiming to remove that constraint in v9 of that SDK, and then it won't be a necessity downstream in this SDK.
