### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by pieterhielkema** [auth0/laravel-auth0#463]
### Checklist

- [X] I agree to uphold [the Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We use Laravel 11 at Mediahuis, so would love if this would work as well :)

**Comment by parallels999** [comment]
- https://github.com/auth0/laravel-auth0/pull/445

**Comment by evansims** [comment]
Laravel 11 support has been available since SDK v7.13
