### ISSUE TITLE
Auth0UserRepository name is already in use

### ISSUE THREAD

**Issue by Amialc** [auth0/laravel-auth0#51]
I've tried to run [laravel-api sample](https://github.com/auth0-samples/auth0-laravel-php-web-api) and got this:
![image](https://cloud.githubusercontent.com/assets/1114365/18615659/f3d1b574-7db4-11e6-9a6e-843705e9c214.png)
![image](https://cloud.githubusercontent.com/assets/1114365/18615654/dbfcb30e-7db4-11e6-9c5a-a17d09740278.png)

**Comment by glena** [comment]
Fixed in `4.0.1`
