### ISSUE TITLE
Support for Laravel 5?

### ISSUE THREAD

**Issue by drock07** [auth0/laravel-auth0#6]
Do you plan on supporting Laravel 5? If so, how soon? 

I think the biggest change would be converting the filters into middleware.

**Comment by jonathan-bird** [comment]
+1

**Comment by drock07** [comment]
So, the filters could still work with Laravel 5, so I think the only obstacle to using this library is that it depends on Laravel 4 and throws an error when the version isn't 4.*.*

**Comment by jonathan-bird** [comment]
Might be worth making a fork and changing to laravel 5 as dependency if no updates soon.

**Comment by drock07** [comment]
Good idea. Will do.

**Comment by moltar** [comment]
+1 on this, please fix very useful

**Comment by glena** [comment]
Hi,

we have released the v2.0.0 with support for Laravel 5.

https://github.com/auth0/laravel-auth0/releases/tag/2.0.0

Let me know if you have any question!
