### ISSUE TITLE
Add RS256 to the list of supported algorithms

### ISSUE THREAD

**Issue by indiealexh** [auth0/laravel-auth0#62]
By default the JWTVerifier uses only HS256 unless overridden by the arguments provided in Auth0Service.

RS256 is now the default when creating an API in the Auth0 Interface and the [quickstart documentation](https://auth0.com/docs/quickstart/backend/php-laravel) does not mention the need to use HS256.

To rectify this I propose either adding RS256 to the support_algs config, or adding an option to add it in the laravel-auth0 config file.

Pull Request for proposed fix: #63

**Comment by ryanstelmat** [comment]
I'd like to see this PR get pushed through as well. Out of the box Auth0 seems to use HS256.

**Comment by ryantology** [comment]
Should be closed based on #65

**Comment by cocojoe** [comment]
Closing as support added as linked in last comment. Thx
