### ISSUE TITLE
Error with Laravel 5.4

### ISSUE THREAD

**Issue by achegedus** [auth0/laravel-auth0#67]
I was running fine with 5.3, but since I upgraded, I'm now getting this error when I try to use the auth0.jwt middleware:

`BindingResolutionException in Container.php line 804:
Target [Auth0\Login\Contract\Auth0UserRepository] is not instantiable while building [\Auth0\Login\Middleware\Auth0JWTMiddleware].`

Any ideas on what's up, or a plan to support 5.4?

**Comment by glena** [comment]
It will support 5.4, not ETA yet.

Didnt check the changelog yet, but seems that something changed with the DI bindings, are you bingding `Auth0\Login\Contract\Auth0UserRepository` to the actual implementation

```
    $this->app->bind(
        '\Auth0\Login\Contract\Auth0UserRepository',
        '\Auth0\Login\Repository\Auth0UserRepository');
```

**Comment by glena** [comment]
Update, it might be related to https://laravel.com/docs/5.4/upgrade, check the `Binding Classes With Leading Slashes` section.
