### ISSUE TITLE
Improvements for Laravel 5.4

### ISSUE THREAD

**Issue by glena** [auth0/laravel-auth0#68]
Related to #67 

We need to check the migration guide and make sure that there is no breaking change: https://laravel.com/docs/5.4/upgrade#container

- Exceptions rename
- Middleware changes
- Session changes, does it impact in the plugin?
- Check if we can add value from Gate and policies (under Authorization section)

We also need to update the docs:
- change bindings
- check if there are any note that needs to be changed
- update version of the quickstart

**Comment by c0h1b4** [comment]
Any updates?

**Comment by glena** [comment]
it should work right away as it is. the only posible issue might be the Binding Classes With Leading Slashes section.

https://laravel.com/docs/5.4/upgrade

This issue is mostly for improvements based on the new features

**Comment by m1guelpf** [comment]
See #91 for a 5.5 improvement :smile:

**Comment by dmyers** [comment]
Maybe it would also be good to change the config file from `laravel-auth0` to just `auth0`? It's cleaner and the `laravel` prefix is redundant since it's a Laravel app.

**Comment by joshcanhelp** [comment]
Thanks for the feedback and PRs everyone. We'll review all this internally and look towards a major release in the near future.
