### ISSUE TITLE
Problem with the intallation in laravel 5.2

### ISSUE THREAD

**Issue by UltraWeb** [auth0/laravel-auth0#72]
I am try to install this package with composer, but i am get this error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install auth0/login 5.0.1
    - Conclusion: remove guzzlehttp/guzzle 5.3.1
    - Installation request for auth0/login ~5.0 -> satisfiable by auth0/login[5.0.0, 5.0.1].
    - Conclusion: don't install guzzlehttp/guzzle 5.3.1
    - auth0/login 5.0.0 requires auth0/auth0-php ^5.0.0 -> satisfiable by auth0/auth0-php[5.0.0, 5.0.1, 5.0.2, 5.0.3].
    - auth0/auth0-php 5.0.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3].
    - auth0/auth0-php 5.0.1 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3].
    - auth0/auth0-php 5.0.2 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3].
    - auth0/auth0-php 5.0.3 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3].
    - Can only install one of: guzzlehttp/guzzle[6.0.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.2, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.1.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.1.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.2, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.3, 5.3.1].
    - Installation request for guzzlehttp/guzzle (locked at 5.3.1) -> satisfiable by guzzlehttp/guzzle[5.3.1].

Installation failed, reverting ./composer.json to its original content.

How i can resolve this?

**Comment by cocojoe** [comment]
Should not be an issue in 5.x certainly from my own testing. Suggest you try latest, if you have a problem please create a new issue. Thx
