### ISSUE TITLE
Increasing Session Timeout

### ISSUE THREAD

**Issue by jaga-me** [auth0/laravel-auth0#73]
how do we increase the session timeout? I have already set the timeout lifetime in config/session.php but it doesn't seem to be working well

**Comment by cocojoe** [comment]
Isn't this a Lavarel issue? https://laracasts.com/discuss/channels/laravel/session-time-out-n-laravel-51

**Comment by joshcanhelp** [comment]
@jaga-me - Apologies for the long delay here. What might be a little confusing when using this package is that there are, technically, 3 sessions that are happening:

- The Laravel session, which is controlled in the config file you mentioned
- The Auth-PHP SDK session, which is held in the generic PHP session
- The session at Auth0

The Auth0-PHP SDK sets a default value for the session cookie, which might be overwriting the Laravel one, so setting the session only in in the session config might not get through. Try adding the following to `config/laravel-auth0.php`:

```php
return array(

    // Other settings ...

    'session_cookie_expires'        => 2628000, // Value desired, in seconds
);
```
