### ISSUE TITLE
Scope configuration

### ISSUE THREAD

**Issue by a-kinder** [auth0/laravel-auth0#81]
The readme specifies that the name/email scope should be requested for a user, and indeed that should be a value that should be configurable but there doesn't seem to be a spot to do this. The default scope is 'openid'. Adding 'scope' as an array value in the auth0 config file doesn't seem to work.

**Comment by cocojoe** [comment]
You can specify when you call `login()`  https://github.com/auth0/laravel-auth0/blob/master/src/Auth0/Login/Auth0Service.php#L54
