### ISSUE TITLE
5.5 fresh - fails to login

### ISSUE THREAD

**Issue by johnstontrav** [auth0/laravel-auth0#82]
same error on fresh install of 5.5 and 00-starter-seed.zip package.

5.5:
<img width="1431" alt="whoops__there_was_an_error_" src="https://user-images.githubusercontent.com/7200330/30357664-31897c00-9883-11e7-9f98-10559636be06.png">

starter-seed:
<img width="1010" alt="auth0-laravel_dev_callback_code_av_5zaghwly07ze6" src="https://user-images.githubusercontent.com/7200330/30357678-4e3bd4c4-9883-11e7-9f93-f639437b4f19.png">

I have verified the login was successful via auth0 dashboard and logs.

Anyone help would be great!

Cheers,
Trav

**Comment by johnstontrav** [comment]
I manage to resolve this issue.  I need to add the scope in the login method:

`return \App::make('auth0')->login(null,null,['scope' => 'openid profile']);`

**Comment by cocojoe** [comment]
@johnstontrav thanks, ran into this myself.  Have patched the sample started seed project and have raised a PR for this #83
