### ISSUE TITLE
404 Error on API-Call

### ISSUE THREAD

**Issue by Matschick** [auth0/laravel-auth0#86]
I´m using Laravel 5.5 and"auth0/login": "~5.0". I try to secure my API with Auth0.

Problem: I run into "404 Page not found" after a API call.

I install the plugin with this tutorial direct from auth0. Maybe my configuration is not correct especially the redirect url. This is my currently configuration

```
domain: geezee.eu.auth0.com
client_id: ***
client_secret: ***
redirect_uri: http://myurl.de/auth0/callback
api_identifier: http://www.myurl.de/api/v1/
suported_algs: ['RS256']
```
I have no route for callback.

**Comment by joshcanhelp** [comment]
@Matschick - Apologies for the delay in response here. 

This package is mostly used for logging into Laravel, not API authentication. That said, it does include the Auth0-PHP SDK, which can be used for this purpose. You can just include that directly or continue to use this package but follow the steps here for API securing:

https://auth0.com/docs/quickstart/backend/php/01-authorization
