### ISSUE TITLE
Support single sign on with an SSO middleware or otherwise

### ISSUE THREAD

**Issue by andzandz** [auth0/laravel-auth0#87]
This respository's README.md states

![image](https://user-images.githubusercontent.com/13456494/32887652-8c724014-cabc-11e7-8f12-39e90a48c7cb.png)

The Laravel-specific documentation page https://auth0.com/docs/quickstart/webapp/laravel/01-login ends when you have a simple login set up, not SSO.

While trying to implement single sign on with Auth0 between two sites on two domains, from reading the Silent Login page https://auth0.com/docs/api-auth/tutorials/silent-authentication, I noticed

![image](https://user-images.githubusercontent.com/13456494/32887707-cc62fff6-cabc-11e7-82c5-bb1c0e495a4c.png)

The standard example login route with this package is

```php
Route::get('/login', function() {
    return \App::make('auth0')->login(null, null, ['scope' => 'openid profile email'], 'code');
});
```

I have figured out that I can create this, for a silent login route:

```php
Route::get('/login_silent', function() {
    return \App::make('auth0')->login(null, null, ['scope' => 'openid profile email', 'prompt' => 'none'], 'code');
});
```

After logging in on my first site, navigating to this route on my second site logs me in nicely, by performing the redirect to Auth0, then redirecting back to my second site.

To implement a full single sign-on solution (the user is automatically logged in when browsing to the second site without clicking anything), we need to perform the silent login redirect on their first page load, and then

* If they have logged in on another site configured with single sign on, log them in and redirect back

* If they are not already logged in: do nothing and redirect back to the original site, not logged in

**I don't see a way to cover the second case with this package; when the user is not logged in yet.**

After a login attempt (prompt or silent), Auth0 redirects to this route:

```php
Route::get('/auth0/callback', '\Auth0\Login\Auth0Controller@callback');
```

Looking at Auth0Controller:

```php
public function callback()
    {
        // Get a handle of the Auth0 service (we don't know if it has an alias)
        $service = \App::make('auth0');

        // Try to get the user information
        $profile = $service->getUser();

        // Get the user related to the profile
        $auth0User = $this->userRepository->getUserByUserInfo($profile);

        if ($auth0User) {
            // If we have a user, we are going to log him in, but if
            // there is an onLogin defined we need to allow the Laravel developer
            // to implement the user as he wants an also let him store it.
            if ($service->hasOnLogin()) {
                $user = $service->callOnLogin($auth0User);
            } else {
                // If not, the user will be fine
                $user = $auth0User;
            }
            \Auth::login($user, $service->rememberUser());
        }

        return \Redirect::intended('/');
    }
```

According to https://auth0.com/docs/api-auth/tutorials/silent-authentication:

![image](https://user-images.githubusercontent.com/13456494/32888211-6af79748-cabe-11e7-8691-d909642927d2.png)

The `errors` (or state of $auth0User) we need are lost after this redirect at the end of the Auth0Controller callback() function.

I thought about trying this:

```php
Route::get('/', function() {
    if(!Auth::check()) {
        return \App::make('auth0')->login(null, null, ['scope' => 'openid profile email', 'prompt' => 'none'], 'code');
    }

    return view('home');
});
```

But if the user isn't logged in, we are then in an endless redirect loop, sending the user to Auth0 trying to log in.

What we are looking for is something like this:

```php
Route::get('/', function() {
    if(!Auth::check()) {
        if (!$we_have_been_redirected_back_from_auth0_and_failed_to_login)
            return \App::make('auth0')->login(null, null, ['scope' => 'openid profile email', 'prompt' => 'none'], 'code');
        }
    }

    return view('home');
});
```

The block above `return view('home');` could be encapsulated into a nice SSO middleware.

I don't see a way to achieve this without editing the package or implementing my own solution using Auth0's RESTful APIs directly.

**Comment by pilotchase** [comment]
I have created a middleware solution that is working so far. Basically here is my structure

Website 1 (sam.example.com) - This is my system access manager. Permissions control, authentication, etc

Website 2 (jetnet.example.com) - Employee portal and company news

Everyone who wishes to access any service from my application suite must first login here. If someone attempts to access another website while logged out, they will be redirected here to login. Once logged in on sam, they are free to access any affiliate website they please. Once they login to sam and access an affiliate website, it will trigger a silent login and their requested page will then load.

So what is wrong with this setup? Well, unfortunately I have yet to be able to create an SSO style logout using this method. For example, lets say you have a 3rd client that is logged in. If you logout of sam or website 2, website 3 will remain logged in. It isn't a huge issue, unless we are talking about security (delete a user and they immediately lose access to all services). It isn't perfect but it's a start until I can create a true sso setup.
 
```
public function handle($request, Closure $next)
    {
        if(!Auth::check())
        {
            if(!isset($_SERVER['HTTP_REFERER']))
            {
                return redirect('https://sam.example.com');
            } else {
                $referer = parse_url($_SERVER['HTTP_REFERER']);
                $referer = $referer['host'];
                if($referer != 'sam.example.com')
                {
                    return redirect('https://sam.example.com');
                } else {
                    return \App::make('auth0')->login(null, null, ['scope' => 'openid profile email', 'prompt' => 'none'], 'code');
                }
            }
        } else {
            return $next($request);
        }
    }
```

**Comment by joshcanhelp** [comment]
@andzandz - Apologies for the long delay in getting back to you. Hopefully you found a way for this to work but I'll look into incorporating your scenario here into a future version of the package. It could just be as simple as including a check for the `login_required` error and redirecting back. 

@pilotchase - Thank you for sharing your solution here.

**Comment by andzandz** [comment]
We chose to not use Auth0 in the end, and built our own solution. Feel free to try and get my scenario working yourself though.
