### ISSUE TITLE
Laravel Spark Integration 

### ISSUE THREAD

**Issue by scottybo** [auth0/laravel-auth0#94]
There are many great tutorials on how to integrate Auth0 with Laravel (mainly using this package) but I can't find any guides on how to integrate with Laravel Spark.

If anyone has some experience with getting it up and running with the Spark User Repository I would be eternally grateful if you could share your knowledge.

**Comment by joshcanhelp** [comment]
@scottybo - Apologies for the delay here. I'll pass this along to our product team to evaluate. Thank you for the suggestion!
