### ISSUE TITLE
pls change config arg name

### ISSUE THREAD

**Issue by ekadesign** [auth0/laravel-auth0#95]
in the package, config name suported_algs is not valid, but in this repo config name is correct. Please change it on "supported algs". 
```
vendor/auth0/login/src/config/config.php
<?php 
return array(
    /*
    |--------------------------------------------------------------------------
    |   Supported algs by your API
    |--------------------------------------------------------------------------
    |   Algs supported by your API
    |
    */
    // 'suported_algs'        => ['HS256'],
);
```

**Comment by joshcanhelp** [comment]
@ekadesign - I'm a little confused. It's correct in the file you're referencing:

https://github.com/auth0/laravel-auth0/blob/master/src/config/config.php#L91

Is it incorrect somewhere else? This is an artifact from an old version of a JWT library we're using.

**Comment by ekadesign** [comment]
@joshcanhelp in this repo all is ok. but if you using composer require in config file on vendor dir has this bug. And my codepast from package

**Comment by joshcanhelp** [comment]
Everything should be cleared up with 5.1.0, coming out in just a bit today.
